apiVersion: v1
kind: Service
metadata:
  name: mock-llm-provider
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mock-llm-provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-llm-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-llm-provider
  template:
    metadata:
      labels:
        app: mock-llm-provider
    spec:
      containers:
        - name: httpbun
          image: sharat87/httpbun:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
