"""GET /v1/videos/{id} on fal.ai: once the queue reports COMPLETED, the proxy probes
the result URL before answering. That probe must ride the same client and headers as
the status GET, and a provider hanging up on it is transient, not a 500 (LIT-8341).

A live edge sits between the proxy and queue.fal.run so the test can see the headers
the probe carried, terminate TLS with a certificate only ``ssl_verify: false`` accepts,
or drop the connection on the probe alone. The video itself is generated by fal.ai."""

from __future__ import annotations

import threading
import time
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from types import MappingProxyType
from typing import Final

import pytest
from e2e_config import POLL_INTERVAL, PROVIDER_EDGE_ADVERTISE_HOST, PROVIDER_EDGE_BIND_HOST, unique_marker
from e2e_http import Result, Success, unwrap
from lifecycle import ResourceManager
from models import LiteLLMParamsBody, VideoCreateBody, VideoStatusResponse
from provider_edge import EdgeTls, LiveEdge, RunningEdge, self_signed_tls, start_provider_edge
from proxy_client import ProxyClient

pytestmark = pytest.mark.e2e

FAL_BACKEND: Final = "fal_ai/minimax/h3/text-to-video"
FAL_MOUNT: Final = "fal"
FAL_UPSTREAM: Final = "https://queue.fal.run"
VIDEO_PROMPT: Final = "A paper boat drifting across a puddle after rain"
VIDEO_SECONDS: Final = "5"
VIDEO_SIZE: Final = "480P"
RENDER_TIMEOUT_SECONDS: Final = 900.0
PENDING_STATUSES: Final = frozenset({"queued", "in_progress"})


def _is_result_probe(url: str) -> bool:
    return "/requests/" in url and not url.endswith("/status")


@dataclass(slots=True)
class FalRequestCapture:
    _headers_by_url: list[tuple[str, Mapping[str, str]]] = field(default_factory=list, repr=False)
    _lock: threading.Lock = field(default_factory=threading.Lock, repr=False)

    def observe(self, url: str, headers: Mapping[str, str], body: bytes | None) -> None:
        with self._lock:
            self._headers_by_url.append((url, MappingProxyType({k.lower(): v for k, v in headers.items()})))

    def probe_count(self) -> int:
        with self._lock:
            return sum(1 for url, _ in self._headers_by_url if _is_result_probe(url))

    def header_values(self, name: str, *, result_probe: bool) -> tuple[str | None, ...]:
        with self._lock:
            return tuple(
                headers.get(name.lower())
                for url, headers in self._headers_by_url
                if "/requests/" in url and _is_result_probe(url) == result_probe
            )


def _hang_up_on_result_probe(method: str, url: str) -> bool:
    return method == "GET" and _is_result_probe(url)


def _start_fal_edge(
    resources: ResourceManager, live: LiveEdge, tls: EdgeTls | None = None
) -> RunningEdge:
    edge: Final = start_provider_edge(
        live,
        mounts=MappingProxyType({FAL_MOUNT: FAL_UPSTREAM}),
        bind_host=PROVIDER_EDGE_BIND_HOST,
        advertise_host=PROVIDER_EDGE_ADVERTISE_HOST,
        forward_timeout=120.0,
        tls=tls,
    )
    resources.defer(edge.shutdown)
    return edge


def _is_pending(outcome: Result[VideoStatusResponse]) -> bool:
    match outcome:
        case Success(data=VideoStatusResponse(status=status)):
            return status in PENDING_STATUSES
        case _:
            return False


def _poll_until_settled(proxy: ProxyClient, key: str, video_id: str) -> Result[VideoStatusResponse]:
    deadline: Final = time.monotonic() + RENDER_TIMEOUT_SECONDS
    polls: Final = iter(lambda: proxy.video_status(key, video_id), None)
    for outcome in polls:
        if not _is_pending(outcome):
            return outcome
        if time.monotonic() >= deadline:
            pytest.fail(f"video {video_id} still {outcome} after {RENDER_TIMEOUT_SECONDS}s")
        time.sleep(POLL_INTERVAL)
    raise AssertionError("unreachable")


def _generate_and_settle(
    proxy: ProxyClient, resources: ResourceManager, params: LiteLLMParamsBody
) -> Result[VideoStatusResponse]:
    model: Final = f"e2e-fal-video-{unique_marker()}"
    model_id: Final = proxy.create_model(model, params, provider_live=True)
    resources.defer(lambda: proxy.delete_model(model_id))
    key: Final = resources.key()
    created: Final = unwrap(
        proxy.create_video(key, VideoCreateBody(model=model, prompt=VIDEO_PROMPT, seconds=VIDEO_SECONDS, size=VIDEO_SIZE))
    )
    return _poll_until_settled(proxy, key, created.id)


@pytest.mark.provider_edge_host
class TestFalAiVideoResultProbe:
    @pytest.mark.covers("llm.videos.fal_ai.status_retrieve.nonstream.result_probe_forwards_extra_headers")
    def test_result_probe_carries_the_deployment_extra_headers(
        self, proxy: ProxyClient, resources: ResourceManager
    ) -> None:
        capture: Final = FalRequestCapture()
        edge: Final = _start_fal_edge(resources, LiveEdge(observe_request=capture.observe))
        marker: Final = unique_marker()
        settled: Final = _generate_and_settle(
            proxy,
            resources,
            LiteLLMParamsBody(
                model=FAL_BACKEND,
                api_base=edge.edge.api_base(FAL_MOUNT),
                api_key="os.environ/FAL_AI_API_KEY",
                extra_headers={"x-e2e-routing": marker},
            ),
        )

        final: Final = unwrap(settled)
        assert final.status == "completed", final
        on_status: Final = capture.header_values("x-e2e-routing", result_probe=False)
        on_probe: Final = capture.header_values("x-e2e-routing", result_probe=True)
        assert on_status and set(on_status) == {marker}, f"status GETs lost extra_headers: {on_status}"
        assert on_probe and set(on_probe) == {marker}, f"result probes lost extra_headers: {on_probe}"

    @pytest.mark.covers("llm.videos.fal_ai.status_retrieve.nonstream.result_probe_honors_ssl_verify")
    def test_result_probe_reuses_the_ssl_verify_false_client(
        self, proxy: ProxyClient, resources: ResourceManager, tmp_path: Path
    ) -> None:
        capture: Final = FalRequestCapture()
        edge: Final = _start_fal_edge(
            resources,
            LiveEdge(observe_request=capture.observe),
            tls=self_signed_tls(tmp_path, PROVIDER_EDGE_ADVERTISE_HOST),
        )
        settled: Final = _generate_and_settle(
            proxy,
            resources,
            LiteLLMParamsBody(
                model=FAL_BACKEND,
                api_base=edge.edge.api_base(FAL_MOUNT),
                api_key="os.environ/FAL_AI_API_KEY",
                ssl_verify=False,
            ),
        )

        final: Final = unwrap(settled)
        assert final.status == "completed", final
        assert capture.probe_count(), "no result probe reached the edge"

    @pytest.mark.covers("llm.videos.fal_ai.status_retrieve.nonstream.result_probe_hangup_stays_completed")
    def test_provider_hanging_up_on_the_result_probe_keeps_the_completed_status(
        self, proxy: ProxyClient, resources: ResourceManager
    ) -> None:
        edge: Final = _start_fal_edge(resources, LiveEdge(hang_up=_hang_up_on_result_probe))
        settled: Final = _generate_and_settle(
            proxy,
            resources,
            LiteLLMParamsBody(
                model=FAL_BACKEND,
                api_base=edge.edge.api_base(FAL_MOUNT),
                api_key="os.environ/FAL_AI_API_KEY",
            ),
        )

        final: Final = unwrap(settled)
        assert final.status == "completed" and final.error is None, final
