contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - wolfi-base
    - bash
    - libevent
    - libsndfile
    - libssl3
    - nodejs-26
    - openssl-4.0
    - python-3.13
    - tzdata

archs:
  - x86_64
  - aarch64

environment:
  PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
