#!/usr/bin/env python3
"""Coverage gate for PR1 (ProxyLogging) of the ``proxy/utils.py`` plan.

CLI: ``python _coverage_check.py`` (no flags). Reads ``.cov_new.xml`` from
the working directory (generated by the prior pytest run with
``--cov=litellm.proxy.utils --cov-branch --cov-report=xml:.cov_new.xml``),
filters coverage to PR1's line range, and prints ``PASS`` / ``FAIL``.

Never prints numbers.
"""

from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

_LINE_START = 158
_LINE_END = 2665
_LINE_TARGET_RATE = 0.50
_BRANCH_TARGET_RATE = 0.30


def _filtered_rates(xml_path: Path):
    tree = ET.parse(xml_path)
    root = tree.getroot()
    total_lines = 0
    covered_lines = 0
    total_branches = 0
    covered_branches = 0
    for class_elem in root.iter("class"):
        filename = class_elem.get("filename", "")
        if not (filename.endswith("proxy/utils.py") or filename.endswith("/proxy/utils.py") or filename == "litellm/proxy/utils.py"):
            continue
        lines_elem = class_elem.find("lines")
        if lines_elem is None:
            continue
        for line in lines_elem.findall("line"):
            num = int(line.get("number", "0"))
            if num < _LINE_START or num > _LINE_END:
                continue
            hits = int(line.get("hits", "0"))
            total_lines += 1
            if hits > 0:
                covered_lines += 1
            cond = line.get("condition-coverage")
            if cond:
                inside = cond.split("(", 1)[1].rstrip(")")
                covered, total = inside.split("/")
                total_branches += int(total)
                covered_branches += int(covered)
    if total_lines == 0:
        return None
    line_rate = covered_lines / total_lines
    branch_rate = covered_branches / total_branches if total_branches else 1.0
    return line_rate, branch_rate


def main() -> int:
    xml_path = Path(".cov_new.xml")
    if not xml_path.is_file():
        print(f"coverage xml not found at {xml_path.resolve()}", file=sys.stderr)
        print("FAIL")
        return 1
    rates = _filtered_rates(xml_path)
    if rates is None:
        print("no coverage data for litellm/proxy/utils.py in range", file=sys.stderr)
        print("FAIL")
        return 1
    line_rate, branch_rate = rates
    ok = line_rate >= _LINE_TARGET_RATE and branch_rate >= _BRANCH_TARGET_RATE
    print("PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
