use std::{borrow::Cow, path::Path};

use schemars::{JsonSchema, Schema, SchemaGenerator, generate::SchemaSettings};
use serde_json::{Value, json};

use crate::DbFailure;

const QUERY_ROOT: &str = "../../../litellm/proxy/db/queries/";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Cardinality {
    Many,
    Optional,
    One,
    Execute,
}

impl Cardinality {
    fn descriptor(self) -> &'static str {
        match self {
            Self::Many => "ManyQuery",
            Self::Optional => "OptionalQuery",
            Self::One => "OneQuery",
            Self::Execute => "ExecuteQuery",
        }
    }
}

#[derive(Clone, Copy)]
pub struct Model {
    name: fn() -> Cow<'static, str>,
    schema: fn(&mut SchemaGenerator) -> Schema,
}

impl Model {
    pub const fn of<T: JsonSchema>() -> Self {
        Self {
            name: T::schema_name,
            schema: SchemaGenerator::subschema_for::<T>,
        }
    }

    fn name(self) -> Cow<'static, str> {
        (self.name)()
    }
}

pub struct QuerySpec {
    pub name: &'static str,
    pub file: &'static str,
    pub cardinality: Cardinality,
    pub arguments: &'static [&'static str],
    pub params: Model,
    pub row: Option<Model>,
}

impl QuerySpec {
    fn models(&self) -> impl Iterator<Item = Model> {
        [Some(self.params), self.row].into_iter().flatten()
    }
}

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
pub enum CodegenError {
    #[error("`{query}` reads {file}, which is not a .sql file under {QUERY_ROOT}")]
    OutsideQueryRoot {
        query: &'static str,
        file: &'static str,
    },
}

pub fn schema_document(queries: &[&QuerySpec]) -> Value {
    let mut generator = SchemaSettings::draft2020_12()
        .for_serialize()
        .into_generator();
    generator.subschema_for::<DbFailure>();
    for model in queries.iter().flat_map(|query| query.models()) {
        (model.schema)(&mut generator);
    }
    json!({
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$defs": generator.take_definitions(true),
    })
}

pub fn catalog_module(queries: &[&QuerySpec]) -> Result<String, CodegenError> {
    let descriptors = queries
        .iter()
        .map(|query| descriptor(query))
        .collect::<Result<Vec<_>, _>>()?;
    if descriptors.is_empty() {
        return Ok(String::from(HEADER));
    }
    let mut models: Vec<_> = queries
        .iter()
        .flat_map(|query| query.models())
        .map(Model::name)
        .collect();
    models.sort();
    models.dedup();
    let mut kinds: Vec<_> = queries
        .iter()
        .map(|query| query.cardinality.descriptor())
        .collect();
    kinds.sort_unstable();
    kinds.dedup();
    Ok(format!(
        "{HEADER}\nfrom typing import Final\n\nfrom litellm.proxy.db.queries import load\nfrom litellm.proxy.db.queries.generated.models import {}\nfrom litellm.proxy.db.queries.runtime import {}\n{}",
        models.join(", "),
        kinds.join(", "),
        descriptors.concat(),
    ))
}

const HEADER: &str =
    "# @generated by `make db-codegen` from litellm-rust/crates/db. Do not edit.\n";

fn descriptor(query: &QuerySpec) -> Result<String, CodegenError> {
    let outside = || CodegenError::OutsideQueryRoot {
        query: query.name,
        file: query.file,
    };
    let relative = query
        .file
        .strip_prefix("../../../")
        .and_then(|path| path.strip_suffix(".sql"))
        .filter(|_| query.file.starts_with(QUERY_ROOT))
        .ok_or_else(outside)?;
    let path = Path::new(relative);
    let (Some(package), Some(stem)) = (path.parent(), path.file_name()) else {
        return Err(outside());
    };
    let package = package.to_string_lossy().replace('/', ".");
    let stem = stem.to_string_lossy();
    let arguments: String = query
        .arguments
        .iter()
        .map(|argument| format!("\"{argument}\", "))
        .collect();
    let row = query
        .row
        .map(|row| format!("    row={},\n", row.name()))
        .unwrap_or_default();
    Ok(format!(
        "\n{constant}: Final = {kind}(\n    sql=load(\"{package}\", \"{stem}\"),\n    arguments=({arguments}),\n    params={params},\n{row})\n",
        constant = query.name.to_uppercase(),
        kind = query.cardinality.descriptor(),
        arguments = arguments.trim_end_matches(' '),
        params = query.params.name(),
    ))
}
