#!/bin/sh

set -e

[ "$(git branch --show-current)" = main ] || SUFFIX="-dev"
cat << EOF > "${GITHUB_OUTPUT}"
image=ghcr.io/${GITHUB_REPOSITORY_OWNER}/$(basename "${PWD}")${SUFFIX}
version=$("$(dirname $0)"/version)
EOF
