package litellm

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"reflect"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

const (
	endpointBudgetNew    = "/budget/new"
	endpointBudgetInfo   = "/budget/info"
	endpointBudgetUpdate = "/budget/update"
	endpointBudgetDelete = "/budget/delete"
)

func budgetSuppressEquivalentJSON(k, oldValue, newValue string, d *schema.ResourceData) bool {
	var oldParsed, newParsed interface{}
	if err := json.Unmarshal([]byte(oldValue), &oldParsed); err != nil {
		return false
	}
	if err := json.Unmarshal([]byte(newValue), &newParsed); err != nil {
		return false
	}
	return reflect.DeepEqual(oldParsed, newParsed)
}

func resourceLiteLLMBudget() *schema.Resource {
	return &schema.Resource{
		Create: resourceLiteLLMBudgetCreate,
		Read:   resourceLiteLLMBudgetRead,
		Update: resourceLiteLLMBudgetUpdate,
		Delete: resourceLiteLLMBudgetDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},

		Schema: map[string]*schema.Schema{
			"budget_id": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				Description: "Unique ID for the budget. Generated by the server if not provided",
			},
			"max_budget": {
				Type:        schema.TypeFloat,
				Optional:    true,
				Description: "Requests fail if this budget in USD is exceeded",
			},
			"soft_budget": {
				Type:        schema.TypeFloat,
				Optional:    true,
				Description: "Requests do not fail if this is exceeded, but alerts fire",
			},
			"max_parallel_requests": {
				Type:        schema.TypeInt,
				Optional:    true,
				Description: "Maximum concurrent requests allowed for this budget",
			},
			"tpm_limit": {
				Type:        schema.TypeInt,
				Optional:    true,
				Description: "Maximum tokens per minute allowed for this budget",
			},
			"rpm_limit": {
				Type:        schema.TypeInt,
				Optional:    true,
				Description: "Maximum requests per minute allowed for this budget",
			},
			"budget_duration": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Budget reset period (e.g. '1hr', '1d', '28d')",
			},
			"model_max_budget": {
				Type:             schema.TypeString,
				Optional:         true,
				ValidateFunc:     validation.StringIsJSON,
				DiffSuppressFunc: budgetSuppressEquivalentJSON,
				Description:      "JSON string of per-model budget config (e.g. '{\"gpt-4o\": {\"max_budget\": 10.0}}')",
			},
			"budget_reset_at": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Datetime when the budget is reset",
			},
		},
	}
}

type budgetResponse struct {
	BudgetID            string      `json:"budget_id"`
	MaxBudget           *float64    `json:"max_budget"`
	SoftBudget          *float64    `json:"soft_budget"`
	MaxParallelRequests *int        `json:"max_parallel_requests"`
	TPMLimit            *int        `json:"tpm_limit"`
	RPMLimit            *int        `json:"rpm_limit"`
	BudgetDuration      *string     `json:"budget_duration"`
	ModelMaxBudget      interface{} `json:"model_max_budget"`
	BudgetResetAt       *string     `json:"budget_reset_at"`
}

func budgetModelMaxBudgetString(v interface{}) (string, bool) {
	switch typed := v.(type) {
	case string:
		return typed, typed != ""
	case map[string]interface{}:
		if len(typed) == 0 {
			return "", false
		}
		encoded, err := json.Marshal(typed)
		return string(encoded), err == nil
	}
	return "", false
}

func setBudgetState(d *schema.ResourceData, budgetResp budgetResponse) {
	if budgetResp.MaxBudget != nil {
		d.Set("max_budget", *budgetResp.MaxBudget)
	}
	if budgetResp.SoftBudget != nil {
		d.Set("soft_budget", *budgetResp.SoftBudget)
	}
	if budgetResp.MaxParallelRequests != nil {
		d.Set("max_parallel_requests", *budgetResp.MaxParallelRequests)
	}
	if budgetResp.TPMLimit != nil {
		d.Set("tpm_limit", *budgetResp.TPMLimit)
	}
	if budgetResp.RPMLimit != nil {
		d.Set("rpm_limit", *budgetResp.RPMLimit)
	}
	if budgetResp.BudgetDuration != nil {
		d.Set("budget_duration", *budgetResp.BudgetDuration)
	}
	if encoded, ok := budgetModelMaxBudgetString(budgetResp.ModelMaxBudget); ok {
		d.Set("model_max_budget", encoded)
	}
	if budgetResp.BudgetResetAt != nil {
		d.Set("budget_reset_at", *budgetResp.BudgetResetAt)
	}
}

func resourceLiteLLMBudgetCreate(d *schema.ResourceData, m interface{}) error {
	client := m.(*Client)

	budgetData := buildBudgetData(d)
	if v, ok := d.GetOk("budget_id"); ok {
		budgetData["budget_id"] = v.(string)
	}

	log.Printf("[DEBUG] Create budget request payload: %+v", budgetData)

	resp, err := MakeRequest(client, "POST", endpointBudgetNew, budgetData)
	if err != nil {
		return fmt.Errorf("error creating budget: %w", err)
	}
	defer resp.Body.Close()

	if err := handleResponse(resp, "creating budget"); err != nil {
		return err
	}

	var budgetResp budgetResponse
	if err := json.NewDecoder(resp.Body).Decode(&budgetResp); err != nil {
		return fmt.Errorf("error decoding create budget response: %w", err)
	}
	if budgetResp.BudgetID == "" {
		return fmt.Errorf("create budget response did not contain a budget_id")
	}

	d.SetId(budgetResp.BudgetID)
	log.Printf("[INFO] Budget created with ID: %s", budgetResp.BudgetID)

	return resourceLiteLLMBudgetRead(d, m)
}

func resourceLiteLLMBudgetRead(d *schema.ResourceData, m interface{}) error {
	client := m.(*Client)

	log.Printf("[INFO] Reading budget with ID: %s", d.Id())

	resp, err := MakeRequest(client, "POST", endpointBudgetInfo, map[string]interface{}{
		"budgets": []string{d.Id()},
	})
	if err != nil {
		return fmt.Errorf("error reading budget: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusNotFound {
		log.Printf("[WARN] Budget with ID %s not found, removing from state", d.Id())
		d.SetId("")
		return nil
	}

	if err := handleResponse(resp, "reading budget"); err != nil {
		return err
	}

	var budgetResps []budgetResponse
	if err := json.NewDecoder(resp.Body).Decode(&budgetResps); err != nil {
		return fmt.Errorf("error decoding budget info response: %w", err)
	}
	if len(budgetResps) == 0 {
		log.Printf("[WARN] Budget with ID %s not found in response, removing from state", d.Id())
		d.SetId("")
		return nil
	}

	d.Set("budget_id", d.Id())
	setBudgetState(d, budgetResps[0])

	log.Printf("[INFO] Successfully read budget with ID: %s", d.Id())
	return nil
}

func resourceLiteLLMBudgetUpdate(d *schema.ResourceData, m interface{}) error {
	client := m.(*Client)

	budgetData := buildBudgetData(d)
	budgetData["budget_id"] = d.Id()

	log.Printf("[DEBUG] Update budget request payload: %+v", budgetData)

	resp, err := MakeRequest(client, "POST", endpointBudgetUpdate, budgetData)
	if err != nil {
		return fmt.Errorf("error updating budget: %w", err)
	}
	defer resp.Body.Close()

	if err := handleResponse(resp, "updating budget"); err != nil {
		return err
	}

	log.Printf("[INFO] Successfully updated budget with ID: %s", d.Id())
	return resourceLiteLLMBudgetRead(d, m)
}

func resourceLiteLLMBudgetDelete(d *schema.ResourceData, m interface{}) error {
	client := m.(*Client)

	log.Printf("[INFO] Deleting budget with ID: %s", d.Id())

	resp, err := MakeRequest(client, "POST", endpointBudgetDelete, map[string]interface{}{
		"id": d.Id(),
	})
	if err != nil {
		return fmt.Errorf("error deleting budget: %w", err)
	}
	defer resp.Body.Close()

	if err := handleResponse(resp, "deleting budget"); err != nil {
		return err
	}

	log.Printf("[INFO] Successfully deleted budget with ID: %s", d.Id())
	d.SetId("")
	return nil
}

func buildBudgetData(d *schema.ResourceData) map[string]interface{} {
	budgetData := map[string]interface{}{}

	for _, key := range []string{
		"max_budget", "soft_budget", "max_parallel_requests", "tpm_limit", "rpm_limit", "budget_duration",
	} {
		if v, ok := d.GetOk(key); ok {
			budgetData[key] = v
		}
	}

	if v, ok := d.GetOk("model_max_budget"); ok {
		var parsed map[string]interface{}
		if err := json.Unmarshal([]byte(v.(string)), &parsed); err == nil {
			budgetData["model_max_budget"] = parsed
		}
	}

	return budgetData
}
