package litellm

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"net/url"
	"reflect"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

const (
	endpointUserNew    = "/user/new"
	endpointUserInfo   = "/user/info"
	endpointUserUpdate = "/user/update"
	endpointUserDelete = "/user/delete"
)

func userSuppressEquivalentJSON(k, oldValue, newValue string, d *schema.ResourceData) bool {
	var oldParsed, newParsed interface{}
	if err := json.Unmarshal([]byte(oldValue), &oldParsed); err != nil {
		return false
	}
	if err := json.Unmarshal([]byte(newValue), &newParsed); err != nil {
		return false
	}
	return reflect.DeepEqual(oldParsed, newParsed)
}

func resourceLiteLLMUser() *schema.Resource {
	return &schema.Resource{
		Create: resourceLiteLLMUserCreate,
		Read:   resourceLiteLLMUserRead,
		Update: resourceLiteLLMUserUpdate,
		Delete: resourceLiteLLMUserDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},

		Schema: map[string]*schema.Schema{
			"user_id": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				Description: "Unique ID for the user. Generated by the server if not provided",
			},
			"user_email": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Email address of the user",
			},
			"user_alias": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Descriptive name for the user",
			},
			"user_role": {
				Type:     schema.TypeString,
				Optional: true,
				ValidateFunc: validation.StringInSlice([]string{
					"proxy_admin", "proxy_admin_viewer", "internal_user", "internal_user_viewer",
				}, false),
				Description: "Role of the user on the proxy",
			},
			"teams": {
				Type:        schema.TypeList,
				Optional:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Description: "List of team IDs the user belongs to",
			},
			"models": {
				Type:        schema.TypeList,
				Optional:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Description: "Models the user is allowed to call",
			},
			"max_budget": {
				Type:        schema.TypeFloat,
				Optional:    true,
				Description: "Maximum budget in USD for the user",
			},
			"budget_duration": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Budget reset period (e.g. '30s', '30m', '30d')",
			},
			"tpm_limit": {
				Type:        schema.TypeInt,
				Optional:    true,
				Description: "Tokens per minute limit for the user",
			},
			"rpm_limit": {
				Type:        schema.TypeInt,
				Optional:    true,
				Description: "Requests per minute limit for the user",
			},
			"max_parallel_requests": {
				Type:        schema.TypeInt,
				Optional:    true,
				Description: "Maximum number of parallel requests for the user",
			},
			"metadata": {
				Type:        schema.TypeMap,
				Optional:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Description: "Metadata for the user",
			},
			"auto_create_key": {
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     true,
				ForceNew:    true,
				Description: "Whether to auto-create an API key for the user on creation",
			},
			"send_invite_email": {
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     false,
				ForceNew:    true,
				Description: "Whether to send an invite email to the user on creation",
			},
			"key_alias": {
				Type:        schema.TypeString,
				Optional:    true,
				Description: "Alias for the auto-created API key",
			},
			"aliases": {
				Type:        schema.TypeMap,
				Optional:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Description: "Model aliases for the user",
			},
			"config": {
				Type:        schema.TypeMap,
				Optional:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Description: "Config values for the user",
			},
			"permissions": {
				Type:        schema.TypeMap,
				Optional:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Description: "Permission values for the user",
			},
			"model_max_budget": {
				Type:             schema.TypeString,
				Optional:         true,
				ValidateFunc:     validation.StringIsJSON,
				DiffSuppressFunc: userSuppressEquivalentJSON,
				Description:      "JSON string of per-model budget config (e.g. '{\"gpt-4o\": {\"max_budget\": 10.0}}')",
			},
			"guardrails": {
				Type:        schema.TypeList,
				Optional:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
				Description: "Guardrails applied to the user's requests",
			},
			"blocked": {
				Type:        schema.TypeBool,
				Optional:    true,
				Default:     false,
				Description: "Whether the user is blocked from making requests",
			},
			"key": {
				Type:        schema.TypeString,
				Computed:    true,
				Sensitive:   true,
				Description: "Auto-created API key for the user (when auto_create_key is true)",
			},
		},
	}
}

type userNewResponse struct {
	UserID string `json:"user_id"`
	Key    string `json:"key"`
}

type userInfoResponse struct {
	UserID   string                 `json:"user_id"`
	UserInfo map[string]interface{} `json:"user_info"`
}

func resourceLiteLLMUserCreate(d *schema.ResourceData, m interface{}) error {
	client := m.(*Client)

	userData := buildUserData(d)
	if v, ok := d.GetOk("user_id"); ok {
		userData["user_id"] = v.(string)
	}
	userData["auto_create_key"] = d.Get("auto_create_key").(bool)
	userData["send_invite_email"] = d.Get("send_invite_email").(bool)

	log.Printf("[DEBUG] Create user request payload: %+v", userData)

	resp, err := MakeRequest(client, "POST", endpointUserNew, userData)
	if err != nil {
		return fmt.Errorf("error creating user: %w", err)
	}
	defer resp.Body.Close()

	if err := handleResponse(resp, "creating user"); err != nil {
		return err
	}

	var userResp userNewResponse
	if err := json.NewDecoder(resp.Body).Decode(&userResp); err != nil {
		return fmt.Errorf("error decoding create user response: %w", err)
	}
	if userResp.UserID == "" {
		return fmt.Errorf("create user response did not contain a user_id")
	}

	d.SetId(userResp.UserID)
	if userResp.Key != "" {
		d.Set("key", userResp.Key)
	}
	log.Printf("[INFO] User created with ID: %s", userResp.UserID)

	return resourceLiteLLMUserRead(d, m)
}

func resourceLiteLLMUserRead(d *schema.ResourceData, m interface{}) error {
	client := m.(*Client)

	log.Printf("[INFO] Reading user with ID: %s", d.Id())

	resp, err := MakeRequest(client, "GET", fmt.Sprintf("%s?user_id=%s", endpointUserInfo, url.QueryEscape(d.Id())), nil)
	if err != nil {
		return fmt.Errorf("error reading user: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode == http.StatusNotFound {
		log.Printf("[WARN] User with ID %s not found, removing from state", d.Id())
		d.SetId("")
		return nil
	}

	if err := handleResponse(resp, "reading user"); err != nil {
		return err
	}

	var infoResp userInfoResponse
	if err := json.NewDecoder(resp.Body).Decode(&infoResp); err != nil {
		return fmt.Errorf("error decoding user info response: %w", err)
	}
	if infoResp.UserInfo == nil {
		log.Printf("[WARN] User with ID %s has no user_info, removing from state", d.Id())
		d.SetId("")
		return nil
	}

	d.Set("user_id", d.Id())
	setUserStateFromInfo(d, infoResp.UserInfo)

	log.Printf("[INFO] Successfully read user with ID: %s", d.Id())
	return nil
}

func setUserStateFromInfo(d *schema.ResourceData, info map[string]interface{}) {
	for _, key := range []string{"user_email", "user_alias", "user_role", "budget_duration"} {
		if v, ok := info[key].(string); ok && v != "" {
			d.Set(key, v)
		}
	}
	if v, ok := info["max_budget"].(float64); ok {
		d.Set("max_budget", v)
	}
	for _, key := range []string{"tpm_limit", "rpm_limit", "max_parallel_requests"} {
		if v, ok := info[key].(float64); ok {
			d.Set(key, int(v))
		}
	}
	for _, key := range []string{"teams", "models"} {
		if v, ok := info[key].([]interface{}); ok && len(v) > 0 {
			d.Set(key, v)
		}
	}
	if v, ok := info["metadata"].(map[string]interface{}); ok && len(v) > 0 {
		d.Set("metadata", v)
	}
	if v, ok := info["model_max_budget"].(map[string]interface{}); ok && len(v) > 0 {
		if encoded, err := json.Marshal(v); err == nil {
			d.Set("model_max_budget", string(encoded))
		}
	}
}

func resourceLiteLLMUserUpdate(d *schema.ResourceData, m interface{}) error {
	client := m.(*Client)

	userData := buildUserData(d)
	userData["user_id"] = d.Id()

	log.Printf("[DEBUG] Update user request payload: %+v", userData)

	resp, err := MakeRequest(client, "POST", endpointUserUpdate, userData)
	if err != nil {
		return fmt.Errorf("error updating user: %w", err)
	}
	defer resp.Body.Close()

	if err := handleResponse(resp, "updating user"); err != nil {
		return err
	}

	log.Printf("[INFO] Successfully updated user with ID: %s", d.Id())
	return resourceLiteLLMUserRead(d, m)
}

func resourceLiteLLMUserDelete(d *schema.ResourceData, m interface{}) error {
	client := m.(*Client)

	log.Printf("[INFO] Deleting user with ID: %s", d.Id())

	resp, err := MakeRequest(client, "POST", endpointUserDelete, map[string]interface{}{
		"user_ids": []string{d.Id()},
	})
	if err != nil {
		return fmt.Errorf("error deleting user: %w", err)
	}
	defer resp.Body.Close()

	if err := handleResponse(resp, "deleting user"); err != nil {
		return err
	}

	log.Printf("[INFO] Successfully deleted user with ID: %s", d.Id())
	d.SetId("")
	return nil
}

func buildUserData(d *schema.ResourceData) map[string]interface{} {
	userData := map[string]interface{}{
		"blocked": d.Get("blocked").(bool),
	}

	for _, key := range []string{
		"user_email", "user_alias", "user_role", "teams", "models", "max_budget",
		"budget_duration", "tpm_limit", "rpm_limit", "max_parallel_requests",
		"metadata", "key_alias", "aliases", "config", "permissions", "guardrails",
	} {
		if v, ok := d.GetOk(key); ok {
			userData[key] = v
		}
	}

	if v, ok := d.GetOk("model_max_budget"); ok {
		var parsed map[string]interface{}
		if err := json.Unmarshal([]byte(v.(string)), &parsed); err == nil {
			userData["model_max_budget"] = parsed
		}
	}

	return userData
}
