general_settings:
   database_url: os.environ/DATABASE_URL
   master_key: "sk-1234"
   allow_client_side_credentials: true

litellm_settings:
   callbacks: ["prometheus", "arize_phoenix"]


model_list:
  - model_name: gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY
  - model_name: gemini-3.6-flash
    litellm_params:
      model: gemini/gemini-3.6-flash
      api_key: os.environ/GEMINI_API_KEY
