model_list:
  - model_name: claude-sonnet-4-6
    litellm_params:
      model: bedrock/converse/global.anthropic.claude-sonnet-4-6
      # aws_region_name: "global"
  - model_name: claude-sonnet-4-5
    litellm_params:
      model: bedrock/converse/global.anthropic.claude-sonnet-4-5-20250929-v1:0
      # aws_region_name: "global"
  - model_name: gpt-5.4-mini
    litellm_params:
      model: openai/gpt-5.4-mini
      api_key: os.environ/OPENAI_API_KEY

general_settings:
  context_management_summary_model: gpt-5.4-mini

litellm_settings:
  use_chat_completions_url_for_anthropic_messages: true