model_list:
  - model_name: anthropic/*
    litellm_params:
      model: anthropic/*
  - model_name: azure_ai/claude-opus-4-6
    litellm_params:
      model: azure_ai/claude-opus-4-6
      api_base: https://ai-eisgptphiai810714567559.services.ai.azure.com
      api_key: os.environ/AZURE_AI_API_KEY
      cache_control_injection_points:
        - role: system
          location: message
      drop_params: true


router_settings:
  routing_strategy: usage-based-routing-v2
  enable_pre_call_checks: true

files_settings:
  - custom_llm_provider: openai
