model_list:
  - model_name: minimax/minimax-m3:free
    litellm_params:
      model: openai/minimax/minimax-m3:free
      api_key: sk-or-v1-REDACTED
      api_base: https://openrouter.ai/api/v1

general_settings:
  master_key: test123
