from __future__ import annotations

import os
import platform
import traceback
from dataclasses import dataclass
from pathlib import Path
from typing import Final, Literal
from urllib.parse import urlencode

import litellm
from litellm._logging import redact_secrets
from litellm._version import version as litellm_version

ISSUE_URL_BASE: Final = "https://github.com/BerriAI/litellm/issues/new"
MAX_URL_LENGTH: Final = 6000
MAX_MESSAGE_CHARS: Final = 600
MAX_FRAMES: Final = 12
DISABLE_ENV_VAR: Final = "LITELLM_DISABLE_BUG_REPORT_LINK"
_SHORTENED_MESSAGE_LENGTHS: Final = (480, 360, 240, 120, 0)

Surface = Literal["sdk", "proxy"]


@dataclass(frozen=True, slots=True)
class BugReport:
    surface: Surface
    exception_type: str
    exception_message: str
    litellm_frames: tuple[str, ...]
    litellm_version: str
    python_version: str
    os_platform: str
    call_type: str | None
    model: str | None
    custom_llm_provider: str | None


def bug_report_enabled() -> bool:
    return os.getenv(DISABLE_ENV_VAR, "").lower() != "true"


def _format_frame(frame: traceback.FrameSummary, package_dir: Path, package_parent: Path) -> str | None:
    frame_path: Final = Path(frame.filename).resolve()
    try:
        frame_path.relative_to(package_dir)
        relative_path: Final = frame_path.relative_to(package_parent)
    except ValueError:
        return None
    return f"{relative_path.as_posix()}:{frame.lineno} in {frame.name}"


def _get_litellm_frames(exc: BaseException) -> tuple[str, ...]:
    package_file: Final = getattr(litellm, "__file__", None)
    if not isinstance(package_file, str) or exc.__traceback__ is None:
        return ()
    package_dir: Final = Path(package_file).resolve().parent
    package_parent: Final = package_dir.parent
    return tuple(
        frame_text
        for frame in traceback.extract_tb(exc.__traceback__)
        if (frame_text := _format_frame(frame, package_dir, package_parent)) is not None
    )[-MAX_FRAMES:]


def _redact_context(value: str | None) -> str | None:
    if value is None:
        return None
    return redact_secrets(value)[:MAX_MESSAGE_CHARS]


def build_bug_report(
    exc: BaseException,
    *,
    surface: Surface,
    call_type: str | None = None,
    model: str | None = None,
    custom_llm_provider: str | None = None,
) -> BugReport:
    exception_message: Final = redact_secrets(str(exc))[:MAX_MESSAGE_CHARS]
    return BugReport(
        surface=surface,
        exception_type=type(exc).__name__,
        exception_message=exception_message,
        litellm_frames=_get_litellm_frames(exc),
        litellm_version=litellm_version,
        python_version=platform.python_version(),
        os_platform=platform.platform(terse=True),
        call_type=_redact_context(call_type),
        model=_redact_context(model),
        custom_llm_provider=_redact_context(custom_llm_provider),
    )


def _domain(report: BugReport) -> str:
    if report.surface == "sdk":
        return "Python SDK: the litellm package itself"
    if report.custom_llm_provider is not None:
        return "LLM translation: a specific provider's request or response"
    return "Proxy core: startup, config, health checks, endpoints"


def _description(report: BugReport, message: str, frames: tuple[str, ...]) -> str:
    frame_text: Final = "\n".join(frames)
    return (
        "Auto-generated by LiteLLM's bug report link. Please describe what you were doing above this line.\n\n"
        f"```\n{report.exception_type}: {message}\n```\n\n"
        f"LiteLLM frames:\n```\n{frame_text}\n```\n\n"
        f"Surface: {report.surface}\n"
        f"Endpoint / call: {report.call_type or 'unknown'}\n"
        f"Model: {report.model or 'unknown'}\n"
        f"Provider: {report.custom_llm_provider or 'unknown'}\n"
        f"LiteLLM: {report.litellm_version}\n"
        f"Python: {report.python_version}\n"
        f"OS: {report.os_platform}\n"
    )


def _issue_url(report: BugReport, message: str, frames: tuple[str, ...]) -> str:
    deployment: Final[tuple[tuple[str, str], ...]] = (
        (("deployment", "pip / Python SDK"),)
        if report.surface == "sdk"
        else (("deployment", "Docker"),)
        if os.path.exists("/.dockerenv")
        else ()
    )
    fields: Final = (
        ("template", "bug_report.yml"),
        ("labels", "bug"),
        ("title", f"[Bug]: {report.exception_type}: {message[:80]}"),
        ("version", report.litellm_version),
        ("domain", _domain(report)),
        ("description", _description(report, message, frames)),
    ) + deployment
    return f"{ISSUE_URL_BASE}?{urlencode(fields)}"


def bug_report_issue_url(report: BugReport) -> str:
    frames: Final = report.litellm_frames
    message: Final = report.exception_message
    candidates: Final = (
        *(_issue_url(report, message, frames[index:]) for index in range(len(frames) + 1)),
        *(_issue_url(report, message[:length], ()) for length in _SHORTENED_MESSAGE_LENGTHS if length < len(message)),
    )
    return next((candidate for candidate in candidates if len(candidate) <= MAX_URL_LENGTH), _issue_url(report, "", ()))


def bug_report_notice(report: BugReport) -> str:
    return (
        "This looks like a bug in LiteLLM rather than in your request. File it with one click "
        f"(prefilled and redacted, review before submitting): {bug_report_issue_url(report)}"
    )
