from __future__ import annotations

import os
import platform
import traceback
from dataclasses import dataclass
from pathlib import Path
from typing import Final, Literal
from urllib.parse import urlencode

import litellm
from litellm._version import version as litellm_version
from litellm.types.utils import LlmProviders

ISSUE_URL_BASE: Final = "https://github.com/BerriAI/litellm/issues/new"
MAX_URL_LENGTH: Final = 6000
MAX_FRAMES: Final = 12
DISABLE_ENV_VAR: Final = "LITELLM_DISABLE_BUG_REPORT_LINK"
NOTICE_PREFIX: Final = "This looks like a bug in LiteLLM rather than in your request."
KNOWN_PROVIDERS: Final = frozenset(provider.value for provider in LlmProviders)

Surface = Literal["sdk", "proxy"]


@dataclass(frozen=True, slots=True)
class EnvironmentReport:
    surface: Surface
    litellm_version: str
    python_version: str
    deployment: str | None
    config_lines: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class BugReport:
    environment: EnvironmentReport
    exception_type: str
    litellm_frames: tuple[str, ...]
    call_type: str | None
    custom_llm_provider: str | None
    stream: bool | None


def bug_report_enabled() -> bool:
    return os.getenv(DISABLE_ENV_VAR, "").lower() != "true"


def should_report_bug(exc: object) -> bool:
    return bug_report_enabled() and isinstance(exc, BaseException) and getattr(exc, "status_code", None) is None


def _format_frame(frame: traceback.FrameSummary, package_dir: Path, package_parent: Path) -> str | None:
    frame_path: Final = Path(frame.filename).resolve()
    try:
        frame_path.relative_to(package_dir)
        relative_path: Final = frame_path.relative_to(package_parent)
    except ValueError:
        return None
    return f"{relative_path.as_posix()}:{frame.lineno} in {frame.name}"


def _get_litellm_frames(exc: BaseException) -> tuple[str, ...]:
    if exc.__traceback__ is None:
        return ()
    package_dir: Final = Path(litellm.__file__).resolve().parent
    package_parent: Final = package_dir.parent
    return tuple(
        frame_text
        for frame in traceback.extract_tb(exc.__traceback__)
        if (frame_text := _format_frame(frame, package_dir, package_parent)) is not None
    )[-MAX_FRAMES:]


def allowlisted(value: object, allowed: frozenset[str]) -> str | None:
    return value if isinstance(value, str) and value in allowed else None


def _deployment(surface: Surface) -> str | None:
    if surface == "sdk":
        return "pip / Python SDK"
    return "Docker" if os.path.exists("/.dockerenv") else None


def build_environment_report(*, surface: Surface, config_lines: tuple[str, ...] = ()) -> EnvironmentReport:
    return EnvironmentReport(
        surface=surface,
        litellm_version=litellm_version,
        python_version=platform.python_version(),
        deployment=_deployment(surface),
        config_lines=config_lines,
    )


def build_bug_report(
    exc: BaseException,
    *,
    surface: Surface,
    call_type: str | None = None,
    custom_llm_provider: object = None,
    stream: object = None,
    config_lines: tuple[str, ...] = (),
) -> BugReport:
    return BugReport(
        environment=build_environment_report(surface=surface, config_lines=config_lines),
        exception_type=type(exc).__name__,
        litellm_frames=_get_litellm_frames(exc),
        call_type=call_type,
        custom_llm_provider=allowlisted(custom_llm_provider, KNOWN_PROVIDERS),
        stream=stream if isinstance(stream, bool) else None,
    )


def _domain(report: BugReport) -> str:
    if report.environment.surface == "sdk":
        return "Python SDK: the litellm package itself"
    if report.custom_llm_provider is not None:
        return "LLM translation: a specific provider's request or response"
    return "Proxy core: startup, config, health checks, endpoints"


def _title(report: BugReport, frames: tuple[str, ...]) -> str:
    location: Final = frames[-1].split(":", 1)[0] if frames else "litellm"
    return f"[Bug]: {report.exception_type} in {location}"


def _description(report: BugReport, frames: tuple[str, ...], config_lines: tuple[str, ...]) -> str:
    frame_block: Final = "LiteLLM frames:\n```\n" + "\n".join(frames) + "\n```\n\n" if frames else ""
    stream_line: Final = "" if report.stream is None else f"Stream: {str(report.stream).lower()}\n"
    config_block: Final = (
        "\nConfig (true/false flags and LiteLLM-defined values only):\n```\n" + "\n".join(config_lines) + "\n```\n"
        if config_lines
        else ""
    )
    return (
        "Auto-generated by LiteLLM's bug report link. It carries no request data or error text. "
        "Please describe what you were doing, and paste the error message from your log below "
        "if it contains nothing sensitive.\n\n"
        "```\n\n```\n\n"
        f"Exception: `{report.exception_type}`\n\n"
        f"{frame_block}"
        f"Surface: {report.environment.surface}\n"
        f"Endpoint / call: {report.call_type or 'unknown'}\n"
        f"Provider: {report.custom_llm_provider or 'unknown'}\n"
        f"LiteLLM: {report.environment.litellm_version}\n"
        f"Python: {report.environment.python_version}\n"
        f"{stream_line}"
        f"{config_block}"
    )


def _issue_url(report: BugReport, frames: tuple[str, ...], config_lines: tuple[str, ...]) -> str:
    deployment: Final[tuple[tuple[str, str], ...]] = (
        () if report.environment.deployment is None else (("deployment", report.environment.deployment),)
    )
    fields: Final = (
        ("template", "bug_report.yml"),
        ("labels", "bug"),
        ("title", _title(report, frames)),
        ("version", report.environment.litellm_version),
        ("domain", _domain(report)),
        ("description", _description(report, frames, config_lines)),
    ) + deployment
    return f"{ISSUE_URL_BASE}?{urlencode(fields)}"


def bug_report_issue_url(report: BugReport) -> str:
    frames: Final = report.litellm_frames
    config_lines: Final = report.environment.config_lines
    candidates: Final = (
        *((frames, config_lines[:count]) for count in range(len(config_lines), -1, -1)),
        *((frames[index:], ()) for index in range(1, len(frames) + 1)),
    )
    return next(
        (
            url
            for candidate_frames, candidate_config in candidates
            if len(url := _issue_url(report, candidate_frames, candidate_config)) <= MAX_URL_LENGTH
        ),
        _issue_url(report, (), ()),
    )


def strip_bug_report_notice(message: str) -> str:
    index: Final = message.find(NOTICE_PREFIX)
    if index == -1:
        return message
    head: Final = message[:index]
    return head.removesuffix("\n")


def bug_report_notice(report: BugReport) -> str:
    return (
        f"{NOTICE_PREFIX} File it with one click "
        f"(prefilled, no request data or error text, review before submitting): {bug_report_issue_url(report)}"
    )
