from concurrent.futures import ThreadPoolExecutor

from litellm.constants import MAX_SYNC_STREAM_PRODUCER_THREADS

sync_stream_producer_executor = ThreadPoolExecutor(max_workers=MAX_SYNC_STREAM_PRODUCER_THREADS)
