import subprocess
from pathlib import Path

import pytest


REPO_ROOT = Path(__file__).resolve().parents[2]
DASHBOARD_EXPORT_PATH = "litellm/proxy/_experimental/out"


def test_dashboard_static_export_is_not_tracked_in_git():
    result = subprocess.run(
        ["git", "ls-files", DASHBOARD_EXPORT_PATH],
        cwd=REPO_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        pytest.skip("git metadata is unavailable")

    tracked_files = [
        path
        for path in result.stdout.splitlines()
        if path.startswith(DASHBOARD_EXPORT_PATH)
    ]

    assert tracked_files == [], (
        "The dashboard static export is generated by the Docker build and should "
        "not be committed to git."
    )


def test_dockerfiles_build_dashboard_static_export_from_source():
    dockerfiles = [
        REPO_ROOT / "Dockerfile",
        REPO_ROOT / "docker" / "Dockerfile.non_root",
    ]

    for dockerfile in dockerfiles:
        contents = dockerfile.read_text(encoding="utf-8")

        assert "cd ui/litellm-dashboard" in contents
        assert "npm ci" in contents
        assert "npm run build" in contents
        assert "cp -R out/. ../../litellm/proxy/_experimental/out/" in contents
