import { MetricWithMetadata } from "../../types";

export const mockEndpointData: Record<string, MetricWithMetadata> = {
  "/chat/completions": {
    metrics: {
      spend: 1250.45,
      prompt_tokens: 150000,
      completion_tokens: 45000,
      cache_read_input_tokens: 0,
      cache_creation_input_tokens: 0,
      total_tokens: 195000,
      successful_requests: 1250,
      failed_requests: 45,
      api_requests: 1295,
    },
    metadata: {},
    api_key_breakdown: {},
  },
  "/audio/speech": {
    metrics: {
      spend: 320.78,
      prompt_tokens: 0,
      completion_tokens: 0,
      cache_read_input_tokens: 0,
      cache_creation_input_tokens: 0,
      total_tokens: 0,
      successful_requests: 890,
      failed_requests: 12,
      api_requests: 902,
    },
    metadata: {},
    api_key_breakdown: {},
  },
  "/audio/transcriptions": {
    metrics: {
      spend: 85.23,
      prompt_tokens: 0,
      completion_tokens: 0,
      cache_read_input_tokens: 0,
      cache_creation_input_tokens: 0,
      total_tokens: 0,
      successful_requests: 234,
      failed_requests: 8,
      api_requests: 242,
    },
    metadata: {},
    api_key_breakdown: {},
  },
  "/embeddings": {
    metrics: {
      spend: 450.12,
      prompt_tokens: 200000,
      completion_tokens: 0,
      cache_read_input_tokens: 0,
      cache_creation_input_tokens: 0,
      total_tokens: 200000,
      successful_requests: 2100,
      failed_requests: 23,
      api_requests: 2123,
    },
    metadata: {},
    api_key_breakdown: {},
  },
  "/images/generations": {
    metrics: {
      spend: 180.56,
      prompt_tokens: 0,
      completion_tokens: 0,
      cache_read_input_tokens: 0,
      cache_creation_input_tokens: 0,
      total_tokens: 0,
      successful_requests: 156,
      failed_requests: 5,
      api_requests: 161,
    },
    metadata: {},
    api_key_breakdown: {},
  },
  "/moderations": {
    metrics: {
      spend: 95.34,
      prompt_tokens: 50000,
      completion_tokens: 0,
      cache_read_input_tokens: 0,
      cache_creation_input_tokens: 0,
      total_tokens: 50000,
      successful_requests: 567,
      failed_requests: 3,
      api_requests: 570,
    },
    metadata: {},
    api_key_breakdown: {},
  },
};
