[mypy]
warn_return_any = True
ignore_missing_imports = True
disallow_untyped_defs = True
mypy_path = litellm/stubs
namespace_packages = True
disable_error_code =
    annotation-unchecked,
    import-untyped

[mypy-litellm.*]
ignore_missing_imports = False

[mypy-google.*]
ignore_missing_imports = True

[mypy-cryptography.hazmat.bindings._rust.x509]
ignore_errors = True

[mypy-fastuuid.*]
ignore_missing_imports = True
ignore_errors = True