import express from 'express';
import { Credentials, OAuth2Client } from 'google-auth-library';
import http from 'http';
import open from 'open';
import { loadCredentials } from './client.js';
import { describeErrorForLog } from './utils.js';
import { resolveOAuthScopes } from './scopes.js';
import { escapeHtml } from './html.js';

export type PromptMode =
  | 'consent'
  | 'select_account'
  | 'consent select_account';

export interface AuthServerOptions {
  /**
   * Receives the tokens from the OAuth callback. AuthServer never persists
   * tokens itself — the caller owns persistence into `AccountStore`
   * (buildAuthSystem's first-time bootstrap and `manage_accounts add`).
   * A throw here renders the failure page and leaves
   * `authCompletedSuccessfully` false.
   */
  onTokens: (tokens: Credentials) => Promise<void>;
  /**
   * Google OAuth `prompt` parameter. Defaults to `'consent'` for the
   * first-time server-boot flow; the add-a-new-account flow overrides this
   * with `'consent select_account'` to show an explicit picker and guarantee
   * a fresh refresh_token.
   */
  promptMode?: PromptMode;
  /**
   * Scopes to request. Defaults to the env-configured OAuth scopes. Extra
   * scopes (e.g. userinfo) can be appended here per flow without mutating
   * the process-wide default.
   */
  scopes?: readonly string[];
}

export class AuthServer {
  private baseOAuth2Client: OAuth2Client; // Fallback for consent-URL generation on the '/' route before start() creates the flow client
  private flowOAuth2Client: OAuth2Client | null = null; // Used specifically for the auth code flow
  private app: express.Express;
  private server: http.Server | null = null;
  private readonly onTokens: (tokens: Credentials) => Promise<void>;
  private readonly promptMode: PromptMode;
  private readonly scopes: readonly string[];
  public readonly portRange: { start: number; end: number };
  public authCompletedSuccessfully = false; // Flag for standalone script

  constructor(oauth2Client: OAuth2Client, opts: AuthServerOptions) {
    this.baseOAuth2Client = oauth2Client;
    this.onTokens = opts.onTokens;
    this.promptMode = opts.promptMode ?? 'consent';
    this.scopes = opts.scopes ?? resolveOAuthScopes();
    this.app = express();
    const raw = process.env.GOOGLE_DRIVE_MCP_AUTH_PORT;
    const portStart = raw ? Number(raw) : 3000;
    if (!Number.isInteger(portStart) || portStart < 1 || portStart > 65531) {
      throw new Error(
        `Invalid GOOGLE_DRIVE_MCP_AUTH_PORT: "${raw}". Must be an integer between 1 and 65531.`
      );
    }
    this.portRange = { start: portStart, end: portStart + 4 };
    this.setupRoutes();
  }

  /** Build the Google consent URL for a client using this server's scopes/prompt. */
  private buildConsentUrl(client: OAuth2Client): string {
    return client.generateAuthUrl({
      access_type: 'offline',
      scope: [...this.scopes],
      prompt: this.promptMode,
    });
  }

  private setupRoutes(): void {
    this.app.get('/', (req, res) => {
      // Generate the URL using the active flow client if available, else base
      const clientForUrl = this.flowOAuth2Client || this.baseOAuth2Client;
      const authUrl = this.buildConsentUrl(clientForUrl);
      // escapeHtml guards attribute breakout here, not the URL scheme; this
      // is safe only because authUrl is generated by google-auth-library
      // (always an https:// Google URL), never derived from user input.
      res.send(`<h1>Google Drive Authentication</h1><a href="${escapeHtml(authUrl)}">Authenticate with Google</a>`);
    });

    this.app.get('/oauth2callback', async (req, res) => {
      const code = req.query.code as string;
      if (!code) {
        res.status(400).send('Authorization code missing');
        return;
      }
      // IMPORTANT: Use the flowOAuth2Client to exchange the code
      if (!this.flowOAuth2Client) {
        res.status(500).send('Authentication flow not properly initiated.');
        return;
      }
      try {
        const { tokens } = await this.flowOAuth2Client.getToken(code);
        await this.onTokens(tokens);
        this.authCompletedSuccessfully = true;

        res.send(`
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Authentication Successful</title>
              <style>
                  body { font-family: sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; background-color: #f4f4f4; margin: 0; }
                  .container { text-align: center; padding: 2em; background-color: #fff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
                  h1 { color: #4CAF50; }
                  p { color: #333; margin-bottom: 0.5em; }
                  code { background-color: #eee; padding: 0.2em 0.4em; border-radius: 3px; font-size: 0.9em; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Authentication Successful!</h1>
                  <p>Your account has been connected and securely stored.</p>
                  <p>You can now close this browser window.</p>
              </div>
          </body>
          </html>
        `);
      } catch (error: unknown) {
        this.authCompletedSuccessfully = false;
        // Log the message only, not the raw error object: google-auth-library
        // token-exchange failures are GaxiosErrors whose `config`/`response`
        // carry the request body (authorization code + client_secret), which
        // must not land in logs.
        console.error(
          'OAuth callback failed:',
          error instanceof Error ? error.message : String(error)
        );
        // Send a generic HTML error response; the error detail goes to the
        // server log only, never reflected back to the browser.
        res.status(500).send(`
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Authentication Failed</title>
              <style>
                  body { font-family: sans-serif; display: flex; justify-content: center; align-items: center; height: 100vh; background-color: #f4f4f4; margin: 0; }
                  .container { text-align: center; padding: 2em; background-color: #fff; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
                  h1 { color: #F44336; }
                  p { color: #333; }
              </style>
          </head>
          <body>
              <div class="container">
                  <h1>Authentication Failed</h1>
                  <p>An error occurred during authentication.</p>
                  <p>Please try again, or check the server logs for details.</p>
              </div>
          </body>
          </html>
        `);
      }
    });
  }

  async start(openBrowser = true): Promise<boolean> {
    // Try to start the server and get the port
    const port = await this.startServerOnAvailablePort();
    if (port === null) {
      this.authCompletedSuccessfully = false;
      return false;
    }

    // Successfully started server on `port`. Now create the flow-specific OAuth client.
    try {
      const { client_id, client_secret } = await loadCredentials();
      this.flowOAuth2Client = new OAuth2Client(
        client_id,
        client_secret || undefined,
        `http://127.0.0.1:${port}/oauth2callback`
      );
    } catch (error) {
        // Could not load credentials, cannot proceed with auth flow.
        // describeErrorForLog: a JSON.parse SyntaxError echoes fragments of the
        // credentials file (client secret) into its message.
        console.error(`Failed to load credentials for auth flow: ${describeErrorForLog(error)}`);
        this.authCompletedSuccessfully = false;
        await this.stop(); // Stop the server we just started
        return false;
    }

    if (openBrowser) {
      // Generate Auth URL using the newly created flow client
      const authorizeUrl = this.buildConsentUrl(this.flowOAuth2Client);

      console.error('\n🔐 AUTHENTICATION REQUIRED');
      console.error('══════════════════════════════════════════');
      console.error('\nOpening your browser to authenticate...');
      console.error(`If the browser doesn't open, visit:\n${authorizeUrl}\n`);

      await open(authorizeUrl);
    }

    return true; // Auth flow initiated
  }

  /**
   * Build the auth URL the user needs to visit, without opening the browser.
   * Callers must have already invoked `start(false)` to reserve a port and
   * initialize the flow client.
   */
  public getAuthorizeUrl(): string | null {
    if (!this.flowOAuth2Client) return null;
    return this.buildConsentUrl(this.flowOAuth2Client);
  }

  private async startServerOnAvailablePort(): Promise<number | null> {
    for (let port = this.portRange.start; port <= this.portRange.end; port++) {
      try {
        await new Promise<void>((resolve, reject) => {
          // Create a temporary server instance to test the port.
          // Bind to the loopback interface explicitly: the OAuth redirect URI
          // is hard-coded to `http://127.0.0.1:<port>/oauth2callback`, so we
          // never need to accept connections from other interfaces, and doing
          // so would expose the short-lived auth server to the LAN. The IP is
          // used (not `localhost`) so the bind and the redirect URI resolve to
          // the same address on dual-stack hosts.
          const testServer = this.app.listen(port, '127.0.0.1', () => {
            this.server = testServer; // Assign to class property *only* if successful
            console.error(`Authentication server listening on http://127.0.0.1:${port}`);
            resolve();
          });
          testServer.on('error', (err: NodeJS.ErrnoException) => {
            if (err.code === 'EADDRINUSE') {
              // Port is in use, close the test server and reject
              testServer.close(() => reject(err));
            } else {
              // Other error, reject
              reject(err);
            }
          });
        });
        return port; // Port successfully bound
      } catch (error: unknown) {
        // Check if it's EADDRINUSE, otherwise rethrow or handle
        if (!(error instanceof Error && 'code' in error && (error as any).code === 'EADDRINUSE')) {
            // An unexpected error occurred during server start
            console.error('Failed to start auth server:', error);
            return null;
        }
        // EADDRINUSE occurred, loop continues
      }
    }
    console.error('No available ports for authentication server (tried ports', this.portRange.start, '-', this.portRange.end, ')');
    return null; // No port found
  }

  public getRunningPort(): number | null {
    if (this.server) {
      const address = this.server.address();
      if (typeof address === 'object' && address !== null) {
        return address.port;
      }
    }
    return null;
  }

  public getServerAddress(): string | null {
    if (this.server) {
      const address = this.server.address();
      if (typeof address === 'object' && address !== null) {
        return address.address;
      }
    }
    return null;
  }

  async stop(): Promise<void> {
    return new Promise((resolve, reject) => {
      if (this.server) {
        this.server.close((err) => {
          if (err) {
            reject(err);
          } else {
            this.server = null;
            resolve();
          }
        });
      } else {
        resolve();
      }
    });
  }
}
