"""
Type definitions for Google Interactions API

Auto-generated from OpenAPI spec: https://ai.google.dev/static/api/interactions.openapi.json
See README.md for regeneration instructions.
"""

from litellm.types.interactions.generated import (
    AgentOption,
    Annotation,
    AudioContent,
    CancelInteractionResult,
    CodeExecution,
    CodeExecutionCallContent,
    CodeExecutionResultContent,
    ComputerUse,
    Content,
    ContentDelta,
    ContentStart,
    ContentStop,
    CreateAgentInteractionParams,
    CreateModelInteractionParams,
    DeepResearchAgentConfig,
    DeleteInteractionResult,
    DocumentContent,
    DynamicAgentConfig,
    ErrorEvent,
    FileSearch,
    FileSearchResultContent,
    Function,
    FunctionCallContent,
    FunctionResultContent,
    GenerationConfig,
    GoogleSearch,
    GoogleSearchCallContent,
    GoogleSearchResultContent,
    ImageContent,
    Interaction,
    InteractionCompleted,
    InteractionCreated,
    InteractionEnvironment,
    InteractionEvent,
    InteractionInProgress,
    InteractionInput,
    InteractionRequiresAction,
    InteractionsAPIOptionalRequestParams,
    InteractionsAPIResponse,
    InteractionsAPIStreamingResponse,
    InteractionSseEvent,
    InteractionTool,
    InteractionToolChoiceConfig,
    McpServer,
    McpServerToolCallContent,
    McpServerToolResultContent,
    ModelOption,
    ResponseModality,
    StepDelta,
    StepStart,
    StepStop,
    TextContent,
    ThoughtContent,
    Tool,
    ToolChoiceConfig,
    Turn,
    UrlContext,
    UrlContextCallContent,
    UrlContextResultContent,
    Usage,
    VideoContent,
)
from litellm.types.interactions.generated import (
    Status3 as InteractionStatus,  # Main request/response types; Content types; Turn for multi-turn conversations; Tool types; Config types; Usage; Status enum; Events for streaming; Agent configs; Model/Agent options; Response modality; Annotation; LiteLLM types; Backwards compat aliases
)

__all__ = [
    "AgentOption",
    "Annotation",
    "AudioContent",
    "CancelInteractionResult",
    "CodeExecution",
    "CodeExecutionCallContent",
    "CodeExecutionResultContent",
    "ComputerUse",
    "Content",
    "ContentDelta",
    "ContentStart",
    "ContentStop",
    "CreateAgentInteractionParams",
    # Generated types
    "CreateModelInteractionParams",
    "DeepResearchAgentConfig",
    "DeleteInteractionResult",
    "DocumentContent",
    "DynamicAgentConfig",
    "ErrorEvent",
    "FileSearch",
    "FileSearchResultContent",
    "Function",
    "FunctionCallContent",
    "FunctionResultContent",
    "GenerationConfig",
    "GoogleSearch",
    "GoogleSearchCallContent",
    "GoogleSearchResultContent",
    "ImageContent",
    "Interaction",
    "InteractionCompleted",
    "InteractionCreated",
    # LiteLLM types
    "InteractionEnvironment",
    "InteractionEvent",
    "InteractionInProgress",
    "InteractionInput",
    "InteractionRequiresAction",
    "InteractionSseEvent",
    "InteractionStatus",
    # Backwards compat
    "InteractionTool",
    "InteractionToolChoiceConfig",
    "InteractionsAPIOptionalRequestParams",
    "InteractionsAPIResponse",
    "InteractionsAPIStreamingResponse",
    "McpServer",
    "McpServerToolCallContent",
    "McpServerToolResultContent",
    "ModelOption",
    "ResponseModality",
    "StepDelta",
    # New schema SSE event types (Api-Revision: 2026-05-20)
    "StepStart",
    "StepStop",
    "TextContent",
    "ThoughtContent",
    "Tool",
    "ToolChoiceConfig",
    "Turn",
    "UrlContext",
    "UrlContextCallContent",
    "UrlContextResultContent",
    "Usage",
    "VideoContent",
]
