#!/usr/bin/env python3
"""Coverage gate for PR2 (PrismaClient + spend) of the proxy/utils.py
behavior-pinning project.

Reads ``.cov_new.xml`` from the working directory (generated by the prior
pytest run with ``--cov=litellm.proxy.utils --cov-branch
--cov-report=xml:.cov_new.xml``). Filters covered lines to the PR2 range
on ``litellm/proxy/utils.py`` and prints PASS / FAIL only; no numbers.

The PR target floors below are intentionally generous; pin-list completion
is the behavior gate. This script is a local-only stopping signal to catch
the case where an engineer fills the pin list but the coverage tooling
shows the tests never executed the targeted region.

Exits 0 on PASS, non-zero on FAIL.
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Iterable, Set, Tuple

HERE = Path(__file__).resolve().parent
_REPO_ROOT = HERE.parent.parent.parent.parent.parent

_TARGET_FILE_SUFFIX = "proxy/utils.py"
_PR2_LINE_START = 2669
_PR2_LINE_END = 5542
_MIN_LINE_RATE = 0.55
_MIN_BRANCH_RATE = 0.40


def _iter_line_hits(
    xml_path: Path, line_start: int, line_end: int
) -> Tuple[int, int, int, int]:
    """Return (lines_total, lines_hit, branches_total, branches_hit) within the
    PR2 range on the target file.
    """
    if not xml_path.is_file():
        raise FileNotFoundError(f"Coverage XML not found at {xml_path}")
    tree = ET.parse(xml_path)
    root = tree.getroot()

    lines_total = lines_hit = 0
    branches_total = branches_hit = 0
    found = False
    for class_elem in root.iter("class"):
        filename = class_elem.get("filename", "")
        if not filename.endswith(_TARGET_FILE_SUFFIX):
            continue
        found = True
        for line_elem in class_elem.iter("line"):
            try:
                lineno = int(line_elem.get("number", "0"))
            except ValueError:
                continue
            if lineno < line_start or lineno > line_end:
                continue
            lines_total += 1
            hits = int(line_elem.get("hits", "0"))
            if hits > 0:
                lines_hit += 1
            cond = line_elem.get("condition-coverage")
            if cond:
                inside = cond[cond.find("(") + 1 : cond.find(")")]
                if "/" in inside:
                    a, b = inside.split("/", 1)
                    try:
                        branches_hit += int(a)
                        branches_total += int(b)
                    except ValueError:
                        pass
    if not found:
        raise RuntimeError(
            f"Target file ending in {_TARGET_FILE_SUFFIX!r} not present in {xml_path}"
        )
    return lines_total, lines_hit, branches_total, branches_hit


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--coverage-xml",
        default=None,
        help="Path to coverage XML (default: ./.cov_new.xml then repo-root)",
    )
    args = parser.parse_args()

    candidates: Iterable[Path]
    if args.coverage_xml:
        candidates = (Path(args.coverage_xml),)
    else:
        candidates = (
            Path(".cov_new.xml"),
            _REPO_ROOT / ".cov_new.xml",
        )

    xml_path: Path | None = None
    for c in candidates:
        if c.is_file():
            xml_path = c
            break
    if xml_path is None:
        print("FAIL", file=sys.stderr)
        return 2

    try:
        lines_total, lines_hit, branches_total, branches_hit = _iter_line_hits(
            xml_path, _PR2_LINE_START, _PR2_LINE_END
        )
    except (FileNotFoundError, RuntimeError):
        print("FAIL", file=sys.stderr)
        return 2

    if lines_total == 0:
        print("FAIL", file=sys.stderr)
        return 1

    line_rate = lines_hit / lines_total
    branch_rate = (branches_hit / branches_total) if branches_total > 0 else 1.0

    ok = line_rate >= _MIN_LINE_RATE and branch_rate >= _MIN_BRANCH_RATE
    print("PASS" if ok else "FAIL")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
