model_list:
  - model_name: "gpt-4"
    litellm_params:
      model: openai/fake
      api_key: fake-key
      api_base: http://host.docker.internal:8090/

general_settings:    
    alerting: ["slack"]