use std::collections::HashSet;
use std::env;
use std::fs;
use std::path::PathBuf;

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct ProviderMetadataInput {
    routing_name: String,
    display_name: String,
    default_api_base: Option<String>,
    api_key_env_var: Option<String>,
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

fn rust_option(value: Option<&str>) -> String {
    value
        .map(|value| format!("Some({})", rust_string(value)))
        .unwrap_or_else(|| "None".to_string())
}

fn variant_name(routing_name: &str) -> String {
    routing_name
        .split(['_', '-', '.'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => {
                    let mut out = String::new();
                    out.extend(first.to_uppercase());
                    out.push_str(chars.as_str());
                    out
                }
                None => String::new(),
            }
        })
        .collect()
}

fn validate_providers(providers: &[ProviderMetadataInput]) {
    let mut routing_names = HashSet::new();
    let mut variants = HashSet::new();

    for provider in providers {
        if provider.routing_name.trim().is_empty() {
            panic!("provider routing_name cannot be empty");
        }
        if provider.display_name.trim().is_empty() {
            panic!(
                "provider {} has an empty display_name",
                provider.routing_name
            );
        }
        if !routing_names.insert(provider.routing_name.as_str()) {
            panic!("duplicate provider routing_name: {}", provider.routing_name);
        }

        let variant = variant_name(&provider.routing_name);
        if variant.is_empty() {
            panic!(
                "provider {} generated an empty Rust variant",
                provider.routing_name
            );
        }
        if !variants.insert(variant.clone()) {
            panic!(
                "provider {} generated duplicate Rust variant {variant}",
                provider.routing_name
            );
        }
    }
}

fn generate_provider_code(providers: &[ProviderMetadataInput]) -> String {
    let variants: Vec<String> = providers
        .iter()
        .map(|provider| variant_name(&provider.routing_name))
        .collect();

    let enum_variants = variants
        .iter()
        .map(|variant| format!("    {variant},"))
        .collect::<Vec<_>>()
        .join("\n");

    let all_values = variants
        .iter()
        .map(|variant| format!("        LlmProvider::{variant},"))
        .collect::<Vec<_>>()
        .join("\n");

    let metadata_values = providers
        .iter()
        .zip(variants.iter())
        .map(|(provider, variant)| {
            format!(
                "        ProviderMetadata {{ provider: LlmProvider::{variant}, routing_name: {}, display_name: {}, default_api_base: {}, api_key_env_var: {} }},",
                rust_string(&provider.routing_name),
                rust_string(&provider.display_name),
                rust_option(provider.default_api_base.as_deref()),
                rust_option(provider.api_key_env_var.as_deref()),
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let metadata_match_arms = variants
        .iter()
        .enumerate()
        .map(|(index, variant)| {
            format!("            LlmProvider::{variant} => &Self::METADATA[{index}],")
        })
        .collect::<Vec<_>>()
        .join("\n");

    format!(
        r#"// @generated by crates/core/build.rs from litellm-rust/crates/core/src/providers/provider_registry.json.
// Do not edit this file by hand.

use std::fmt;
use std::str::FromStr;

use crate::error::CoreError;

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ProviderMetadata {{
    pub provider: LlmProvider,
    pub routing_name: &'static str,
    pub display_name: &'static str,
    pub default_api_base: Option<&'static str>,
    pub api_key_env_var: Option<&'static str>,
}}

#[allow(clippy::enum_variant_names)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LlmProvider {{
{enum_variants}
}}

impl LlmProvider {{
    pub const ALL: [LlmProvider; {provider_count}] = [
{all_values}
    ];

    pub const METADATA: [ProviderMetadata; {provider_count}] = [
{metadata_values}
    ];

    pub fn metadata(self) -> &'static ProviderMetadata {{
        match self {{
{metadata_match_arms}
        }}
    }}

    pub fn as_str(self) -> &'static str {{
        self.metadata().routing_name
    }}

    pub fn display_name(self) -> &'static str {{
        self.metadata().display_name
    }}

    pub fn default_api_base(self) -> Option<&'static str> {{
        self.metadata().default_api_base
    }}

    pub fn api_key_env_var(self) -> Option<&'static str> {{
        self.metadata().api_key_env_var
    }}
}}

impl fmt::Display for LlmProvider {{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{
        f.write_str(self.as_str())
    }}
}}

impl FromStr for LlmProvider {{
    type Err = CoreError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {{
        LlmProvider::ALL
            .iter()
            .copied()
            .find(|provider| provider.as_str() == value)
            .ok_or_else(|| CoreError::InvalidProvider(value.to_string()))
    }}
}}

#[cfg(test)]
mod tests {{
    use super::*;

    #[derive(serde::Deserialize)]
    struct RegistryProvider {{
        routing_name: String,
    }}

    fn registry_provider_values() -> Vec<String> {{
        let raw = include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/src/providers/provider_registry.json"
        ));
        serde_json::from_str::<Vec<RegistryProvider>>(raw)
            .expect("provider_registry.json parses")
            .into_iter()
            .map(|provider| provider.routing_name)
            .collect()
    }}

    fn python_provider_values() -> Vec<String> {{
        let source = include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../../litellm/types/utils.py"
        ));
        let mut values = Vec::new();
        let mut in_llm_providers = false;

        for line in source.lines() {{
            if line.starts_with("class LlmProviders(") {{
                in_llm_providers = true;
                continue;
            }}
            if in_llm_providers && line.starts_with("class ") {{
                break;
            }}
            if !in_llm_providers {{
                continue;
            }}

            let trimmed = line.trim();
            let Some((name, value_expr)) = trimmed.split_once('=') else {{
                continue;
            }};
            if !name
                .trim()
                .chars()
                .all(|ch| ch.is_ascii_uppercase() || ch.is_ascii_digit() || ch == '_')
            {{
                continue;
            }}
            let Some(value) = value_expr.split('"').nth(1) else {{
                continue;
            }};
            values.push(value.to_string());
        }}

        assert!(!values.is_empty(), "parsed Python LlmProviders values");
        values
    }}

    #[test]
    fn provider_values_match_registry_order() {{
        let registry_values = registry_provider_values();
        assert_eq!(LlmProvider::ALL.len(), registry_values.len());
        assert_eq!(
            LlmProvider::ALL
                .iter()
                .map(|provider| provider.as_str().to_string())
                .collect::<Vec<_>>(),
            registry_values
        );
    }}

    #[test]
    fn provider_registry_matches_python_llm_providers() {{
        assert_eq!(registry_provider_values(), python_provider_values());
    }}

    #[test]
    fn from_str_round_trips_all_providers() {{
        for provider in LlmProvider::ALL {{
            assert_eq!(LlmProvider::from_str(provider.as_str()), Ok(provider));
            assert_eq!(provider.to_string(), provider.as_str());
        }}
    }}

    #[test]
    fn from_str_rejects_unknown_provider() {{
        assert_eq!(
            LlmProvider::from_str("not-a-provider"),
            Err(CoreError::InvalidProvider("not-a-provider".to_string()))
        );
    }}

    #[test]
    fn provider_metadata_exposes_optional_defaults() {{
        assert_eq!(LlmProvider::Mistral.display_name(), "Mistral");
        assert_eq!(
            LlmProvider::Mistral.default_api_base(),
            Some("https://api.mistral.ai/v1")
        );
        assert_eq!(LlmProvider::Mistral.api_key_env_var(), Some("MISTRAL_API_KEY"));
    }}
}}
"#,
        enum_variants = enum_variants,
        provider_count = providers.len(),
        all_values = all_values,
        metadata_values = metadata_values,
        metadata_match_arms = metadata_match_arms,
    )
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let providers_path = manifest_dir.join("src/providers/provider_registry.json");
    println!("cargo:rerun-if-changed={}", providers_path.display());
    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir.join("build.rs").display()
    );

    let raw = fs::read_to_string(&providers_path).unwrap_or_else(|err| {
        panic!(
            "failed to read provider registry {}: {err}",
            providers_path.display()
        )
    });
    let providers: Vec<ProviderMetadataInput> = serde_json::from_str(&raw)
        .unwrap_or_else(|err| panic!("failed to parse {}: {err}", providers_path.display()));
    validate_providers(&providers);

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    fs::write(
        out_dir.join("provider_generated.rs"),
        generate_provider_code(&providers),
    )
    .expect("failed to write generated provider code");
}
