CREATE VIEW IF NOT EXISTS {database}.traces
SQL SECURITY INVOKER
AS SELECT
    team_id,
    api_key_hash,
    trace_id,
    any(trace_ref) AS id,
    if(uniqExact(user_id) = 1, any(user_id), '') AS user_id,
    if(countIf(parent_span_id = '') > 0,
       argMinIf(s.name, tuple(s.start_time, span_id), parent_span_id = ''),
       argMin(s.name, tuple(s.start_time, span_id))) AS name,
    argMin(s.service, tuple(s.start_time, span_id)) AS service,
    coalesce(nullIf(if(countIf(parent_span_id = '') > 0,
       argMinIf(s.input_preview, tuple(s.start_time, span_id), parent_span_id = ''),
       argMin(s.input_preview, tuple(s.start_time, span_id))), ''),
       argMinIf(s.input_preview, tuple(s.start_time, span_id),
                s.input_preview != '' AND observation_type IN ('agent', 'llm'))) AS input_preview,
    if(countIf(parent_span_id = '') > 0,
       argMinIf(status, tuple(s.start_time, span_id), parent_span_id = ''),
       argMin(status, tuple(s.start_time, span_id))) AS root_status,
    min(s.start_time) AS start_time,
    max(s.start_time + toIntervalNanosecond(s.duration_ns)) AS end_time,
    toUInt64(greatest(toUnixTimestamp64Nano(end_time) - toUnixTimestamp64Nano(start_time), 0)) AS duration_ns,
    duration_ns / 1000000.0 AS duration_ms,
    count() AS span_count,
    countIf(status = 'error') AS error_count,
    CAST(error_count > 0, 'Bool') AS has_error,
    countIf(observation_type = 'agent') AS agent_span_count,
    arraySort(groupUniqArrayIf(if(agent_name = '', s.name, agent_name), agent_name != '' OR observation_type = 'agent')) AS agent_names,
    length(agent_names) AS agent_label_count,
    arraySort(groupUniqArrayIf(framework, framework != '')) AS frameworks,
    countIf(observation_type = 'llm') AS llm_span_count,
    countIf(observation_type = 'tool') AS tool_span_count,
    sum(s.input_tokens) AS span_input_tokens,
    sum(s.output_tokens) AS span_output_tokens,
    arraySort(groupUniqArrayIf(model, model != '')) AS models
FROM {database}.spans AS s
GROUP BY team_id, api_key_hash, trace_id
