CREATE VIEW IF NOT EXISTS {database}.calls
SQL SECURITY INVOKER
AS SELECT
    team_id,
    api_key AS api_key_hash,
    user AS user_id,
    request_id,
    response_id,
    litellm_call_id,
    trace_id,
    span_id,
    call_type,
    model,
    model_group,
    custom_llm_provider AS provider,
    spend,
    prompt_tokens AS input_tokens,
    completion_tokens AS output_tokens,
    total_tokens,
    cache_read_tokens,
    cache_write_tokens,
    start_time,
    end_time,
    completion_start_time,
    dateDiff('millisecond', start_time, end_time) AS duration_ms,
    status,
    error_str AS error,
    cache_hit,
    session_id,
    request_tags,
    metadata,
    messages,
    response,
    EngineReceivedMs AS ingested_at_ms
FROM {database}.spend_logs FINAL
