version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.3.0

workflows:
  setup:
    jobs:
      - path-filtering/filter:
          base-revision: main
          config-path: .circleci/continue_config.yml
          mapping: |
            .*\.py$ run-code-tests true
            .*\.ts$ run-code-tests true
            .*\.tsx$ run-code-tests true
