[package]
name = "litellm-db"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
postgres-tests = []
schema = ["dep:schemars"]

[dependencies]
schemars = { workspace = true, optional = true, features = ["chrono04"] }
sqlx.workspace = true

[dev-dependencies]
litellm-db-testing.workspace = true
rstest.workspace = true
tokio.workspace = true
