model_list:
  - model_name: gpt-5
    litellm_params:
      model: openai/gpt-5

guardrails:
  - guardrail_name: "mock-guard"
    litellm_params:
      guardrail: generic_guardrail_api
      mode: pre_call
      api_base: "http://127.0.0.1:8888"
      default_on: true
