[package]
name = "litellm-llms-types"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
schema = ["dep:schemars", "schemars/indexmap2"]

[dependencies]
indexmap = { version = "2.14.0", features = ["serde"] }
macro_rules_attribute.workspace = true
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
strum.workspace = true
thiserror.workspace = true

[dev-dependencies]
rstest.workspace = true
