from types import MappingProxyType
from typing import Final

TODO: Final = MappingProxyType(
    {
        "test_transport_parity[azure-cohere-connection-refused-async]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[azure-cohere-connection-refused-sync]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[azure-cohere-missing-fields-sync]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[azure-cohere-not-json-async]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[azure-cohere-not-json-sync]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[azure-cohere-oversized-async]": "4.2: Python has no response size limit",
        "test_transport_parity[azure-cohere-oversized-sync]": "4.2: Python has no response size limit",
        "test_transport_parity[azure-cohere-read-timeout-async]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[azure-cohere-read-timeout-sync]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[azure-document-intelligence-connection-refused-async]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[azure-document-intelligence-connection-refused-sync]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[azure-document-intelligence-missing-fields-async]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[azure-document-intelligence-missing-fields-sync]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[azure-document-intelligence-not-json-async]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[azure-document-intelligence-not-json-sync]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[azure-document-intelligence-oversized-async]": "4.2: Python has no response size limit",
        "test_transport_parity[azure-document-intelligence-oversized-sync]": "4.2: Python has no response size limit",
        "test_transport_parity[azure-document-intelligence-read-timeout-async]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[azure-document-intelligence-read-timeout-sync]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[azure-mistral-connection-refused-async]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[azure-mistral-connection-refused-sync]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[azure-mistral-missing-fields-async]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[azure-mistral-missing-fields-sync]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[azure-mistral-not-json-async]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[azure-mistral-not-json-sync]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[azure-mistral-oversized-async]": "4.2: Python has no response size limit",
        "test_transport_parity[azure-mistral-oversized-sync]": "4.2: Python has no response size limit",
        "test_transport_parity[azure-mistral-read-timeout-async]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[azure-mistral-read-timeout-sync]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[cohere-connection-refused-async]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[cohere-connection-refused-sync]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[cohere-missing-fields-sync]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[cohere-not-json-async]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[cohere-not-json-sync]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[cohere-oversized-async]": "4.2: Python has no response size limit",
        "test_transport_parity[cohere-oversized-sync]": "4.2: Python has no response size limit",
        "test_transport_parity[cohere-read-timeout-async]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[cohere-read-timeout-sync]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[mistral-connection-refused-async]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[mistral-connection-refused-sync]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[mistral-missing-fields-async]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[mistral-missing-fields-sync]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[mistral-not-json-async]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[mistral-not-json-sync]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[mistral-oversized-async]": "4.2: Python has no response size limit",
        "test_transport_parity[mistral-oversized-sync]": "4.2: Python has no response size limit",
        "test_transport_parity[mistral-read-timeout-async]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[mistral-read-timeout-sync]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[reducto-legacy-connection-refused-async]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[reducto-legacy-connection-refused-sync]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[reducto-legacy-missing-fields-sync]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[reducto-legacy-not-json-async]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[reducto-legacy-not-json-sync]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[reducto-legacy-oversized-async]": "4.2: Python has no response size limit",
        "test_transport_parity[reducto-legacy-oversized-sync]": "4.2: Python has no response size limit",
        "test_transport_parity[reducto-legacy-read-timeout-async]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[reducto-legacy-read-timeout-sync]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[reducto-v3-connection-refused-async]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[reducto-v3-connection-refused-sync]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[reducto-v3-missing-fields-sync]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[reducto-v3-not-json-async]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[reducto-v3-not-json-sync]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[reducto-v3-oversized-async]": "4.2: Python has no response size limit",
        "test_transport_parity[reducto-v3-oversized-sync]": "4.2: Python has no response size limit",
        "test_transport_parity[reducto-v3-read-timeout-async]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[reducto-v3-read-timeout-sync]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[vertex-deepseek-connection-refused-async]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[vertex-deepseek-connection-refused-sync]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[vertex-deepseek-missing-fields-async]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[vertex-deepseek-missing-fields-sync]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[vertex-deepseek-not-json-async]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[vertex-deepseek-not-json-sync]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[vertex-deepseek-oversized-async]": "4.2: Python has no response size limit",
        "test_transport_parity[vertex-deepseek-oversized-sync]": "4.2: Python has no response size limit",
        "test_transport_parity[vertex-deepseek-read-timeout-async]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[vertex-deepseek-read-timeout-sync]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[vertex-mistral-connection-refused-async]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[vertex-mistral-connection-refused-sync]": "4.2: Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[vertex-mistral-missing-fields-async]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[vertex-mistral-missing-fields-sync]": "4.2: responses missing fields do not map like the Python transformation",
        "test_transport_parity[vertex-mistral-not-json-async]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[vertex-mistral-not-json-sync]": "4.2: unparseable responses carry the Rust parser's message",
        "test_transport_parity[vertex-mistral-oversized-async]": "4.2: Python has no response size limit",
        "test_transport_parity[vertex-mistral-oversized-sync]": "4.2: Python has no response size limit",
        "test_transport_parity[vertex-mistral-read-timeout-async]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[vertex-mistral-read-timeout-sync]": "4.2: timeouts carry a Rust message instead of the Python handler's",
        "test_validation_parity[azure-cohere-pdf-async]": "4.4: Cohere image-only text differs",
        "test_validation_parity[azure-cohere-pdf-sync]": "4.4: Cohere image-only text differs",
        "test_validation_parity[bad-req-format-azure-cohere-async]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-azure-cohere-sync]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-azure-document-intelligence-async]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-azure-document-intelligence-sync]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-azure-mistral-async]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-azure-mistral-sync]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-cohere-async]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-cohere-sync]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-mistral-async]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-mistral-sync]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-reducto-legacy-async]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-reducto-legacy-sync]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-reducto-v3-async]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-reducto-v3-sync]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-vertex-deepseek-async]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-vertex-deepseek-sync]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-vertex-mistral-async]": "4.4: req_format text differs",
        "test_validation_parity[bad-req-format-vertex-mistral-sync]": "4.4: req_format text differs",
        "test_validation_parity[cohere-pdf-async]": "4.4: Cohere image-only text differs",
        "test_validation_parity[cohere-pdf-sync]": "4.4: Cohere image-only text differs",
        "test_validation_parity[empty-file-azure-cohere-async]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-azure-cohere-sync]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-azure-document-intelligence-async]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-azure-document-intelligence-sync]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-azure-mistral-async]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-azure-mistral-sync]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-cohere-async]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-cohere-sync]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-mistral-async]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-mistral-sync]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-reducto-legacy-async]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-reducto-legacy-sync]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-reducto-v3-async]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-reducto-v3-sync]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-vertex-deepseek-async]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-vertex-deepseek-sync]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-vertex-mistral-async]": "4.4: local ValueError classification",
        "test_validation_parity[empty-file-vertex-mistral-sync]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-data-uri-azure-cohere-async]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-azure-cohere-sync]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-azure-document-intelligence-async]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-azure-document-intelligence-sync]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-azure-mistral-async]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-azure-mistral-sync]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-cohere-async]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-cohere-sync]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-mistral-sync]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-reducto-legacy-async]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-reducto-legacy-sync]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-reducto-v3-async]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-reducto-v3-sync]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-vertex-deepseek-async]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-vertex-deepseek-sync]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-vertex-mistral-async]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-vertex-mistral-sync]": "4.4: Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-mime-type-azure-cohere-async]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-azure-cohere-sync]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-azure-document-intelligence-async]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-azure-document-intelligence-sync]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-azure-mistral-async]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-azure-mistral-sync]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-cohere-async]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-cohere-sync]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-mistral-async]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-mistral-sync]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-reducto-legacy-async]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-reducto-legacy-sync]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-reducto-v3-async]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-reducto-v3-sync]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-vertex-deepseek-async]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-vertex-deepseek-sync]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-vertex-mistral-async]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-mime-type-vertex-mistral-sync]": "4.4: local ValueError classification",
        "test_validation_parity[invalid-pages-async]": "4.4: pages validation text differs",
        "test_validation_parity[invalid-pages-sync]": "4.4: pages validation text differs",
        "test_validation_parity[invalid-provider-async]": "4.4: invalid provider text differs",
        "test_validation_parity[invalid-provider-sync]": "4.4: invalid provider text differs",
        "test_validation_parity[missing-azure-ai-credentials-async]": "4.4: credential text differs",
        "test_validation_parity[missing-azure-ai-credentials-sync]": "4.4: credential text differs",
        "test_validation_parity[missing-document-intelligence-credentials-async]": "4.4: credential text differs",
        "test_validation_parity[missing-document-intelligence-credentials-sync]": "4.4: credential text differs",
        "test_validation_parity[missing-document-url-azure-cohere-async]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-azure-cohere-sync]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-azure-document-intelligence-async]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-azure-document-intelligence-sync]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-azure-mistral-async]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-azure-mistral-sync]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-cohere-async]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-cohere-sync]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-mistral-async]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-mistral-sync]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-reducto-legacy-async]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-reducto-legacy-sync]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-reducto-v3-async]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-reducto-v3-sync]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-vertex-deepseek-async]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-vertex-deepseek-sync]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-vertex-mistral-async]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-vertex-mistral-sync]": "4.4: Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-file-cohere-async]": "4.4: local FileNotFoundError classification",
        "test_validation_parity[missing-file-cohere-sync]": "4.4: local FileNotFoundError classification",
        "test_validation_parity[missing-file-reducto-legacy-async]": "4.4: local FileNotFoundError classification",
        "test_validation_parity[missing-file-reducto-legacy-sync]": "4.4: local FileNotFoundError classification",
        "test_validation_parity[missing-file-reducto-v3-async]": "4.4: local FileNotFoundError classification",
        "test_validation_parity[missing-file-reducto-v3-sync]": "4.4: local FileNotFoundError classification",
        "test_validation_parity[missing-file-vertex-deepseek-async]": "4.4: local FileNotFoundError classification",
        "test_validation_parity[missing-file-vertex-deepseek-sync]": "4.4: local FileNotFoundError classification",
        "test_validation_parity[missing-file-vertex-mistral-async]": "4.4: local FileNotFoundError classification",
        "test_validation_parity[missing-file-vertex-mistral-sync]": "4.4: local FileNotFoundError classification",
        "test_validation_parity[missing-reducto-key-async]": "4.4: credential error classification",
        "test_validation_parity[missing-reducto-key-sync]": "4.4: credential error classification",
        "test_validation_parity[reducto-legacy-plain-url-async]": "4.4: Reducto source text differs",
        "test_validation_parity[reducto-legacy-plain-url-sync]": "4.4: Reducto source text differs",
        "test_validation_parity[reducto-plain-url-async]": "4.4: Reducto source text differs",
        "test_validation_parity[reducto-plain-url-sync]": "4.4: Reducto source text differs",
        "test_validation_parity[unreadable-file-azure-cohere-async]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-azure-cohere-sync]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-azure-document-intelligence-async]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-azure-document-intelligence-sync]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-azure-mistral-async]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-azure-mistral-sync]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-cohere-async]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-cohere-sync]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-mistral-async]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-mistral-sync]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-reducto-legacy-async]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-reducto-legacy-sync]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-reducto-v3-async]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-reducto-v3-sync]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-vertex-deepseek-async]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-vertex-deepseek-sync]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-vertex-mistral-async]": "4.4: local OSError classification",
        "test_validation_parity[unreadable-file-vertex-mistral-sync]": "4.4: local OSError classification",
        "test_router_and_proxy_parity[missing-document-url]": "4.4: Python rejects an empty document URL before provider resolution",
    }
)
