from types import MappingProxyType
from typing import Final

UPSTREAM_FAILURE: Final = (
    "Rust error text carries a (status, body) tuple instead of the upstream body; async rows also lose "
    "num_retries and timeout; some bodies map to a different exception class than Python's exception_type"
)

FUNCTION_TODO: Final = MappingProxyType(
    {
        "test_upstream_status_parity": UPSTREAM_FAILURE,
        "test_upstream_body_parity": UPSTREAM_FAILURE,
        "test_call_option_parity": UPSTREAM_FAILURE,
    }
)

TODO: Final = MappingProxyType(
    {
        "test_document_intelligence_failed_operation_parity": "Rust drops the Document Intelligence failure message; aocr failures lose num_retries and timeout",
        "test_document_intelligence_settings_parity[api-version]": "Rust ignores AZURE_DOCUMENT_INTELLIGENCE_API_VERSION",
        "test_document_intelligence_settings_parity[dpi]": "Rust ignores AZURE_DOCUMENT_INTELLIGENCE_DEFAULT_DPI",
        "test_ocr_contract_post_call_event_carries_the_api_key_and_only_the_request_body[rust-async]": "the post_call event carries request headers Python does not pass",
        "test_ocr_contract_post_call_event_carries_the_api_key_and_only_the_request_body[rust-sync]": "the post_call event carries request headers Python does not pass",
        "test_remote_document_fetch_parity[allowlisted-host]": "Rust ignores litellm.user_url_allowed_hosts",
        "test_request_parity[extra-body-mistral-async]": "Rust merges extra_body into the provider request, Python ignores it for OCR",
        "test_request_parity[extra-body-mistral-sync]": "Rust merges extra_body into the provider request, Python ignores it for OCR",
        "test_request_parity[sampling-params-vertex-deepseek-async]": "Rust forwards sampling params to Vertex DeepSeek, Python drops them",
        "test_request_parity[sampling-params-vertex-deepseek-sync]": "Rust forwards sampling params to Vertex DeepSeek, Python drops them",
        "test_request_user_agent_parity": "Rust sends no litellm User-Agent",
        "test_router_and_proxy_parity[deployment-retries]": "Router ignores the deployment num_retries because aocr failures lose it",
        "test_router_and_proxy_parity[missing-document-url]": "Python rejects an empty document URL before provider resolution; proxy errors lose x-litellm-timeout because aocr failures lose timeout",
        "test_router_and_proxy_parity[not-found]": "proxy errors lose x-litellm-timeout because aocr failures lose timeout",
        "test_router_and_proxy_parity[not-json]": "proxy errors lose x-litellm-timeout because aocr failures lose timeout",
        "test_router_and_proxy_parity[provider-failure]": "proxy errors lose x-litellm-timeout because aocr failures lose timeout",
        "test_router_and_proxy_parity[rate-limited]": "proxy errors lose x-litellm-timeout because aocr failures lose timeout",
        "test_router_and_proxy_parity[read-timeout]": "proxy errors lose x-litellm-timeout because aocr failures lose timeout",
        "test_router_and_proxy_parity[unauthorized]": "proxy errors lose x-litellm-timeout because aocr failures lose timeout",
        "test_transport_parity[azure-cohere-connection-refused-async]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[azure-cohere-connection-refused-sync]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[azure-cohere-not-json-async]": "unparseable responses carry the Rust parser's message; aocr failures lose num_retries and timeout",
        "test_transport_parity[azure-cohere-not-json-sync]": "unparseable responses carry the Rust parser's message",
        "test_transport_parity[azure-cohere-oversized-async]": "Python has no response size limit",
        "test_transport_parity[azure-cohere-oversized-sync]": "Python has no response size limit",
        "test_transport_parity[azure-cohere-read-timeout-async]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[azure-cohere-read-timeout-sync]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[azure-document-intelligence-connection-refused-async]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[azure-document-intelligence-connection-refused-sync]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[azure-document-intelligence-missing-fields-async]": "responses missing fields do not map like the Python transformation; aocr failures lose num_retries and timeout",
        "test_transport_parity[azure-document-intelligence-missing-fields-sync]": "responses missing fields do not map like the Python transformation",
        "test_transport_parity[azure-document-intelligence-not-json-async]": "unparseable responses carry the Rust parser's message; aocr failures lose num_retries and timeout",
        "test_transport_parity[azure-document-intelligence-not-json-sync]": "unparseable responses carry the Rust parser's message",
        "test_transport_parity[azure-document-intelligence-oversized-async]": "Python has no response size limit; aocr failures lose num_retries and timeout",
        "test_transport_parity[azure-document-intelligence-oversized-sync]": "Python has no response size limit",
        "test_transport_parity[azure-document-intelligence-read-timeout-async]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[azure-document-intelligence-read-timeout-sync]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[azure-mistral-connection-refused-async]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[azure-mistral-connection-refused-sync]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[azure-mistral-missing-fields-async]": "responses missing fields do not map like the Python transformation",
        "test_transport_parity[azure-mistral-missing-fields-sync]": "responses missing fields do not map like the Python transformation",
        "test_transport_parity[azure-mistral-not-json-async]": "unparseable responses carry the Rust parser's message; aocr failures lose num_retries and timeout",
        "test_transport_parity[azure-mistral-not-json-sync]": "unparseable responses carry the Rust parser's message",
        "test_transport_parity[azure-mistral-oversized-async]": "Python has no response size limit",
        "test_transport_parity[azure-mistral-oversized-sync]": "Python has no response size limit",
        "test_transport_parity[azure-mistral-read-timeout-async]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[azure-mistral-read-timeout-sync]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[cohere-connection-refused-async]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[cohere-connection-refused-sync]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[cohere-not-json-async]": "unparseable responses carry the Rust parser's message; aocr failures lose num_retries and timeout",
        "test_transport_parity[cohere-not-json-sync]": "unparseable responses carry the Rust parser's message",
        "test_transport_parity[cohere-oversized-async]": "Python has no response size limit",
        "test_transport_parity[cohere-oversized-sync]": "Python has no response size limit",
        "test_transport_parity[cohere-read-timeout-async]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[cohere-read-timeout-sync]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[mistral-connection-refused-async]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[mistral-connection-refused-sync]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[mistral-missing-fields-async]": "responses missing fields do not map like the Python transformation",
        "test_transport_parity[mistral-missing-fields-sync]": "responses missing fields do not map like the Python transformation",
        "test_transport_parity[mistral-not-json-async]": "unparseable responses carry the Rust parser's message; aocr failures lose num_retries and timeout",
        "test_transport_parity[mistral-not-json-sync]": "unparseable responses carry the Rust parser's message",
        "test_transport_parity[mistral-oversized-async]": "Python has no response size limit",
        "test_transport_parity[mistral-oversized-sync]": "Python has no response size limit",
        "test_transport_parity[mistral-read-timeout-async]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[mistral-read-timeout-sync]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[reducto-legacy-connection-refused-async]": "Python reports a refused connection as a 500 from the provider; aocr failures lose num_retries and timeout",
        "test_transport_parity[reducto-legacy-connection-refused-sync]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[reducto-legacy-not-json-async]": "unparseable responses carry the Rust parser's message; aocr failures lose num_retries and timeout",
        "test_transport_parity[reducto-legacy-not-json-sync]": "unparseable responses carry the Rust parser's message",
        "test_transport_parity[reducto-legacy-oversized-async]": "Python has no response size limit",
        "test_transport_parity[reducto-legacy-oversized-sync]": "Python has no response size limit",
        "test_transport_parity[reducto-legacy-read-timeout-async]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[reducto-legacy-read-timeout-sync]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[reducto-v3-connection-refused-async]": "Python reports a refused connection as a 500 from the provider; aocr failures lose num_retries and timeout",
        "test_transport_parity[reducto-v3-connection-refused-sync]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[reducto-v3-not-json-async]": "unparseable responses carry the Rust parser's message; aocr failures lose num_retries and timeout",
        "test_transport_parity[reducto-v3-not-json-sync]": "unparseable responses carry the Rust parser's message",
        "test_transport_parity[reducto-v3-oversized-async]": "Python has no response size limit",
        "test_transport_parity[reducto-v3-oversized-sync]": "Python has no response size limit",
        "test_transport_parity[reducto-v3-read-timeout-async]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[reducto-v3-read-timeout-sync]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[vertex-deepseek-connection-refused-async]": "Python reports a refused connection as a 500 from the provider; aocr failures lose num_retries and timeout",
        "test_transport_parity[vertex-deepseek-connection-refused-sync]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[vertex-deepseek-missing-fields-async]": "responses missing fields do not map like the Python transformation; aocr failures lose num_retries and timeout",
        "test_transport_parity[vertex-deepseek-missing-fields-sync]": "responses missing fields do not map like the Python transformation",
        "test_transport_parity[vertex-deepseek-not-json-async]": "unparseable responses carry the Rust parser's message; aocr failures lose num_retries and timeout",
        "test_transport_parity[vertex-deepseek-not-json-sync]": "unparseable responses carry the Rust parser's message",
        "test_transport_parity[vertex-deepseek-oversized-async]": "Python has no response size limit; aocr failures lose num_retries and timeout",
        "test_transport_parity[vertex-deepseek-oversized-sync]": "Python has no response size limit",
        "test_transport_parity[vertex-deepseek-read-timeout-async]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[vertex-deepseek-read-timeout-sync]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[vertex-mistral-connection-refused-async]": "Python reports a refused connection as a 500 from the provider; aocr failures lose num_retries and timeout",
        "test_transport_parity[vertex-mistral-connection-refused-sync]": "Python reports a refused connection as a 500 from the provider",
        "test_transport_parity[vertex-mistral-missing-fields-async]": "responses missing fields do not map like the Python transformation",
        "test_transport_parity[vertex-mistral-missing-fields-sync]": "responses missing fields do not map like the Python transformation",
        "test_transport_parity[vertex-mistral-not-json-async]": "unparseable responses carry the Rust parser's message; aocr failures lose num_retries and timeout",
        "test_transport_parity[vertex-mistral-not-json-sync]": "unparseable responses carry the Rust parser's message",
        "test_transport_parity[vertex-mistral-oversized-async]": "Python has no response size limit",
        "test_transport_parity[vertex-mistral-oversized-sync]": "Python has no response size limit",
        "test_transport_parity[vertex-mistral-read-timeout-async]": "timeouts carry a Rust message instead of the Python handler's",
        "test_transport_parity[vertex-mistral-read-timeout-sync]": "timeouts carry a Rust message instead of the Python handler's",
        "test_validation_parity[azure-cohere-pdf-async]": "Cohere image-only text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[azure-cohere-pdf-sync]": "Cohere image-only text differs",
        "test_validation_parity[bad-req-format-azure-cohere-async]": "req_format text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[bad-req-format-azure-cohere-sync]": "req_format text differs",
        "test_validation_parity[bad-req-format-azure-document-intelligence-async]": "req_format text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[bad-req-format-azure-document-intelligence-sync]": "req_format text differs",
        "test_validation_parity[bad-req-format-azure-mistral-async]": "req_format text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[bad-req-format-azure-mistral-sync]": "req_format text differs",
        "test_validation_parity[bad-req-format-cohere-async]": "req_format text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[bad-req-format-cohere-sync]": "req_format text differs",
        "test_validation_parity[bad-req-format-mistral-async]": "req_format text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[bad-req-format-mistral-sync]": "req_format text differs",
        "test_validation_parity[bad-req-format-reducto-legacy-async]": "req_format text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[bad-req-format-reducto-legacy-sync]": "req_format text differs",
        "test_validation_parity[bad-req-format-reducto-v3-async]": "req_format text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[bad-req-format-reducto-v3-sync]": "req_format text differs",
        "test_validation_parity[bad-req-format-vertex-deepseek-async]": "req_format text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[bad-req-format-vertex-deepseek-sync]": "req_format text differs",
        "test_validation_parity[bad-req-format-vertex-mistral-async]": "req_format text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[bad-req-format-vertex-mistral-sync]": "req_format text differs",
        "test_validation_parity[cohere-pdf-async]": "Cohere image-only text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[cohere-pdf-sync]": "Cohere image-only text differs",
        "test_validation_parity[empty-file-azure-cohere-async]": "local ValueError classification",
        "test_validation_parity[empty-file-azure-cohere-sync]": "local ValueError classification",
        "test_validation_parity[empty-file-azure-document-intelligence-async]": "local ValueError classification",
        "test_validation_parity[empty-file-azure-document-intelligence-sync]": "local ValueError classification",
        "test_validation_parity[empty-file-azure-mistral-async]": "local ValueError classification",
        "test_validation_parity[empty-file-azure-mistral-sync]": "local ValueError classification",
        "test_validation_parity[empty-file-cohere-async]": "local ValueError classification",
        "test_validation_parity[empty-file-cohere-sync]": "local ValueError classification",
        "test_validation_parity[empty-file-mistral-async]": "local ValueError classification",
        "test_validation_parity[empty-file-mistral-sync]": "local ValueError classification",
        "test_validation_parity[empty-file-reducto-legacy-async]": "local ValueError classification",
        "test_validation_parity[empty-file-reducto-legacy-sync]": "local ValueError classification",
        "test_validation_parity[empty-file-reducto-v3-async]": "local ValueError classification",
        "test_validation_parity[empty-file-reducto-v3-sync]": "local ValueError classification",
        "test_validation_parity[empty-file-vertex-deepseek-async]": "local ValueError classification",
        "test_validation_parity[empty-file-vertex-deepseek-sync]": "local ValueError classification",
        "test_validation_parity[empty-file-vertex-mistral-async]": "local ValueError classification",
        "test_validation_parity[empty-file-vertex-mistral-sync]": "local ValueError classification",
        "test_validation_parity[invalid-data-uri-azure-cohere-async]": "Rust rejects data URIs Python forwards; aocr failures lose num_retries and timeout",
        "test_validation_parity[invalid-data-uri-azure-cohere-sync]": "Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-azure-document-intelligence-async]": "Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-azure-document-intelligence-sync]": "Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-azure-mistral-async]": "Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-azure-mistral-sync]": "Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-cohere-async]": "Rust rejects data URIs Python forwards; aocr failures lose num_retries and timeout",
        "test_validation_parity[invalid-data-uri-cohere-sync]": "Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-reducto-legacy-async]": "Rust rejects data URIs Python forwards; aocr failures lose num_retries and timeout",
        "test_validation_parity[invalid-data-uri-reducto-legacy-sync]": "Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-reducto-v3-async]": "Rust rejects data URIs Python forwards; aocr failures lose num_retries and timeout",
        "test_validation_parity[invalid-data-uri-reducto-v3-sync]": "Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-vertex-deepseek-async]": "Rust rejects data URIs Python forwards; aocr failures lose num_retries and timeout",
        "test_validation_parity[invalid-data-uri-vertex-deepseek-sync]": "Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-vertex-mistral-async]": "Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-data-uri-vertex-mistral-sync]": "Rust rejects data URIs Python forwards",
        "test_validation_parity[invalid-mime-type-azure-cohere-async]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-azure-cohere-sync]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-azure-document-intelligence-async]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-azure-document-intelligence-sync]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-azure-mistral-async]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-azure-mistral-sync]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-cohere-async]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-cohere-sync]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-mistral-async]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-mistral-sync]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-reducto-legacy-async]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-reducto-legacy-sync]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-reducto-v3-async]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-reducto-v3-sync]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-vertex-deepseek-async]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-vertex-deepseek-sync]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-vertex-mistral-async]": "local ValueError classification",
        "test_validation_parity[invalid-mime-type-vertex-mistral-sync]": "local ValueError classification",
        "test_validation_parity[invalid-pages-async]": "pages validation text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[invalid-pages-sync]": "pages validation text differs",
        "test_validation_parity[invalid-provider-async]": "invalid provider text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[invalid-provider-sync]": "invalid provider text differs",
        "test_validation_parity[missing-azure-ai-credentials-async]": "credential text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-azure-ai-credentials-sync]": "credential text differs",
        "test_validation_parity[missing-document-intelligence-credentials-async]": "credential text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-document-intelligence-credentials-sync]": "credential text differs",
        "test_validation_parity[missing-document-url-azure-cohere-async]": "Python rejects an empty document URL before provider resolution; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-document-url-azure-cohere-sync]": "Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-azure-document-intelligence-async]": "Python rejects an empty document URL before provider resolution; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-document-url-azure-document-intelligence-sync]": "Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-azure-mistral-async]": "Python rejects an empty document URL before provider resolution; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-document-url-azure-mistral-sync]": "Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-cohere-async]": "Python rejects an empty document URL before provider resolution; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-document-url-cohere-sync]": "Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-mistral-async]": "Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-mistral-sync]": "Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-reducto-legacy-async]": "Python rejects an empty document URL before provider resolution; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-document-url-reducto-legacy-sync]": "Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-reducto-v3-async]": "Python rejects an empty document URL before provider resolution; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-document-url-reducto-v3-sync]": "Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-vertex-deepseek-async]": "Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-vertex-deepseek-sync]": "Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-vertex-mistral-async]": "Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-document-url-vertex-mistral-sync]": "Python rejects an empty document URL before provider resolution",
        "test_validation_parity[missing-file-azure-cohere-async]": "aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-file-azure-document-intelligence-async]": "aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-file-azure-mistral-async]": "aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-file-cohere-async]": "local FileNotFoundError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-file-cohere-sync]": "local FileNotFoundError classification",
        "test_validation_parity[missing-file-mistral-async]": "aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-file-reducto-legacy-async]": "local FileNotFoundError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-file-reducto-legacy-sync]": "local FileNotFoundError classification",
        "test_validation_parity[missing-file-reducto-v3-async]": "local FileNotFoundError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-file-reducto-v3-sync]": "local FileNotFoundError classification",
        "test_validation_parity[missing-file-vertex-deepseek-async]": "local FileNotFoundError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-file-vertex-deepseek-sync]": "local FileNotFoundError classification",
        "test_validation_parity[missing-file-vertex-mistral-async]": "local FileNotFoundError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-file-vertex-mistral-sync]": "local FileNotFoundError classification",
        "test_validation_parity[missing-reducto-key-async]": "credential error classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[missing-reducto-key-sync]": "credential error classification",
        "test_validation_parity[model-of-a-provider-without-ocr-async]": "Rust sends a model it cannot resolve to Mistral instead of rejecting it",
        "test_validation_parity[model-of-a-provider-without-ocr-sync]": "Rust sends a model it cannot resolve to Mistral instead of rejecting it",
        "test_validation_parity[model-without-provider-prefix-async]": "Rust sends a model it cannot resolve to Mistral instead of rejecting it",
        "test_validation_parity[model-without-provider-prefix-sync]": "Rust sends a model it cannot resolve to Mistral instead of rejecting it",
        "test_validation_parity[raising-file-reader-async]": "aocr failures lose num_retries and timeout",
        "test_validation_parity[raising-token-provider-async]": "aocr failures lose num_retries and timeout",
        "test_validation_parity[reducto-legacy-plain-url-async]": "Reducto source text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[reducto-legacy-plain-url-sync]": "Reducto source text differs",
        "test_validation_parity[reducto-plain-url-async]": "Reducto source text differs; aocr failures lose num_retries and timeout",
        "test_validation_parity[reducto-plain-url-sync]": "Reducto source text differs",
        "test_validation_parity[unreadable-file-azure-cohere-async]": "local OSError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[unreadable-file-azure-cohere-sync]": "local OSError classification",
        "test_validation_parity[unreadable-file-azure-document-intelligence-async]": "local OSError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[unreadable-file-azure-document-intelligence-sync]": "local OSError classification",
        "test_validation_parity[unreadable-file-azure-mistral-async]": "local OSError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[unreadable-file-azure-mistral-sync]": "local OSError classification",
        "test_validation_parity[unreadable-file-cohere-async]": "local OSError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[unreadable-file-cohere-sync]": "local OSError classification",
        "test_validation_parity[unreadable-file-mistral-async]": "local OSError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[unreadable-file-mistral-sync]": "local OSError classification",
        "test_validation_parity[unreadable-file-reducto-legacy-async]": "local OSError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[unreadable-file-reducto-legacy-sync]": "local OSError classification",
        "test_validation_parity[unreadable-file-reducto-v3-async]": "local OSError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[unreadable-file-reducto-v3-sync]": "local OSError classification",
        "test_validation_parity[unreadable-file-vertex-deepseek-async]": "local OSError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[unreadable-file-vertex-deepseek-sync]": "local OSError classification",
        "test_validation_parity[unreadable-file-vertex-mistral-async]": "local OSError classification; aocr failures lose num_retries and timeout",
        "test_validation_parity[unreadable-file-vertex-mistral-sync]": "local OSError classification",
        "test_validation_parity[vertex-api-key-env-without-google-credentials-async]": "Rust authenticates Vertex with VERTEX_AI_API_KEY where Python requires Google credentials",
        "test_validation_parity[vertex-api-key-env-without-google-credentials-sync]": "Rust authenticates Vertex with VERTEX_AI_API_KEY where Python requires Google credentials",
    }
)
