//! Mirrors Python's CallTypes (litellm/types/utils.py), generated from its variant list.

// variant names mirror Python's enum members verbatim
#![allow(non_camel_case_types)]

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum CallTypes {
    embedding,
    aembedding,
    completion,
    acompletion,
    atext_completion,
    text_completion,
    image_generation,
    aimage_generation,
    image_edit,
    aimage_edit,
    moderation,
    amoderation,
    atranscription,
    transcription,
    aspeech,
    speech,
    rerank,
    arerank,
    search,
    asearch,
    arealtime,
    aresponses_websocket,
    create_batch,
    acreate_batch,
    aretrieve_batch,
    retrieve_batch,
    acancel_batch,
    cancel_batch,
    pass_through,
    anthropic_messages,
    aanthropic_messages,
    get_assistants,
    aget_assistants,
    create_assistants,
    acreate_assistants,
    delete_assistant,
    adelete_assistant,
    acreate_thread,
    create_thread,
    aget_thread,
    get_thread,
    a_add_message,
    add_message,
    aget_messages,
    get_messages,
    arun_thread,
    run_thread,
    arun_thread_stream,
    run_thread_stream,
    afile_retrieve,
    file_retrieve,
    afile_delete,
    file_delete,
    afile_list,
    file_list,
    acreate_file,
    create_file,
    afile_content,
    file_content,
    create_fine_tuning_job,
    acreate_fine_tuning_job,
    create_video,
    acreate_video,
    video_generation,
    avideo_generation,
    avideo_retrieve,
    video_retrieve,
    avideo_content,
    video_content,
    video_remix,
    avideo_remix,
    video_list,
    avideo_list,
    video_retrieve_job,
    avideo_retrieve_job,
    video_delete,
    avideo_delete,
    video_create_character,
    avideo_create_character,
    video_get_character,
    avideo_get_character,
    video_edit,
    avideo_edit,
    video_extension,
    avideo_extension,
    vector_store_file_create,
    avector_store_file_create,
    vector_store_file_list,
    avector_store_file_list,
    vector_store_file_retrieve,
    avector_store_file_retrieve,
    vector_store_file_content,
    avector_store_file_content,
    vector_store_file_update,
    avector_store_file_update,
    vector_store_file_delete,
    avector_store_file_delete,
    vector_store_create,
    avector_store_create,
    vector_store_search,
    avector_store_search,
    ingest,
    aingest,
    query,
    aquery,
    create_interaction,
    acreate_interaction,
    create_container,
    acreate_container,
    list_containers,
    alist_containers,
    retrieve_container,
    aretrieve_container,
    delete_container,
    adelete_container,
    list_container_files,
    alist_container_files,
    upload_container_file,
    aupload_container_file,
    create_sandbox,
    acreate_sandbox,
    delete_sandbox,
    adelete_sandbox,
    run_code,
    arun_code,
    code_interpreter_tool,
    acode_interpreter_tool,
    acancel_fine_tuning_job,
    cancel_fine_tuning_job,
    alist_fine_tuning_jobs,
    list_fine_tuning_jobs,
    aretrieve_fine_tuning_job,
    retrieve_fine_tuning_job,
    responses,
    aresponses,
    alist_input_items,
    llm_passthrough_route,
    allm_passthrough_route,
    generate_content,
    agenerate_content,
    generate_content_stream,
    agenerate_content_stream,
    ocr,
    aocr,
    call_mcp_tool,
    list_mcp_tools,
    asend_message,
    send_message,
    acreate_skill,
}

impl CallTypes {
    pub const VALUES: [Self; 149] = [
        Self::embedding,
        Self::aembedding,
        Self::completion,
        Self::acompletion,
        Self::atext_completion,
        Self::text_completion,
        Self::image_generation,
        Self::aimage_generation,
        Self::image_edit,
        Self::aimage_edit,
        Self::moderation,
        Self::amoderation,
        Self::atranscription,
        Self::transcription,
        Self::aspeech,
        Self::speech,
        Self::rerank,
        Self::arerank,
        Self::search,
        Self::asearch,
        Self::arealtime,
        Self::aresponses_websocket,
        Self::create_batch,
        Self::acreate_batch,
        Self::aretrieve_batch,
        Self::retrieve_batch,
        Self::acancel_batch,
        Self::cancel_batch,
        Self::pass_through,
        Self::anthropic_messages,
        Self::aanthropic_messages,
        Self::get_assistants,
        Self::aget_assistants,
        Self::create_assistants,
        Self::acreate_assistants,
        Self::delete_assistant,
        Self::adelete_assistant,
        Self::acreate_thread,
        Self::create_thread,
        Self::aget_thread,
        Self::get_thread,
        Self::a_add_message,
        Self::add_message,
        Self::aget_messages,
        Self::get_messages,
        Self::arun_thread,
        Self::run_thread,
        Self::arun_thread_stream,
        Self::run_thread_stream,
        Self::afile_retrieve,
        Self::file_retrieve,
        Self::afile_delete,
        Self::file_delete,
        Self::afile_list,
        Self::file_list,
        Self::acreate_file,
        Self::create_file,
        Self::afile_content,
        Self::file_content,
        Self::create_fine_tuning_job,
        Self::acreate_fine_tuning_job,
        Self::create_video,
        Self::acreate_video,
        Self::video_generation,
        Self::avideo_generation,
        Self::avideo_retrieve,
        Self::video_retrieve,
        Self::avideo_content,
        Self::video_content,
        Self::video_remix,
        Self::avideo_remix,
        Self::video_list,
        Self::avideo_list,
        Self::video_retrieve_job,
        Self::avideo_retrieve_job,
        Self::video_delete,
        Self::avideo_delete,
        Self::video_create_character,
        Self::avideo_create_character,
        Self::video_get_character,
        Self::avideo_get_character,
        Self::video_edit,
        Self::avideo_edit,
        Self::video_extension,
        Self::avideo_extension,
        Self::vector_store_file_create,
        Self::avector_store_file_create,
        Self::vector_store_file_list,
        Self::avector_store_file_list,
        Self::vector_store_file_retrieve,
        Self::avector_store_file_retrieve,
        Self::vector_store_file_content,
        Self::avector_store_file_content,
        Self::vector_store_file_update,
        Self::avector_store_file_update,
        Self::vector_store_file_delete,
        Self::avector_store_file_delete,
        Self::vector_store_create,
        Self::avector_store_create,
        Self::vector_store_search,
        Self::avector_store_search,
        Self::ingest,
        Self::aingest,
        Self::query,
        Self::aquery,
        Self::create_interaction,
        Self::acreate_interaction,
        Self::create_container,
        Self::acreate_container,
        Self::list_containers,
        Self::alist_containers,
        Self::retrieve_container,
        Self::aretrieve_container,
        Self::delete_container,
        Self::adelete_container,
        Self::list_container_files,
        Self::alist_container_files,
        Self::upload_container_file,
        Self::aupload_container_file,
        Self::create_sandbox,
        Self::acreate_sandbox,
        Self::delete_sandbox,
        Self::adelete_sandbox,
        Self::run_code,
        Self::arun_code,
        Self::code_interpreter_tool,
        Self::acode_interpreter_tool,
        Self::acancel_fine_tuning_job,
        Self::cancel_fine_tuning_job,
        Self::alist_fine_tuning_jobs,
        Self::list_fine_tuning_jobs,
        Self::aretrieve_fine_tuning_job,
        Self::retrieve_fine_tuning_job,
        Self::responses,
        Self::aresponses,
        Self::alist_input_items,
        Self::llm_passthrough_route,
        Self::allm_passthrough_route,
        Self::generate_content,
        Self::agenerate_content,
        Self::generate_content_stream,
        Self::agenerate_content_stream,
        Self::ocr,
        Self::aocr,
        Self::call_mcp_tool,
        Self::list_mcp_tools,
        Self::asend_message,
        Self::send_message,
        Self::acreate_skill,
    ];

    const NAMES: [(Self, &'static str); 149] = [
        (Self::embedding, "embedding"),
        (Self::aembedding, "aembedding"),
        (Self::completion, "completion"),
        (Self::acompletion, "acompletion"),
        (Self::atext_completion, "atext_completion"),
        (Self::text_completion, "text_completion"),
        (Self::image_generation, "image_generation"),
        (Self::aimage_generation, "aimage_generation"),
        (Self::image_edit, "image_edit"),
        (Self::aimage_edit, "aimage_edit"),
        (Self::moderation, "moderation"),
        (Self::amoderation, "amoderation"),
        (Self::atranscription, "atranscription"),
        (Self::transcription, "transcription"),
        (Self::aspeech, "aspeech"),
        (Self::speech, "speech"),
        (Self::rerank, "rerank"),
        (Self::arerank, "arerank"),
        (Self::search, "search"),
        (Self::asearch, "asearch"),
        (Self::arealtime, "_arealtime"),
        (Self::aresponses_websocket, "_aresponses_websocket"),
        (Self::create_batch, "create_batch"),
        (Self::acreate_batch, "acreate_batch"),
        (Self::aretrieve_batch, "aretrieve_batch"),
        (Self::retrieve_batch, "retrieve_batch"),
        (Self::acancel_batch, "acancel_batch"),
        (Self::cancel_batch, "cancel_batch"),
        (Self::pass_through, "pass_through_endpoint"),
        (Self::anthropic_messages, "anthropic_messages"),
        (Self::aanthropic_messages, "aanthropic_messages"),
        (Self::get_assistants, "get_assistants"),
        (Self::aget_assistants, "aget_assistants"),
        (Self::create_assistants, "create_assistants"),
        (Self::acreate_assistants, "acreate_assistants"),
        (Self::delete_assistant, "delete_assistant"),
        (Self::adelete_assistant, "adelete_assistant"),
        (Self::acreate_thread, "acreate_thread"),
        (Self::create_thread, "create_thread"),
        (Self::aget_thread, "aget_thread"),
        (Self::get_thread, "get_thread"),
        (Self::a_add_message, "a_add_message"),
        (Self::add_message, "add_message"),
        (Self::aget_messages, "aget_messages"),
        (Self::get_messages, "get_messages"),
        (Self::arun_thread, "arun_thread"),
        (Self::run_thread, "run_thread"),
        (Self::arun_thread_stream, "arun_thread_stream"),
        (Self::run_thread_stream, "run_thread_stream"),
        (Self::afile_retrieve, "afile_retrieve"),
        (Self::file_retrieve, "file_retrieve"),
        (Self::afile_delete, "afile_delete"),
        (Self::file_delete, "file_delete"),
        (Self::afile_list, "afile_list"),
        (Self::file_list, "file_list"),
        (Self::acreate_file, "acreate_file"),
        (Self::create_file, "create_file"),
        (Self::afile_content, "afile_content"),
        (Self::file_content, "file_content"),
        (Self::create_fine_tuning_job, "create_fine_tuning_job"),
        (Self::acreate_fine_tuning_job, "acreate_fine_tuning_job"),
        (Self::create_video, "create_video"),
        (Self::acreate_video, "acreate_video"),
        (Self::video_generation, "video_generation"),
        (Self::avideo_generation, "avideo_generation"),
        (Self::avideo_retrieve, "avideo_retrieve"),
        (Self::video_retrieve, "video_retrieve"),
        (Self::avideo_content, "avideo_content"),
        (Self::video_content, "video_content"),
        (Self::video_remix, "video_remix"),
        (Self::avideo_remix, "avideo_remix"),
        (Self::video_list, "video_list"),
        (Self::avideo_list, "avideo_list"),
        (Self::video_retrieve_job, "video_retrieve_job"),
        (Self::avideo_retrieve_job, "avideo_retrieve_job"),
        (Self::video_delete, "video_delete"),
        (Self::avideo_delete, "avideo_delete"),
        (Self::video_create_character, "video_create_character"),
        (Self::avideo_create_character, "avideo_create_character"),
        (Self::video_get_character, "video_get_character"),
        (Self::avideo_get_character, "avideo_get_character"),
        (Self::video_edit, "video_edit"),
        (Self::avideo_edit, "avideo_edit"),
        (Self::video_extension, "video_extension"),
        (Self::avideo_extension, "avideo_extension"),
        (Self::vector_store_file_create, "vector_store_file_create"),
        (Self::avector_store_file_create, "avector_store_file_create"),
        (Self::vector_store_file_list, "vector_store_file_list"),
        (Self::avector_store_file_list, "avector_store_file_list"),
        (
            Self::vector_store_file_retrieve,
            "vector_store_file_retrieve",
        ),
        (
            Self::avector_store_file_retrieve,
            "avector_store_file_retrieve",
        ),
        (Self::vector_store_file_content, "vector_store_file_content"),
        (
            Self::avector_store_file_content,
            "avector_store_file_content",
        ),
        (Self::vector_store_file_update, "vector_store_file_update"),
        (Self::avector_store_file_update, "avector_store_file_update"),
        (Self::vector_store_file_delete, "vector_store_file_delete"),
        (Self::avector_store_file_delete, "avector_store_file_delete"),
        (Self::vector_store_create, "vector_store_create"),
        (Self::avector_store_create, "avector_store_create"),
        (Self::vector_store_search, "vector_store_search"),
        (Self::avector_store_search, "avector_store_search"),
        (Self::ingest, "ingest"),
        (Self::aingest, "aingest"),
        (Self::query, "query"),
        (Self::aquery, "aquery"),
        (Self::create_interaction, "create_interaction"),
        (Self::acreate_interaction, "acreate_interaction"),
        (Self::create_container, "create_container"),
        (Self::acreate_container, "acreate_container"),
        (Self::list_containers, "list_containers"),
        (Self::alist_containers, "alist_containers"),
        (Self::retrieve_container, "retrieve_container"),
        (Self::aretrieve_container, "aretrieve_container"),
        (Self::delete_container, "delete_container"),
        (Self::adelete_container, "adelete_container"),
        (Self::list_container_files, "list_container_files"),
        (Self::alist_container_files, "alist_container_files"),
        (Self::upload_container_file, "upload_container_file"),
        (Self::aupload_container_file, "aupload_container_file"),
        (Self::create_sandbox, "create_sandbox"),
        (Self::acreate_sandbox, "acreate_sandbox"),
        (Self::delete_sandbox, "delete_sandbox"),
        (Self::adelete_sandbox, "adelete_sandbox"),
        (Self::run_code, "run_code"),
        (Self::arun_code, "arun_code"),
        (Self::code_interpreter_tool, "code_interpreter_tool"),
        (Self::acode_interpreter_tool, "acode_interpreter_tool"),
        (Self::acancel_fine_tuning_job, "acancel_fine_tuning_job"),
        (Self::cancel_fine_tuning_job, "cancel_fine_tuning_job"),
        (Self::alist_fine_tuning_jobs, "alist_fine_tuning_jobs"),
        (Self::list_fine_tuning_jobs, "list_fine_tuning_jobs"),
        (Self::aretrieve_fine_tuning_job, "aretrieve_fine_tuning_job"),
        (Self::retrieve_fine_tuning_job, "retrieve_fine_tuning_job"),
        (Self::responses, "responses"),
        (Self::aresponses, "aresponses"),
        (Self::alist_input_items, "alist_input_items"),
        (Self::llm_passthrough_route, "llm_passthrough_route"),
        (Self::allm_passthrough_route, "allm_passthrough_route"),
        (Self::generate_content, "generate_content"),
        (Self::agenerate_content, "agenerate_content"),
        (Self::generate_content_stream, "generate_content_stream"),
        (Self::agenerate_content_stream, "agenerate_content_stream"),
        (Self::ocr, "ocr"),
        (Self::aocr, "aocr"),
        (Self::call_mcp_tool, "call_mcp_tool"),
        (Self::list_mcp_tools, "list_mcp_tools"),
        (Self::asend_message, "asend_message"),
        (Self::send_message, "send_message"),
        (Self::acreate_skill, "acreate_skill"),
    ];

    pub fn as_str(self) -> &'static str {
        Self::NAMES
            .iter()
            .find(|(variant, _)| *variant == self)
            .map(|(_, name)| *name)
            .expect("every variant carries its name")
    }

    pub fn parse(name: &str) -> Option<Self> {
        Self::NAMES
            .iter()
            .find(|(_, known)| *known == name)
            .map(|(variant, _)| *variant)
    }
}

impl std::fmt::Display for CallTypes {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}
