//! Mirrors Python's LlmProviders (litellm/types/utils.py), generated from its variant list.

// variant names mirror Python's enum members verbatim
#![allow(non_camel_case_types)]

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum LlmProviders {
    OPENAI,
    CHATGPT,
    OPENAI_LIKE,
    JINA_AI,
    XAI,
    ZAI,
    CUSTOM_OPENAI,
    TEXT_COMPLETION_OPENAI,
    COHERE,
    COHERE_CHAT,
    CLARIFAI,
    ANTHROPIC,
    ANTHROPIC_TEXT,
    BYTEZ,
    REPLICATE,
    REDUCTO,
    AWS_TEXTRACT,
    RUNWAYML,
    AWS_POLLY,
    TRANSCRIBE,
    HUGGINGFACE,
    TOGETHER_AI,
    OPENROUTER,
    DATAROBOT,
    VERTEX_AI,
    VERTEX_AI_BETA,
    GEMINI,
    AI21,
    BASETEN,
    BLACK_FOREST_LABS,
    AZURE,
    AZURE_TEXT,
    AZURE_AI,
    SAGEMAKER,
    SAGEMAKER_CHAT,
    SAGEMAKER_NOVA,
    BEDROCK,
    VLLM,
    NLP_CLOUD,
    PETALS,
    OOBABOOGA,
    OLLAMA,
    OLLAMA_CHAT,
    DEEPINFRA,
    PERPLEXITY,
    MISTRAL,
    MILVUS,
    GROQ,
    A2A,
    GIGACHAT,
    NVIDIA_NIM,
    NVIDIA_RIVA,
    SONIOX,
    CEREBRAS,
    AI21_CHAT,
    VOLCENGINE,
    CODESTRAL,
    TEXT_COMPLETION_CODESTRAL,
    DASHSCOPE,
    QWENCLOUD,
    QWEN_AI_PLATFORM,
    MODELSCOPE,
    MOONSHOT,
    PUBLICAI,
    V0,
    MORPH,
    LAMBDA_AI,
    INCEPTION,
    TEXT_COMPLETION_INCEPTION,
    DEEPSEEK,
    SAMBANOVA,
    MARITALK,
    VOYAGE,
    CLOUDFLARE,
    XINFERENCE,
    FIREWORKS_AI,
    FRIENDLIAI,
    FEATHERLESS_AI,
    WATSONX,
    WATSONX_TEXT,
    TRITON,
    PREDIBASE,
    DATABRICKS,
    EMPOWER,
    GITHUB,
    RAGFLOW,
    COMPACTIFAI,
    DOCKER_MODEL_RUNNER,
    CUSTOM,
    LITELLM_PROXY,
    HOSTED_VLLM,
    TENCENT,
    LLAMAFILE,
    LM_STUDIO,
    GALADRIEL,
    NEBIUS,
    INFINITY,
    DEEPGRAM,
    ELEVENLABS,
    NOVITA,
    AIOHTTP_OPENAI,
    LANGFUSE,
    HUMANLOOP,
    TOPAZ,
    SAP_GENERATIVE_AI_HUB,
    ASSEMBLYAI,
    AZURE_SPEECH,
    CHARITY_ENGINE,
    GITHUB_COPILOT,
    SNOWFLAKE,
    GRADIENT_AI,
    LLAMA,
    NSCALE,
    PG_VECTOR,
    S3_VECTORS,
    VALKEY,
    MONGODB,
    HELICONE,
    HYPERBOLIC,
    RECRAFT,
    FAL_AI,
    STABILITY,
    HEROKU,
    AIML,
    COMETAPI,
    OCI,
    AUTO_ROUTER,
    VERCEL_AI_GATEWAY,
    EDENAI,
    DOTPROMPT,
    MANUS,
    WANDB,
    OVHCLOUD,
    SCALEWAY,
    LEMONADE,
    AMAZON_NOVA,
    A2A_AGENT,
    LANGGRAPH,
    LANGFLOW,
    MINIMAX,
    SYNTHETIC,
    APERTIS,
    NANOGPT,
    POE,
    CHUTES,
    NEOSANTARA,
    PARASAIL,
    XIAOMI_MIMO,
    TENSORMESH,
    LIBERTAI,
    PINSTRIPES,
    COGNITION,
    SCX_AI,
    DARKBLOOM,
    META,
    LITELLM_AGENT,
    CURSOR,
    BEDROCK_MANTLE,
    GDC,
}

impl LlmProviders {
    pub const VALUES: [Self; 159] = [
        Self::OPENAI,
        Self::CHATGPT,
        Self::OPENAI_LIKE,
        Self::JINA_AI,
        Self::XAI,
        Self::ZAI,
        Self::CUSTOM_OPENAI,
        Self::TEXT_COMPLETION_OPENAI,
        Self::COHERE,
        Self::COHERE_CHAT,
        Self::CLARIFAI,
        Self::ANTHROPIC,
        Self::ANTHROPIC_TEXT,
        Self::BYTEZ,
        Self::REPLICATE,
        Self::REDUCTO,
        Self::AWS_TEXTRACT,
        Self::RUNWAYML,
        Self::AWS_POLLY,
        Self::TRANSCRIBE,
        Self::HUGGINGFACE,
        Self::TOGETHER_AI,
        Self::OPENROUTER,
        Self::DATAROBOT,
        Self::VERTEX_AI,
        Self::VERTEX_AI_BETA,
        Self::GEMINI,
        Self::AI21,
        Self::BASETEN,
        Self::BLACK_FOREST_LABS,
        Self::AZURE,
        Self::AZURE_TEXT,
        Self::AZURE_AI,
        Self::SAGEMAKER,
        Self::SAGEMAKER_CHAT,
        Self::SAGEMAKER_NOVA,
        Self::BEDROCK,
        Self::VLLM,
        Self::NLP_CLOUD,
        Self::PETALS,
        Self::OOBABOOGA,
        Self::OLLAMA,
        Self::OLLAMA_CHAT,
        Self::DEEPINFRA,
        Self::PERPLEXITY,
        Self::MISTRAL,
        Self::MILVUS,
        Self::GROQ,
        Self::A2A,
        Self::GIGACHAT,
        Self::NVIDIA_NIM,
        Self::NVIDIA_RIVA,
        Self::SONIOX,
        Self::CEREBRAS,
        Self::AI21_CHAT,
        Self::VOLCENGINE,
        Self::CODESTRAL,
        Self::TEXT_COMPLETION_CODESTRAL,
        Self::DASHSCOPE,
        Self::QWENCLOUD,
        Self::QWEN_AI_PLATFORM,
        Self::MODELSCOPE,
        Self::MOONSHOT,
        Self::PUBLICAI,
        Self::V0,
        Self::MORPH,
        Self::LAMBDA_AI,
        Self::INCEPTION,
        Self::TEXT_COMPLETION_INCEPTION,
        Self::DEEPSEEK,
        Self::SAMBANOVA,
        Self::MARITALK,
        Self::VOYAGE,
        Self::CLOUDFLARE,
        Self::XINFERENCE,
        Self::FIREWORKS_AI,
        Self::FRIENDLIAI,
        Self::FEATHERLESS_AI,
        Self::WATSONX,
        Self::WATSONX_TEXT,
        Self::TRITON,
        Self::PREDIBASE,
        Self::DATABRICKS,
        Self::EMPOWER,
        Self::GITHUB,
        Self::RAGFLOW,
        Self::COMPACTIFAI,
        Self::DOCKER_MODEL_RUNNER,
        Self::CUSTOM,
        Self::LITELLM_PROXY,
        Self::HOSTED_VLLM,
        Self::TENCENT,
        Self::LLAMAFILE,
        Self::LM_STUDIO,
        Self::GALADRIEL,
        Self::NEBIUS,
        Self::INFINITY,
        Self::DEEPGRAM,
        Self::ELEVENLABS,
        Self::NOVITA,
        Self::AIOHTTP_OPENAI,
        Self::LANGFUSE,
        Self::HUMANLOOP,
        Self::TOPAZ,
        Self::SAP_GENERATIVE_AI_HUB,
        Self::ASSEMBLYAI,
        Self::AZURE_SPEECH,
        Self::CHARITY_ENGINE,
        Self::GITHUB_COPILOT,
        Self::SNOWFLAKE,
        Self::GRADIENT_AI,
        Self::LLAMA,
        Self::NSCALE,
        Self::PG_VECTOR,
        Self::S3_VECTORS,
        Self::VALKEY,
        Self::MONGODB,
        Self::HELICONE,
        Self::HYPERBOLIC,
        Self::RECRAFT,
        Self::FAL_AI,
        Self::STABILITY,
        Self::HEROKU,
        Self::AIML,
        Self::COMETAPI,
        Self::OCI,
        Self::AUTO_ROUTER,
        Self::VERCEL_AI_GATEWAY,
        Self::EDENAI,
        Self::DOTPROMPT,
        Self::MANUS,
        Self::WANDB,
        Self::OVHCLOUD,
        Self::SCALEWAY,
        Self::LEMONADE,
        Self::AMAZON_NOVA,
        Self::A2A_AGENT,
        Self::LANGGRAPH,
        Self::LANGFLOW,
        Self::MINIMAX,
        Self::SYNTHETIC,
        Self::APERTIS,
        Self::NANOGPT,
        Self::POE,
        Self::CHUTES,
        Self::NEOSANTARA,
        Self::PARASAIL,
        Self::XIAOMI_MIMO,
        Self::TENSORMESH,
        Self::LIBERTAI,
        Self::PINSTRIPES,
        Self::COGNITION,
        Self::SCX_AI,
        Self::DARKBLOOM,
        Self::META,
        Self::LITELLM_AGENT,
        Self::CURSOR,
        Self::BEDROCK_MANTLE,
        Self::GDC,
    ];

    const NAMES: [(Self, &'static str); 159] = [
        (Self::OPENAI, "openai"),
        (Self::CHATGPT, "chatgpt"),
        (Self::OPENAI_LIKE, "openai_like"),
        (Self::JINA_AI, "jina_ai"),
        (Self::XAI, "xai"),
        (Self::ZAI, "zai"),
        (Self::CUSTOM_OPENAI, "custom_openai"),
        (Self::TEXT_COMPLETION_OPENAI, "text-completion-openai"),
        (Self::COHERE, "cohere"),
        (Self::COHERE_CHAT, "cohere_chat"),
        (Self::CLARIFAI, "clarifai"),
        (Self::ANTHROPIC, "anthropic"),
        (Self::ANTHROPIC_TEXT, "anthropic_text"),
        (Self::BYTEZ, "bytez"),
        (Self::REPLICATE, "replicate"),
        (Self::REDUCTO, "reducto"),
        (Self::AWS_TEXTRACT, "aws_textract"),
        (Self::RUNWAYML, "runwayml"),
        (Self::AWS_POLLY, "aws_polly"),
        (Self::TRANSCRIBE, "transcribe"),
        (Self::HUGGINGFACE, "huggingface"),
        (Self::TOGETHER_AI, "together_ai"),
        (Self::OPENROUTER, "openrouter"),
        (Self::DATAROBOT, "datarobot"),
        (Self::VERTEX_AI, "vertex_ai"),
        (Self::VERTEX_AI_BETA, "vertex_ai_beta"),
        (Self::GEMINI, "gemini"),
        (Self::AI21, "ai21"),
        (Self::BASETEN, "baseten"),
        (Self::BLACK_FOREST_LABS, "black_forest_labs"),
        (Self::AZURE, "azure"),
        (Self::AZURE_TEXT, "azure_text"),
        (Self::AZURE_AI, "azure_ai"),
        (Self::SAGEMAKER, "sagemaker"),
        (Self::SAGEMAKER_CHAT, "sagemaker_chat"),
        (Self::SAGEMAKER_NOVA, "sagemaker_nova"),
        (Self::BEDROCK, "bedrock"),
        (Self::VLLM, "vllm"),
        (Self::NLP_CLOUD, "nlp_cloud"),
        (Self::PETALS, "petals"),
        (Self::OOBABOOGA, "oobabooga"),
        (Self::OLLAMA, "ollama"),
        (Self::OLLAMA_CHAT, "ollama_chat"),
        (Self::DEEPINFRA, "deepinfra"),
        (Self::PERPLEXITY, "perplexity"),
        (Self::MISTRAL, "mistral"),
        (Self::MILVUS, "milvus"),
        (Self::GROQ, "groq"),
        (Self::A2A, "a2a"),
        (Self::GIGACHAT, "gigachat"),
        (Self::NVIDIA_NIM, "nvidia_nim"),
        (Self::NVIDIA_RIVA, "nvidia_riva"),
        (Self::SONIOX, "soniox"),
        (Self::CEREBRAS, "cerebras"),
        (Self::AI21_CHAT, "ai21_chat"),
        (Self::VOLCENGINE, "volcengine"),
        (Self::CODESTRAL, "codestral"),
        (Self::TEXT_COMPLETION_CODESTRAL, "text-completion-codestral"),
        (Self::DASHSCOPE, "dashscope"),
        (Self::QWENCLOUD, "qwencloud"),
        (Self::QWEN_AI_PLATFORM, "qwen_ai_platform"),
        (Self::MODELSCOPE, "modelscope"),
        (Self::MOONSHOT, "moonshot"),
        (Self::PUBLICAI, "publicai"),
        (Self::V0, "v0"),
        (Self::MORPH, "morph"),
        (Self::LAMBDA_AI, "lambda_ai"),
        (Self::INCEPTION, "inception"),
        (Self::TEXT_COMPLETION_INCEPTION, "text-completion-inception"),
        (Self::DEEPSEEK, "deepseek"),
        (Self::SAMBANOVA, "sambanova"),
        (Self::MARITALK, "maritalk"),
        (Self::VOYAGE, "voyage"),
        (Self::CLOUDFLARE, "cloudflare"),
        (Self::XINFERENCE, "xinference"),
        (Self::FIREWORKS_AI, "fireworks_ai"),
        (Self::FRIENDLIAI, "friendliai"),
        (Self::FEATHERLESS_AI, "featherless_ai"),
        (Self::WATSONX, "watsonx"),
        (Self::WATSONX_TEXT, "watsonx_text"),
        (Self::TRITON, "triton"),
        (Self::PREDIBASE, "predibase"),
        (Self::DATABRICKS, "databricks"),
        (Self::EMPOWER, "empower"),
        (Self::GITHUB, "github"),
        (Self::RAGFLOW, "ragflow"),
        (Self::COMPACTIFAI, "compactifai"),
        (Self::DOCKER_MODEL_RUNNER, "docker_model_runner"),
        (Self::CUSTOM, "custom"),
        (Self::LITELLM_PROXY, "litellm_proxy"),
        (Self::HOSTED_VLLM, "hosted_vllm"),
        (Self::TENCENT, "tencent"),
        (Self::LLAMAFILE, "llamafile"),
        (Self::LM_STUDIO, "lm_studio"),
        (Self::GALADRIEL, "galadriel"),
        (Self::NEBIUS, "nebius"),
        (Self::INFINITY, "infinity"),
        (Self::DEEPGRAM, "deepgram"),
        (Self::ELEVENLABS, "elevenlabs"),
        (Self::NOVITA, "novita"),
        (Self::AIOHTTP_OPENAI, "aiohttp_openai"),
        (Self::LANGFUSE, "langfuse"),
        (Self::HUMANLOOP, "humanloop"),
        (Self::TOPAZ, "topaz"),
        (Self::SAP_GENERATIVE_AI_HUB, "sap"),
        (Self::ASSEMBLYAI, "assemblyai"),
        (Self::AZURE_SPEECH, "azure_speech"),
        (Self::CHARITY_ENGINE, "charity_engine"),
        (Self::GITHUB_COPILOT, "github_copilot"),
        (Self::SNOWFLAKE, "snowflake"),
        (Self::GRADIENT_AI, "gradient_ai"),
        (Self::LLAMA, "meta_llama"),
        (Self::NSCALE, "nscale"),
        (Self::PG_VECTOR, "pg_vector"),
        (Self::S3_VECTORS, "s3_vectors"),
        (Self::VALKEY, "valkey"),
        (Self::MONGODB, "mongodb"),
        (Self::HELICONE, "helicone"),
        (Self::HYPERBOLIC, "hyperbolic"),
        (Self::RECRAFT, "recraft"),
        (Self::FAL_AI, "fal_ai"),
        (Self::STABILITY, "stability"),
        (Self::HEROKU, "heroku"),
        (Self::AIML, "aiml"),
        (Self::COMETAPI, "cometapi"),
        (Self::OCI, "oci"),
        (Self::AUTO_ROUTER, "auto_router"),
        (Self::VERCEL_AI_GATEWAY, "vercel_ai_gateway"),
        (Self::EDENAI, "edenai"),
        (Self::DOTPROMPT, "dotprompt"),
        (Self::MANUS, "manus"),
        (Self::WANDB, "wandb"),
        (Self::OVHCLOUD, "ovhcloud"),
        (Self::SCALEWAY, "scaleway"),
        (Self::LEMONADE, "lemonade"),
        (Self::AMAZON_NOVA, "amazon_nova"),
        (Self::A2A_AGENT, "a2a_agent"),
        (Self::LANGGRAPH, "langgraph"),
        (Self::LANGFLOW, "langflow"),
        (Self::MINIMAX, "minimax"),
        (Self::SYNTHETIC, "synthetic"),
        (Self::APERTIS, "apertis"),
        (Self::NANOGPT, "nano-gpt"),
        (Self::POE, "poe"),
        (Self::CHUTES, "chutes"),
        (Self::NEOSANTARA, "neosantara"),
        (Self::PARASAIL, "parasail"),
        (Self::XIAOMI_MIMO, "xiaomi_mimo"),
        (Self::TENSORMESH, "tensormesh"),
        (Self::LIBERTAI, "libertai"),
        (Self::PINSTRIPES, "pinstripes"),
        (Self::COGNITION, "cognition"),
        (Self::SCX_AI, "scx-ai"),
        (Self::DARKBLOOM, "darkbloom"),
        (Self::META, "meta"),
        (Self::LITELLM_AGENT, "litellm_agent"),
        (Self::CURSOR, "cursor"),
        (Self::BEDROCK_MANTLE, "bedrock_mantle"),
        (Self::GDC, "gdc"),
    ];

    pub fn as_str(self) -> &'static str {
        Self::NAMES
            .iter()
            .find(|(variant, _)| *variant == self)
            .map(|(_, name)| *name)
            .expect("every variant carries its name")
    }

    pub fn parse(name: &str) -> Option<Self> {
        Self::NAMES
            .iter()
            .find(|(_, known)| *known == name)
            .map(|(variant, _)| *variant)
    }
}

impl std::fmt::Display for LlmProviders {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}
