use std::fmt;
use std::str::FromStr;

use crate::error::CoreError;

#[allow(clippy::enum_variant_names)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum LlmProvider {
    Openai,
    Chatgpt,
    OpenaiLike,
    JinaAi,
    Xai,
    Zai,
    CustomOpenai,
    TextCompletionOpenai,
    Cohere,
    CohereChat,
    Clarifai,
    Anthropic,
    AnthropicText,
    Bytez,
    Replicate,
    Reducto,
    Runwayml,
    AwsPolly,
    Huggingface,
    TogetherAi,
    Openrouter,
    Datarobot,
    VertexAi,
    VertexAiBeta,
    Gemini,
    Ai21,
    Baseten,
    BlackForestLabs,
    Azure,
    AzureText,
    AzureAi,
    Sagemaker,
    SagemakerChat,
    SagemakerNova,
    Bedrock,
    Vllm,
    NlpCloud,
    Petals,
    Oobabooga,
    Ollama,
    OllamaChat,
    Deepinfra,
    Perplexity,
    Mistral,
    Milvus,
    Groq,
    A2a,
    Gigachat,
    NvidiaNim,
    NvidiaRiva,
    Soniox,
    Cerebras,
    Ai21Chat,
    Volcengine,
    Codestral,
    TextCompletionCodestral,
    Dashscope,
    Modelscope,
    Moonshot,
    Publicai,
    V0,
    Morph,
    LambdaAi,
    Inception,
    TextCompletionInception,
    Deepseek,
    Sambanova,
    Maritalk,
    Voyage,
    Cloudflare,
    Xinference,
    FireworksAi,
    Friendliai,
    FeatherlessAi,
    Watsonx,
    WatsonxText,
    Triton,
    Predibase,
    Databricks,
    Empower,
    Github,
    Ragflow,
    Compactifai,
    DockerModelRunner,
    Custom,
    LitellmProxy,
    HostedVllm,
    Llamafile,
    LmStudio,
    Galadriel,
    Nebius,
    Infinity,
    Deepgram,
    Elevenlabs,
    Novita,
    AiohttpOpenai,
    Langfuse,
    Humanloop,
    Topaz,
    Sap,
    Assemblyai,
    CharityEngine,
    GithubCopilot,
    Snowflake,
    GradientAi,
    MetaLlama,
    Nscale,
    PgVector,
    S3Vectors,
    Helicone,
    Hyperbolic,
    Recraft,
    FalAi,
    Stability,
    Heroku,
    Aiml,
    Cometapi,
    Oci,
    AutoRouter,
    VercelAiGateway,
    Dotprompt,
    Manus,
    Wandb,
    Ovhcloud,
    Scaleway,
    Lemonade,
    AmazonNova,
    A2aAgent,
    Langgraph,
    Langflow,
    Minimax,
    Synthetic,
    Apertis,
    NanoGpt,
    Poe,
    Chutes,
    Neosantara,
    Parasail,
    XiaomiMimo,
    Tensormesh,
    Libertai,
    Pinstripes,
    Darkbloom,
    LitellmAgent,
    Cursor,
    BedrockMantle,
}

impl LlmProvider {
    #[allow(clippy::too_many_lines)]
    pub fn as_str(self) -> &'static str {
        match self {
            LlmProvider::Openai => "openai",
            LlmProvider::Chatgpt => "chatgpt",
            LlmProvider::OpenaiLike => "openai_like",
            LlmProvider::JinaAi => "jina_ai",
            LlmProvider::Xai => "xai",
            LlmProvider::Zai => "zai",
            LlmProvider::CustomOpenai => "custom_openai",
            LlmProvider::TextCompletionOpenai => "text-completion-openai",
            LlmProvider::Cohere => "cohere",
            LlmProvider::CohereChat => "cohere_chat",
            LlmProvider::Clarifai => "clarifai",
            LlmProvider::Anthropic => "anthropic",
            LlmProvider::AnthropicText => "anthropic_text",
            LlmProvider::Bytez => "bytez",
            LlmProvider::Replicate => "replicate",
            LlmProvider::Reducto => "reducto",
            LlmProvider::Runwayml => "runwayml",
            LlmProvider::AwsPolly => "aws_polly",
            LlmProvider::Huggingface => "huggingface",
            LlmProvider::TogetherAi => "together_ai",
            LlmProvider::Openrouter => "openrouter",
            LlmProvider::Datarobot => "datarobot",
            LlmProvider::VertexAi => "vertex_ai",
            LlmProvider::VertexAiBeta => "vertex_ai_beta",
            LlmProvider::Gemini => "gemini",
            LlmProvider::Ai21 => "ai21",
            LlmProvider::Baseten => "baseten",
            LlmProvider::BlackForestLabs => "black_forest_labs",
            LlmProvider::Azure => "azure",
            LlmProvider::AzureText => "azure_text",
            LlmProvider::AzureAi => "azure_ai",
            LlmProvider::Sagemaker => "sagemaker",
            LlmProvider::SagemakerChat => "sagemaker_chat",
            LlmProvider::SagemakerNova => "sagemaker_nova",
            LlmProvider::Bedrock => "bedrock",
            LlmProvider::Vllm => "vllm",
            LlmProvider::NlpCloud => "nlp_cloud",
            LlmProvider::Petals => "petals",
            LlmProvider::Oobabooga => "oobabooga",
            LlmProvider::Ollama => "ollama",
            LlmProvider::OllamaChat => "ollama_chat",
            LlmProvider::Deepinfra => "deepinfra",
            LlmProvider::Perplexity => "perplexity",
            LlmProvider::Mistral => "mistral",
            LlmProvider::Milvus => "milvus",
            LlmProvider::Groq => "groq",
            LlmProvider::A2a => "a2a",
            LlmProvider::Gigachat => "gigachat",
            LlmProvider::NvidiaNim => "nvidia_nim",
            LlmProvider::NvidiaRiva => "nvidia_riva",
            LlmProvider::Soniox => "soniox",
            LlmProvider::Cerebras => "cerebras",
            LlmProvider::Ai21Chat => "ai21_chat",
            LlmProvider::Volcengine => "volcengine",
            LlmProvider::Codestral => "codestral",
            LlmProvider::TextCompletionCodestral => "text-completion-codestral",
            LlmProvider::Dashscope => "dashscope",
            LlmProvider::Modelscope => "modelscope",
            LlmProvider::Moonshot => "moonshot",
            LlmProvider::Publicai => "publicai",
            LlmProvider::V0 => "v0",
            LlmProvider::Morph => "morph",
            LlmProvider::LambdaAi => "lambda_ai",
            LlmProvider::Inception => "inception",
            LlmProvider::TextCompletionInception => "text-completion-inception",
            LlmProvider::Deepseek => "deepseek",
            LlmProvider::Sambanova => "sambanova",
            LlmProvider::Maritalk => "maritalk",
            LlmProvider::Voyage => "voyage",
            LlmProvider::Cloudflare => "cloudflare",
            LlmProvider::Xinference => "xinference",
            LlmProvider::FireworksAi => "fireworks_ai",
            LlmProvider::Friendliai => "friendliai",
            LlmProvider::FeatherlessAi => "featherless_ai",
            LlmProvider::Watsonx => "watsonx",
            LlmProvider::WatsonxText => "watsonx_text",
            LlmProvider::Triton => "triton",
            LlmProvider::Predibase => "predibase",
            LlmProvider::Databricks => "databricks",
            LlmProvider::Empower => "empower",
            LlmProvider::Github => "github",
            LlmProvider::Ragflow => "ragflow",
            LlmProvider::Compactifai => "compactifai",
            LlmProvider::DockerModelRunner => "docker_model_runner",
            LlmProvider::Custom => "custom",
            LlmProvider::LitellmProxy => "litellm_proxy",
            LlmProvider::HostedVllm => "hosted_vllm",
            LlmProvider::Llamafile => "llamafile",
            LlmProvider::LmStudio => "lm_studio",
            LlmProvider::Galadriel => "galadriel",
            LlmProvider::Nebius => "nebius",
            LlmProvider::Infinity => "infinity",
            LlmProvider::Deepgram => "deepgram",
            LlmProvider::Elevenlabs => "elevenlabs",
            LlmProvider::Novita => "novita",
            LlmProvider::AiohttpOpenai => "aiohttp_openai",
            LlmProvider::Langfuse => "langfuse",
            LlmProvider::Humanloop => "humanloop",
            LlmProvider::Topaz => "topaz",
            LlmProvider::Sap => "sap",
            LlmProvider::Assemblyai => "assemblyai",
            LlmProvider::CharityEngine => "charity_engine",
            LlmProvider::GithubCopilot => "github_copilot",
            LlmProvider::Snowflake => "snowflake",
            LlmProvider::GradientAi => "gradient_ai",
            LlmProvider::MetaLlama => "meta_llama",
            LlmProvider::Nscale => "nscale",
            LlmProvider::PgVector => "pg_vector",
            LlmProvider::S3Vectors => "s3_vectors",
            LlmProvider::Helicone => "helicone",
            LlmProvider::Hyperbolic => "hyperbolic",
            LlmProvider::Recraft => "recraft",
            LlmProvider::FalAi => "fal_ai",
            LlmProvider::Stability => "stability",
            LlmProvider::Heroku => "heroku",
            LlmProvider::Aiml => "aiml",
            LlmProvider::Cometapi => "cometapi",
            LlmProvider::Oci => "oci",
            LlmProvider::AutoRouter => "auto_router",
            LlmProvider::VercelAiGateway => "vercel_ai_gateway",
            LlmProvider::Dotprompt => "dotprompt",
            LlmProvider::Manus => "manus",
            LlmProvider::Wandb => "wandb",
            LlmProvider::Ovhcloud => "ovhcloud",
            LlmProvider::Scaleway => "scaleway",
            LlmProvider::Lemonade => "lemonade",
            LlmProvider::AmazonNova => "amazon_nova",
            LlmProvider::A2aAgent => "a2a_agent",
            LlmProvider::Langgraph => "langgraph",
            LlmProvider::Langflow => "langflow",
            LlmProvider::Minimax => "minimax",
            LlmProvider::Synthetic => "synthetic",
            LlmProvider::Apertis => "apertis",
            LlmProvider::NanoGpt => "nano-gpt",
            LlmProvider::Poe => "poe",
            LlmProvider::Chutes => "chutes",
            LlmProvider::Neosantara => "neosantara",
            LlmProvider::Parasail => "parasail",
            LlmProvider::XiaomiMimo => "xiaomi_mimo",
            LlmProvider::Tensormesh => "tensormesh",
            LlmProvider::Libertai => "libertai",
            LlmProvider::Pinstripes => "pinstripes",
            LlmProvider::Darkbloom => "darkbloom",
            LlmProvider::LitellmAgent => "litellm_agent",
            LlmProvider::Cursor => "cursor",
            LlmProvider::BedrockMantle => "bedrock_mantle",
        }
    }

    #[allow(clippy::too_many_lines)]
    pub const ALL: [LlmProvider; 146] = [
        LlmProvider::Openai,
        LlmProvider::Chatgpt,
        LlmProvider::OpenaiLike,
        LlmProvider::JinaAi,
        LlmProvider::Xai,
        LlmProvider::Zai,
        LlmProvider::CustomOpenai,
        LlmProvider::TextCompletionOpenai,
        LlmProvider::Cohere,
        LlmProvider::CohereChat,
        LlmProvider::Clarifai,
        LlmProvider::Anthropic,
        LlmProvider::AnthropicText,
        LlmProvider::Bytez,
        LlmProvider::Replicate,
        LlmProvider::Reducto,
        LlmProvider::Runwayml,
        LlmProvider::AwsPolly,
        LlmProvider::Huggingface,
        LlmProvider::TogetherAi,
        LlmProvider::Openrouter,
        LlmProvider::Datarobot,
        LlmProvider::VertexAi,
        LlmProvider::VertexAiBeta,
        LlmProvider::Gemini,
        LlmProvider::Ai21,
        LlmProvider::Baseten,
        LlmProvider::BlackForestLabs,
        LlmProvider::Azure,
        LlmProvider::AzureText,
        LlmProvider::AzureAi,
        LlmProvider::Sagemaker,
        LlmProvider::SagemakerChat,
        LlmProvider::SagemakerNova,
        LlmProvider::Bedrock,
        LlmProvider::Vllm,
        LlmProvider::NlpCloud,
        LlmProvider::Petals,
        LlmProvider::Oobabooga,
        LlmProvider::Ollama,
        LlmProvider::OllamaChat,
        LlmProvider::Deepinfra,
        LlmProvider::Perplexity,
        LlmProvider::Mistral,
        LlmProvider::Milvus,
        LlmProvider::Groq,
        LlmProvider::A2a,
        LlmProvider::Gigachat,
        LlmProvider::NvidiaNim,
        LlmProvider::NvidiaRiva,
        LlmProvider::Soniox,
        LlmProvider::Cerebras,
        LlmProvider::Ai21Chat,
        LlmProvider::Volcengine,
        LlmProvider::Codestral,
        LlmProvider::TextCompletionCodestral,
        LlmProvider::Dashscope,
        LlmProvider::Modelscope,
        LlmProvider::Moonshot,
        LlmProvider::Publicai,
        LlmProvider::V0,
        LlmProvider::Morph,
        LlmProvider::LambdaAi,
        LlmProvider::Inception,
        LlmProvider::TextCompletionInception,
        LlmProvider::Deepseek,
        LlmProvider::Sambanova,
        LlmProvider::Maritalk,
        LlmProvider::Voyage,
        LlmProvider::Cloudflare,
        LlmProvider::Xinference,
        LlmProvider::FireworksAi,
        LlmProvider::Friendliai,
        LlmProvider::FeatherlessAi,
        LlmProvider::Watsonx,
        LlmProvider::WatsonxText,
        LlmProvider::Triton,
        LlmProvider::Predibase,
        LlmProvider::Databricks,
        LlmProvider::Empower,
        LlmProvider::Github,
        LlmProvider::Ragflow,
        LlmProvider::Compactifai,
        LlmProvider::DockerModelRunner,
        LlmProvider::Custom,
        LlmProvider::LitellmProxy,
        LlmProvider::HostedVllm,
        LlmProvider::Llamafile,
        LlmProvider::LmStudio,
        LlmProvider::Galadriel,
        LlmProvider::Nebius,
        LlmProvider::Infinity,
        LlmProvider::Deepgram,
        LlmProvider::Elevenlabs,
        LlmProvider::Novita,
        LlmProvider::AiohttpOpenai,
        LlmProvider::Langfuse,
        LlmProvider::Humanloop,
        LlmProvider::Topaz,
        LlmProvider::Sap,
        LlmProvider::Assemblyai,
        LlmProvider::CharityEngine,
        LlmProvider::GithubCopilot,
        LlmProvider::Snowflake,
        LlmProvider::GradientAi,
        LlmProvider::MetaLlama,
        LlmProvider::Nscale,
        LlmProvider::PgVector,
        LlmProvider::S3Vectors,
        LlmProvider::Helicone,
        LlmProvider::Hyperbolic,
        LlmProvider::Recraft,
        LlmProvider::FalAi,
        LlmProvider::Stability,
        LlmProvider::Heroku,
        LlmProvider::Aiml,
        LlmProvider::Cometapi,
        LlmProvider::Oci,
        LlmProvider::AutoRouter,
        LlmProvider::VercelAiGateway,
        LlmProvider::Dotprompt,
        LlmProvider::Manus,
        LlmProvider::Wandb,
        LlmProvider::Ovhcloud,
        LlmProvider::Scaleway,
        LlmProvider::Lemonade,
        LlmProvider::AmazonNova,
        LlmProvider::A2aAgent,
        LlmProvider::Langgraph,
        LlmProvider::Langflow,
        LlmProvider::Minimax,
        LlmProvider::Synthetic,
        LlmProvider::Apertis,
        LlmProvider::NanoGpt,
        LlmProvider::Poe,
        LlmProvider::Chutes,
        LlmProvider::Neosantara,
        LlmProvider::Parasail,
        LlmProvider::XiaomiMimo,
        LlmProvider::Tensormesh,
        LlmProvider::Libertai,
        LlmProvider::Pinstripes,
        LlmProvider::Darkbloom,
        LlmProvider::LitellmAgent,
        LlmProvider::Cursor,
        LlmProvider::BedrockMantle,
    ];
}

impl fmt::Display for LlmProvider {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl FromStr for LlmProvider {
    type Err = CoreError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        LlmProvider::ALL
            .iter()
            .copied()
            .find(|provider| provider.as_str() == value)
            .ok_or_else(|| CoreError::InvalidProvider(value.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const PYTHON_LLM_PROVIDER_VALUES: &[&str] = &[
        "openai",
        "chatgpt",
        "openai_like",
        "jina_ai",
        "xai",
        "zai",
        "custom_openai",
        "text-completion-openai",
        "cohere",
        "cohere_chat",
        "clarifai",
        "anthropic",
        "anthropic_text",
        "bytez",
        "replicate",
        "reducto",
        "runwayml",
        "aws_polly",
        "huggingface",
        "together_ai",
        "openrouter",
        "datarobot",
        "vertex_ai",
        "vertex_ai_beta",
        "gemini",
        "ai21",
        "baseten",
        "black_forest_labs",
        "azure",
        "azure_text",
        "azure_ai",
        "sagemaker",
        "sagemaker_chat",
        "sagemaker_nova",
        "bedrock",
        "vllm",
        "nlp_cloud",
        "petals",
        "oobabooga",
        "ollama",
        "ollama_chat",
        "deepinfra",
        "perplexity",
        "mistral",
        "milvus",
        "groq",
        "a2a",
        "gigachat",
        "nvidia_nim",
        "nvidia_riva",
        "soniox",
        "cerebras",
        "ai21_chat",
        "volcengine",
        "codestral",
        "text-completion-codestral",
        "dashscope",
        "modelscope",
        "moonshot",
        "publicai",
        "v0",
        "morph",
        "lambda_ai",
        "inception",
        "text-completion-inception",
        "deepseek",
        "sambanova",
        "maritalk",
        "voyage",
        "cloudflare",
        "xinference",
        "fireworks_ai",
        "friendliai",
        "featherless_ai",
        "watsonx",
        "watsonx_text",
        "triton",
        "predibase",
        "databricks",
        "empower",
        "github",
        "ragflow",
        "compactifai",
        "docker_model_runner",
        "custom",
        "litellm_proxy",
        "hosted_vllm",
        "llamafile",
        "lm_studio",
        "galadriel",
        "nebius",
        "infinity",
        "deepgram",
        "elevenlabs",
        "novita",
        "aiohttp_openai",
        "langfuse",
        "humanloop",
        "topaz",
        "sap",
        "assemblyai",
        "charity_engine",
        "github_copilot",
        "snowflake",
        "gradient_ai",
        "meta_llama",
        "nscale",
        "pg_vector",
        "s3_vectors",
        "helicone",
        "hyperbolic",
        "recraft",
        "fal_ai",
        "stability",
        "heroku",
        "aiml",
        "cometapi",
        "oci",
        "auto_router",
        "vercel_ai_gateway",
        "dotprompt",
        "manus",
        "wandb",
        "ovhcloud",
        "scaleway",
        "lemonade",
        "amazon_nova",
        "a2a_agent",
        "langgraph",
        "langflow",
        "minimax",
        "synthetic",
        "apertis",
        "nano-gpt",
        "poe",
        "chutes",
        "neosantara",
        "parasail",
        "xiaomi_mimo",
        "tensormesh",
        "libertai",
        "pinstripes",
        "darkbloom",
        "litellm_agent",
        "cursor",
        "bedrock_mantle",
    ];

    #[test]
    fn provider_values_match_python_enum_order() {
        assert_eq!(LlmProvider::ALL.len(), 146);
        assert_eq!(
            LlmProvider::ALL
                .iter()
                .map(|provider| provider.as_str())
                .collect::<Vec<_>>(),
            PYTHON_LLM_PROVIDER_VALUES
        );
    }

    #[test]
    fn from_str_round_trips_all_providers() {
        for provider in LlmProvider::ALL {
            assert_eq!(LlmProvider::from_str(provider.as_str()), Ok(provider));
            assert_eq!(provider.to_string(), provider.as_str());
        }
    }

    #[test]
    fn from_str_rejects_unknown_provider() {
        assert_eq!(
            LlmProvider::from_str("not-a-provider"),
            Err(CoreError::InvalidProvider("not-a-provider".to_string()))
        );
    }
}
