//! Python data formats reproduced in Rust, for state that Python LiteLLM writes and reads.
//!
//! Each module mirrors one Python operation over plain data values, and its tests replay
//! fixtures generated by that operation in CPython (`tests/fixtures/generate.py`):
//!
//! | Module | Python operation |
//! |---|---|
//! | [`literal`] | `ast.literal_eval(text)` |
//! | [`repr`] | `repr(value)` and `str(value)` |
//! | [`json`] | `json.dumps(value)`, and `json.loads(json.dumps(value))` as a JSON value |
//! | [`pickle`] | `pickle.loads(data)` and `pickle.dumps(value)` for plain data |
//! | [`truthy`] | `bool(value)` |
//!
//! [`Value`] is the closed data model these formats share. Live Python objects
//! (descriptors, `__bool__`, `__str__`, callbacks) are out of scope: those belong to the
//! PyO3 boundary in `litellm-python-bridge`, which runs the real protocol.
//!
//! Known limits, each pinned by a test:
//! - `set` iteration order follows Python's hash order, which this crate does not model
//!   (string hashes are randomized per process). Sets keep their literal order.
//! - `str` values are Rust `String`s, so lone surrogates cannot be represented.
//! - [`pickle::loads`] decodes `tuple`, `set`, and `frozenset` as lists.

pub mod json;
pub mod literal;
pub mod pickle;
pub mod repr;
pub mod truthy;

pub use num_bigint::BigInt;

/// A Python value built only from literals: what `ast.literal_eval` can return.
#[derive(Clone, Debug, PartialEq)]
pub enum Value {
    None,
    Bool(bool),
    Int(BigInt),
    Float(f64),
    Complex {
        re: f64,
        im: f64,
    },
    Str(String),
    Bytes(Vec<u8>),
    Tuple(Vec<Value>),
    List(Vec<Value>),
    /// Insertion-ordered, with Python's key equality already applied.
    Dict(Vec<(Value, Value)>),
    /// Literal order, with Python's member equality already applied.
    Set(Vec<Value>),
}

impl Value {
    /// Python's type name, as it appears in `TypeError` messages.
    pub fn type_name(&self) -> &'static str {
        match self {
            Value::None => "NoneType",
            Value::Bool(_) => "bool",
            Value::Int(_) => "int",
            Value::Float(_) => "float",
            Value::Complex { .. } => "complex",
            Value::Str(_) => "str",
            Value::Bytes(_) => "bytes",
            Value::Tuple(_) => "tuple",
            Value::List(_) => "list",
            Value::Dict(_) => "dict",
            Value::Set(_) => "set",
        }
    }
}

impl From<i64> for Value {
    fn from(value: i64) -> Self {
        Value::Int(value.into())
    }
}

impl From<&str> for Value {
    fn from(value: &str) -> Self {
        Value::Str(value.to_owned())
    }
}

/// Nesting limit for text and binary decoders. It keeps untrusted persisted data from
/// overflowing the Rust stack; CPython's own parser stops at 200 nested brackets.
pub const MAX_DEPTH: usize = 128;

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("malformed Python literal at byte {0}")]
    InvalidLiteral(usize),
    #[error("unhashable type: '{0}'")]
    Unhashable(&'static str),
    #[error("value nests deeper than {MAX_DEPTH} levels")]
    TooDeep,
    #[error("invalid pickle: {0}")]
    InvalidPickle(String),
    #[error("Object of type {0} is not JSON serializable")]
    NotJsonSerializable(&'static str),
    #[error("keys must be str, int, float, bool or None, not {0}")]
    InvalidJsonKey(&'static str),
    #[error("Out of range float values are not JSON compliant")]
    NonFiniteFloat,
    #[error("integer does not fit in the JSON number range")]
    IntegerOutOfRange,
    #[error("Object of type {0} cannot be pickled as plain data")]
    NotPicklable(&'static str),
}
