pub const VERTEXAI_PROJECT: &str = "VERTEXAI_PROJECT";
pub const VERTEXAI_LOCATION: &str = "VERTEXAI_LOCATION";
pub const VERTEXAI_CREDENTIALS: &str = "VERTEXAI_CREDENTIALS";
pub const GOOGLE_APPLICATION_CREDENTIALS: &str = "GOOGLE_APPLICATION_CREDENTIALS";
pub const GOOGLE_CLOUD_PROJECT: &str = "GOOGLE_CLOUD_PROJECT";
pub const GOOGLE_CLOUD_QUOTA_PROJECT: &str = "GOOGLE_CLOUD_QUOTA_PROJECT";
pub const CLOUD_PLATFORM_SCOPE: &str = "https://www.googleapis.com/auth/cloud-platform";
