"""
Per-feature OpenAPI snapshot for lazy-loaded routers.

The committed JSON is generated by `python -m litellm.proxy._lazy_openapi_snapshot`
and consumed at runtime so /openapi.json can show full route info for unloaded
features without importing them.

The snapshot is also an *input* to the dashboard's generated types: `npm run gen:api`
dumps the proxy spec without loading the lazy features, so their paths and schemas
come from this file verbatim. A stale fragment therefore ships stale `schema.d.ts`
types, and the UI types-sync check cannot catch it on its own (it regenerates from
this same file, so both end up agreeing with each other and disagreeing with the
code). `--check` closes that loop, and the Check UI API Types Sync workflow runs it
before regenerating the types.
"""

import json
import re
import sys
from pathlib import Path
from typing import Dict, Optional, Sequence, Set

SNAPSHOT_FILE = Path(__file__).parent / "_lazy_openapi_snapshot.json"
HTTP_METHOD_SUFFIXES = {
    "delete",
    "get",
    "head",
    "options",
    "patch",
    "post",
    "put",
    "trace",
}


def _stabilize_multi_method_route_ids(routes) -> None:
    """FastAPI derives route IDs from a set of methods; make snapshots stable."""

    for route in routes:
        methods = sorted(getattr(route, "methods", None) or [])
        if len(methods) <= 1 or not getattr(route, "path_format", None):
            continue

        operation_id = f"{route.name}{route.path_format}"
        operation_id = re.sub(r"\W", "_", operation_id)
        route.unique_id = f"{operation_id}_{methods[0].lower()}"


def load_snapshot() -> Optional[Dict[str, Dict]]:
    if not SNAPSHOT_FILE.exists():
        return None
    try:
        with SNAPSHOT_FILE.open() as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def _normalize_operation_ids(paths: Dict[str, Dict]) -> None:
    """Make FastAPI-generated operation IDs stable for multi-method routes.

    FastAPI derives the default operation ID suffix from the first item in the
    route's methods set. For routes registered with several HTTP methods, that
    set iteration order can vary between processes, which makes the snapshot
    drift even when no routes changed.
    """
    for path_ops in paths.values():
        if not isinstance(path_ops, dict):
            continue

        methods = {method for method in path_ops if method in HTTP_METHOD_SUFFIXES}
        if not methods:
            continue

        for method, operation in path_ops.items():
            if method not in HTTP_METHOD_SUFFIXES or not isinstance(operation, dict):
                continue

            operation_id = operation.get("operationId")
            if not isinstance(operation_id, str):
                continue

            for suffix in methods:
                suffix_token = f"_{suffix}"
                if operation_id.endswith(suffix_token):
                    operation["operationId"] = operation_id[: -len(suffix_token)] + f"_{method}"
                    break


def _register_lazy_feature(app, feat, preloaded: frozenset) -> tuple[str, str] | None:
    """Import and register one lazy feature. Returns (name, error) if it could not be loaded.

    `preloaded` is the set of module paths imported before registration began, not live
    sys.modules. Importing one feature can drag a sibling in as a side effect (loading
    vector_stores imports vector_store_management), and an imported-but-unregistered
    module contributes no routes, so its fragment would silently vanish from the
    snapshot. The runtime loader has the same invariant and tracks it explicitly in
    app.state.lazy_loaded.
    """
    import importlib

    if feat.module_path in preloaded:
        return None
    try:
        feat.register_fn(app, importlib.import_module(feat.module_path))
        return None
    except Exception as exc:
        return (feat.name, f"{type(exc).__name__}: {exc}")


def generate_snapshot(*, strict: bool = False) -> dict[str, dict]:
    """Build a fragment per lazy feature.

    A feature whose module fails to import is skipped, which yields an incomplete
    snapshot. That is tolerable when writing the file by hand but not when verifying
    it, so `strict` turns a skip into an error rather than silent drift.
    """
    from fastapi.openapi.utils import get_openapi

    from litellm.proxy._lazy_features import LAZY_FEATURES
    from litellm.proxy.proxy_server import app, ensure_unique_openapi_operation_ids

    preloaded = frozenset(sys.modules)
    skipped = tuple(
        result
        for result in (_register_lazy_feature(app, feat, preloaded) for feat in LAZY_FEATURES)
        if result is not None
    )
    for name, error in skipped:
        sys.stderr.write(f"warning: skip {name}: {error}\n")
    if strict and skipped:
        raise RuntimeError(
            "cannot verify the snapshot: "
            + ", ".join(f"{name} ({error})" for name, error in skipped)
            + ". Install the extras these features need, then re-run."
        )

    fragments: Dict[str, Dict] = {}
    used_operation_ids: Set[str] = set()
    for feat in LAZY_FEATURES:
        feat_routes = [r for r in app.routes if any(getattr(r, "path", "").startswith(p) for p in feat.path_prefixes)]
        if not feat_routes:
            continue
        _stabilize_multi_method_route_ids(feat_routes)
        full = get_openapi(title=app.title, version=app.version, routes=feat_routes)
        paths = full.get("paths", {})
        _normalize_operation_ids(paths)
        # Group all of a feature's routes under one tag.
        for path_ops in full.get("paths", {}).values():
            for method, op in path_ops.items():
                if isinstance(op, dict):
                    operation_id = op.get("operationId")
                    if isinstance(operation_id, str):
                        for suffix in HTTP_METHOD_SUFFIXES:
                            if operation_id.endswith(f"_{suffix}"):
                                op["operationId"] = operation_id[: -len(suffix)] + method
                                break
                    op["tags"] = [feat.name]
        full = ensure_unique_openapi_operation_ids(full, used_operation_ids)
        fragments[feat.name] = {
            "paths": paths,
            "components": {"schemas": full.get("components", {}).get("schemas", {})},
        }
    return fragments


REGEN_COMMAND = "python -m litellm.proxy._lazy_openapi_snapshot"

EXIT_IN_SYNC = 0
EXIT_DRIFTED = 1
EXIT_CANNOT_VERIFY = 2


def serialize_snapshot(fragments: dict[str, dict]) -> str:
    return json.dumps(fragments, indent=2, sort_keys=True) + "\n"


def drifted_features(committed: dict[str, dict], fresh: dict[str, dict]) -> tuple[str, ...]:
    """Feature names whose fragment was added, removed, or changed."""
    return tuple(sorted(name for name in set(committed) | set(fresh) if committed.get(name) != fresh.get(name)))


def check_snapshot() -> int:
    """Regenerate in memory and compare against the committed file.

    Returns EXIT_IN_SYNC, EXIT_DRIFTED, or EXIT_CANNOT_VERIFY. A feature that will not
    import is reported as its own outcome rather than as drift: the fragments it owns
    are simply absent from the regen, which is indistinguishable from someone deleting
    them, so calling it "stale" would send you off to regenerate a file that is fine.
    """
    try:
        fresh = generate_snapshot(strict=True)
    except RuntimeError as exc:
        sys.stderr.write(
            f"cannot verify {SNAPSHOT_FILE.name}: a lazy feature failed to import.\n\n"
            f"{exc}\n\n"
            "This is an environment problem, not snapshot drift. Install the extras the\n"
            "feature needs and re-run; do not regenerate the snapshot from here, or the\n"
            "missing feature's fragments will be dropped from the committed file.\n"
        )
        return EXIT_CANNOT_VERIFY

    committed = load_snapshot()

    if committed is not None and serialize_snapshot(committed) == serialize_snapshot(fresh):
        sys.stdout.write(f"{SNAPSHOT_FILE.name} is in sync ({len(fresh)} feature fragments).\n")
        return EXIT_IN_SYNC

    drifted = drifted_features(committed or {}, fresh)
    sys.stderr.write(
        f"{SNAPSHOT_FILE.name} is out of sync with the proxy routes.\n\n"
        "This file feeds /openapi.json for unloaded features AND the dashboard's generated\n"
        "types, so stale fragments ship stale schema.d.ts.\n\n"
        f"Drifted features ({len(drifted)}): {', '.join(drifted) or 'formatting only'}\n\n"
        f"To fix, run:\n  {REGEN_COMMAND}\n"
        "then commit the updated litellm/proxy/_lazy_openapi_snapshot.json (and re-run\n"
        "`npm run gen:api` in ui/litellm-dashboard if schema.d.ts changes).\n"
    )
    return EXIT_DRIFTED


def _main(argv: Sequence[str]) -> int:
    if "--check" in argv:
        return check_snapshot()

    fragments = generate_snapshot()
    SNAPSHOT_FILE.write_text(serialize_snapshot(fragments))
    sys.stdout.write(f"wrote {len(fragments)} feature fragments to {SNAPSHOT_FILE}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(_main(sys.argv[1:]))
