"""
Per-feature OpenAPI snapshot for lazy-loaded routers.

The committed JSON is generated by `python -m litellm.proxy._lazy_openapi_snapshot`
and consumed at runtime so /openapi.json can show full route info for unloaded
features without importing them. CI verifies the file is current and surfaces
any drift as a neutral check.
"""

import json
import sys
from pathlib import Path
from typing import Dict, Optional

SNAPSHOT_FILE = Path(__file__).parent / "_lazy_openapi_snapshot.json"


def load_snapshot() -> Optional[Dict[str, Dict]]:
    if not SNAPSHOT_FILE.exists():
        return None
    try:
        with SNAPSHOT_FILE.open() as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def generate_snapshot() -> Dict[str, Dict]:
    import importlib

    from fastapi.openapi.utils import get_openapi

    from litellm.proxy._lazy_features import LAZY_FEATURES
    from litellm.proxy.proxy_server import app

    for feat in LAZY_FEATURES:
        if feat.module_path in sys.modules:
            continue
        try:
            module = importlib.import_module(feat.module_path)
            feat.register_fn(app, module)
        except Exception as exc:
            sys.stderr.write(f"warning: skip {feat.name}: {exc}\n")

    fragments: Dict[str, Dict] = {}
    for feat in LAZY_FEATURES:
        feat_routes = [
            r
            for r in app.routes
            if any(getattr(r, "path", "").startswith(p) for p in feat.path_prefixes)
        ]
        if not feat_routes:
            continue
        full = get_openapi(title=app.title, version=app.version, routes=feat_routes)
        # Group all of a feature's routes under one tag.
        for path_ops in full.get("paths", {}).values():
            for op in path_ops.values():
                if isinstance(op, dict):
                    op["tags"] = [feat.name]
        fragments[feat.name] = {
            "paths": full.get("paths", {}),
            "components": {"schemas": full.get("components", {}).get("schemas", {})},
        }
    return fragments


if __name__ == "__main__":
    fragments = generate_snapshot()
    SNAPSHOT_FILE.write_text(json.dumps(fragments, indent=2, sort_keys=True) + "\n")
    sys.stdout.write(f"wrote {len(fragments)} feature fragments to {SNAPSHOT_FILE}\n")
