model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_base: http://host.docker.internal:8090/
  - model_name: fake-anthropic-endpoint
    litellm_params:
      model: anthropic/fake
      api_base: http://host.docker.internal:8090/

