model_list:
  - model_name: anthropic/*
    litellm_params:
      model: anthropic/*
  - model_name: openai/*
    litellm_params:
      model: openai/*
  - model_name: azure/*
    litellm_params:
      model: azure/*


litellm_settings:
  callbacks: ["datadog_llm_observability"]
  cache: true

