{{- $prev := false -}}
{{- if and .Values.serviceAccounts.gateway.create (include "litellm.workload.render" .) -}}
{{- $prev = true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litellm.gateway.serviceAccountName" . }}
  labels:
    {{- include "litellm.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- with .Values.serviceAccounts.gateway.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccounts.gateway.automount }}
{{- end }}
{{- if and .Values.serviceAccounts.backend.create (include "litellm.backend.render" .) }}
{{- if $prev }}
---
{{- end }}
{{- $prev = true }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litellm.backend.serviceAccountName" . }}
  labels:
    {{- include "litellm.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.serviceAccounts.backend.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccounts.backend.automount }}
{{- end }}
{{- if and .Values.serviceAccounts.ui.create (include "litellm.ui.render" .) }}
{{- if $prev }}
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "litellm.ui.serviceAccountName" . }}
  labels:
    {{- include "litellm.commonLabels" . | nindent 4 }}
    app.kubernetes.io/component: ui
  {{- with .Values.serviceAccounts.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccounts.ui.automount }}
{{- end }}
