-- No-op: model_spend column on LiteLLM_TeamMembership was superseded by the
-- dedicated LiteLLM_TeamMemberModelSpend table (added in the next migration).
-- The JSON approach was dropped to allow atomic per-model increment without
-- read-modify-write races under concurrent pod flushes.
