SELECT
    v.token,
    v.key_name,
    v.key_alias,
    v.soft_budget_cooldown,
    v.spend,
    v.total_spend,
    v.expires,
    v.models,
    v.aliases,
    v.config,
    v.router_settings,
    v.user_id,
    v.team_id,
    v.agent_id,
    v.project_id,
    v.permissions,
    v.max_parallel_requests,
    v.metadata,
    v.blocked,
    v.tpm_limit,
    v.rpm_limit,
    v.tpd_limit,
    v.max_budget,
    v.budget_duration,
    v.budget_reset_at,
    v.allowed_cache_controls,
    v.allowed_routes,
    v.key_type,
    v.policies,
    v.access_group_ids,
    v.model_spend,
    v.model_max_budget,
    v.budget_fallbacks,
    v.budget_id,
    v.organization_id,
    v.object_permission_id,
    v.created_at,
    v.created_by,
    v.updated_at,
    v.updated_by,
    v.settings_updated_at,
    v.last_active,
    v.rotation_count,
    v.auto_rotate,
    v.rotation_interval,
    v.last_rotation_at,
    v.key_rotation_at,
    v.budget_limits,
    t.spend AS team_spend,
    t.max_budget AS team_max_budget,
    t.soft_budget AS team_soft_budget,
    t.model_max_budget AS team_model_max_budget,
    t.tpm_limit AS team_tpm_limit,
    t.rpm_limit AS team_rpm_limit,
    t.tpd_limit AS team_tpd_limit,
    t.models AS team_models,
    t.blocked AS team_blocked,
    t.team_alias AS team_alias,
    t.metadata AS team_metadata,
    t.members_with_roles AS team_members_with_roles,
    t.object_permission_id AS team_object_permission_id,
    t.organization_id as org_id,
    p.project_alias AS project_alias,
    tm.spend AS team_member_spend,
    b_tm.tpm_limit AS team_member_tpm_limit,
    b_tm.rpm_limit AS team_member_rpm_limit,
    m.aliases AS team_model_aliases,
    b.max_budget AS litellm_budget_table_max_budget,
    b.tpm_limit AS litellm_budget_table_tpm_limit,
    b.rpm_limit AS litellm_budget_table_rpm_limit,
    b.tpd_limit AS litellm_budget_table_tpd_limit,
    b.model_max_budget as litellm_budget_table_model_max_budget,
    b.soft_budget as litellm_budget_table_soft_budget,
    o.metadata as organization_metadata,
    o.organization_alias as organization_alias,
    b2.max_budget as organization_max_budget,
    b2.tpm_limit as organization_tpm_limit,
    b2.rpm_limit as organization_rpm_limit
FROM "LiteLLM_VerificationToken" AS v
LEFT JOIN "LiteLLM_TeamTable" AS t ON v.team_id = t.team_id
LEFT JOIN "LiteLLM_TeamMembership" AS tm ON v.team_id = tm.team_id AND tm.user_id = v.user_id
LEFT JOIN "LiteLLM_BudgetTable" AS b_tm ON tm.budget_id = b_tm.budget_id
LEFT JOIN "LiteLLM_ModelTable" m ON t.model_id = m.id
LEFT JOIN "LiteLLM_BudgetTable" AS b ON v.budget_id = b.budget_id
LEFT JOIN "LiteLLM_ProjectTable" AS p ON v.project_id = p.project_id
LEFT JOIN "LiteLLM_OrganizationTable" AS o ON v.organization_id = o.organization_id
LEFT JOIN "LiteLLM_BudgetTable" AS b2 ON o.budget_id = b2.budget_id
WHERE v.token = $1
