[package]
name = "litellm-host-http"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
axum = { workspace = true, features = ["json"] }
bytes.workspace = true
futures-util.workspace = true
http.workspace = true
litellm-host.workspace = true
litellm-host-native.workspace = true
litellm-http.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
axum = { workspace = true, features = ["json"] }
rstest.workspace = true
serde_json.workspace = true
tokio.workspace = true
