-- DropIndex (CONCURRENTLY)
--
-- Disclaimer:
-- - DROP INDEX CONCURRENTLY cannot run inside a transaction. This migration must stay a
--   single statement so Prisma Migrate on PostgreSQL can apply it outside a transaction.
-- - Do not edit this file after it has been applied to any database: Prisma checksums
--   migrations; add a new migration instead.
DROP INDEX CONCURRENTLY IF EXISTS "LiteLLM_DailyTagSpend_tag_date_api_key_model_custom_llm_pro_key";
