[package]
name = "litellm-types"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
schema = ["dep:schemars"]

[dependencies]
schemars = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
strum.workspace = true

[dev-dependencies]
rstest.workspace = true
