import { Member } from "../networking";
import type { ObjectPermission } from "../object_permission_types";
import type { ModelBudgetUsage, ModelMaxBudget } from "./ModelMaxBudgetEditor";

export interface Team {
  team_id: string;
  team_alias: string;
  models: string[];
  max_budget: number | null;
  budget_duration: string | null;
  tpm_limit: number | null;
  rpm_limit: number | null;
  tpd_limit?: number | null;
  organization_id: string;
  metadata?: Record<string, unknown> | null;
  budget_reset_at?: string | null;
  blocked?: boolean;
  created_at: string;
  updated_at?: string | null;
  keys: KeyResponse[];
  keys_count?: number;
  members_count?: number;
  members_with_roles: Member[];
  team_member_permissions?: string[] | null;
  spend: number;
  access_group_ids?: string[];
  access_group_models?: string[];
  access_group_mcp_server_ids?: string[];
  access_group_agent_ids?: string[];
  // Parent org's model ceiling. undefined = no org / not loaded; [] or ["all-proxy-models"] = no ceiling.
  organization_models?: string[] | null;
}

export interface KeyResponse {
  token: string;
  token_id: string;
  key_name: string;
  key_alias: string;
  spend: number;
  total_spend: number;
  max_budget: number;
  expires: string;
  models: string[];
  aliases: Record<string, unknown>;
  config: Record<string, unknown>;
  user_id: string;
  team_id: string | null;
  project_id: string | null;
  max_parallel_requests: number;
  metadata: Record<string, unknown>;
  tpm_limit: number;
  rpm_limit: number;
  tpd_limit?: number | null;
  duration: string;
  budget_duration: string;
  budget_reset_at: string;
  allowed_cache_controls: string[];
  allowed_routes: string[];
  key_type: string | null;
  permissions: Record<string, unknown>;
  model_spend: Record<string, number>;
  model_max_budget: ModelMaxBudget;
  model_max_budget_usage?: Record<string, ModelBudgetUsage> | null;
  soft_budget_cooldown: boolean;
  blocked: boolean;
  deleted_at?: string | null;
  deleted_by?: string | null;
  litellm_budget_table: Record<string, unknown>;
  organization_id: string | null;
  org_id?: string | null;
  created_at: string;
  created_by?: string;
  updated_at: string;
  settings_updated_at?: string | null;
  last_active: string | null;
  team_spend: number;
  team_alias: string;
  team_tpm_limit: number;
  team_rpm_limit: number;
  team_max_budget: number;
  team_models: string[];
  team_blocked: boolean;
  soft_budget: number;
  team_model_aliases: Record<string, string>;
  team_member_spend: number;
  team_member?: {
    user_id: string;
    user_email: string;
    role: "admin" | "user";
  };
  team_metadata: Record<string, unknown>;
  end_user_id: string;
  end_user_tpm_limit: number;
  end_user_rpm_limit: number;
  end_user_max_budget: number;
  last_refreshed_at: number;
  api_key: string;
  user_role: "proxy_admin" | "user";
  allowed_model_region?: "eu" | "us" | string;
  parent_otel_span?: string;
  rpm_limit_per_model: Record<string, number>;
  tpm_limit_per_model: Record<string, number>;
  user_tpm_limit: number;
  user_rpm_limit: number;
  user_email: string;
  object_permission?: ObjectPermission | null;
  access_group_ids?: string[];
  budget_fallbacks?: Record<string, string[]>;
  router_settings?: Record<string, unknown> | null;
  budget_limits?: Array<{ budget_duration: string; max_budget: number; reset_at?: string }>;
  auto_rotate?: boolean;
  rotation_interval?: string;
  last_rotation_at?: string;
  key_rotation_at?: string;
  next_rotation_at?: string;
  user?: {
    user_id: string;
    user_email: string;
    user_alias: string | null;
  };
  created_by_user?: {
    user_id: string;
    user_email: string;
    user_alias: string | null;
  };
}
