"""Writes the Rust copy of the kwarg names Python's `is_litellm_owned_kwarg` accepts.

Run from the repo root: `python -m scripts.generate_owned_kwargs` (add `--check` to only verify)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Final

from litellm.constants import INTERNAL_KWARG_PREFIX
from litellm.types.utils import all_litellm_params

ROOT: Final = Path(__file__).resolve().parents[1]
TARGET: Final = ROOT / "litellm-rust/crates/owned-params/src/owned.rs"
HEADER: Final = (
    "// @generated by `python -m scripts.generate_owned_kwargs` from `litellm.types.utils.all_litellm_params`."
    " Do not edit\n"
)


def render() -> str:
    names: Final = sorted(set(all_litellm_params))
    entries: Final = "".join(f'    "{name}",\n' for name in names)
    return (
        f"{HEADER}\n"
        f'pub(crate) const INTERNAL_PREFIX: &str = "{INTERNAL_KWARG_PREFIX}";\n\n'
        "#[rustfmt::skip]\n"
        f"pub(crate) const PYTHON_OWNED: &[&str] = &[\n{entries}];\n"
    )


def main() -> int:
    parser: Final = argparse.ArgumentParser()
    _ = parser.add_argument("--check", action="store_true")
    check: Final = parser.parse_args().check is True
    expected: Final = render()
    if not check:
        _ = TARGET.write_text(expected)
        return 0
    if TARGET.read_text() == expected:
        return 0
    _ = sys.stderr.write(f"{TARGET.relative_to(ROOT)} is stale; run `python -m scripts.generate_owned_kwargs`\n")
    return 1


if __name__ == "__main__":
    sys.exit(main())
