[package]
name = "litellm-auth-azure"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
litellm-auth.workspace = true

moka.workspace = true
serde_json.workspace = true
sha2.workspace = true
strum.workspace = true
url.workspace = true

azure_core = "1.0.0"
azure_identity = { version = "1.0.0", features = ["tokio"] }

[dev-dependencies]
rstest.workspace = true
tokio.workspace = true
