from typing import Protocol


class OneShotCallbackHandle(Protocol):
    def pre_call(self, payload: object, /) -> None: ...

    def post_call(self, payload: object, /) -> None: ...

    def error(self, payload: object, /) -> None: ...


class SessionCallbackHandle(Protocol):
    def before_send(self, payload: object, /) -> object: ...

    def after_receive(self, payload: object, /) -> object: ...

    def error(self, payload: object, /) -> None: ...

    def close(self, payload: object, /) -> None: ...
