from typing import Protocol


class ProviderAttemptCallbackHandle(Protocol):
    def pre_call(self, payload: object, /) -> object: ...

    def post_call(self, payload: object, /) -> object: ...

    def error(self, payload: object, /) -> None: ...


class OneShotCallbackHandle(ProviderAttemptCallbackHandle, Protocol):
    pass


class StreamingCallbackHandle(ProviderAttemptCallbackHandle, Protocol):
    def stream_event(self, payload: object, /) -> object: ...

    def stream_close(self, payload: object, /) -> None: ...


class SessionCallbackHandle(Protocol):
    def before_connect(self, payload: object, /) -> object: ...

    def connected(self, payload: object, /) -> None: ...

    def before_send(self, payload: object, /) -> object: ...

    def after_receive(self, payload: object, /) -> object: ...

    def response_complete(self, payload: object, /) -> None: ...

    def response_error(self, payload: object, /) -> None: ...

    def error(self, payload: object, /) -> None: ...

    def close(self, payload: object, /) -> None: ...
