model_list:
  - model_name: fake-openai-endpoint
    litellm_params:
      model: openai/my-fake-model
      api_key: my-fake-key
      api_base: http://host.docker.internal:8090/

litellm_settings:
  cache: True
  cache_params:
    type: redis

