model_list:
  - model_name: fake-openai-endpoint
    litellm_params:
      model: openai/my-fake-model
      api_key: my-fake-key
      api_base: os.environ/FAKE_OPENAI_API_BASE

litellm_settings:
  cache: True
  cache_params:
    type: redis

