name: Helm OCI Chart Releaser
description: Push Helm charts to OCI-based (Docker) registries
author: sergeyshaykhullin
branding:
  color: yellow
  icon: upload-cloud
inputs:
  name:
    required: true
    description: Chart name
  repository:
    required: true
    description: Chart repository name
  tag:
    required: true
    description: Chart version
  app_version:
    required: true
    description: App version
  path:
    required: false
    description: Chart path (Default 'charts/{name}')
  registry:
    required: true
    description: OCI registry
  registry_username:
    required: true
    description: OCI registry username
  registry_password:
    required: true
    description: OCI registry password
  update_dependencies:
    required: false
    default: 'false'
    description: Update chart dependencies before packaging (Default 'false')
outputs:
  image:
    value: ${{ steps.output.outputs.image }}
    description: Chart image (Default '{registry}/{repository}/{image}:{tag}')
runs:
  using: composite
  steps:
    - name: Helm | Setup
      uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      with:
        version: v3.20.0

    - name: Helm | Login
      shell: bash
      env:
        REGISTRY_PASSWORD: ${{ inputs.registry_password }}
        REGISTRY_USERNAME: ${{ inputs.registry_username }}
        REGISTRY: ${{ inputs.registry }}
      run: echo "$REGISTRY_PASSWORD" | helm registry login -u "$REGISTRY_USERNAME" --password-stdin "$REGISTRY"

    - name: Helm | Dependency
      if: inputs.update_dependencies == 'true'
      shell: bash
      env:
        CHART_PATH: ${{ inputs.path == null && format('{0}/{1}', 'charts', inputs.name) || inputs.path }}
      run: helm dependency update "$CHART_PATH"

    - name: Helm | Package
      shell: bash
      env:
        CHART_PATH: ${{ inputs.path == null && format('{0}/{1}', 'charts', inputs.name) || inputs.path }}
        TAG: ${{ inputs.tag }}
        APP_VERSION: ${{ inputs.app_version }}
      run: helm package "$CHART_PATH" --version "$TAG" --app-version "$APP_VERSION"

    - name: Helm | Push
      shell: bash
      env:
        NAME: ${{ inputs.name }}
        TAG: ${{ inputs.tag }}
        REGISTRY: ${{ inputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
      run: helm push "${NAME}-${TAG}.tgz" "oci://${REGISTRY}/${REPOSITORY}"

    - name: Helm | Logout
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
      run: helm registry logout "$REGISTRY"

    - name: Helm | Output
      id: output
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
        NAME: ${{ inputs.name }}
        TAG: ${{ inputs.tag }}
      run: echo "image=${REGISTRY}/${REPOSITORY}/${NAME}:${TAG}" >> $GITHUB_OUTPUT
