import enum
from dataclasses import dataclass
from typing import Final

TRUSTED_CALLBACK_VARS_FIELD: Final = "litellm_trusted_callback_vars"
ADDRESSED_RESPONSE_ID_FIELD: Final = "_litellm_addressed_response_id"


class ParamGroup(enum.Enum):
    AGENTIC_LOOP_STATE = enum.auto()
    PROXY_STAMPED = enum.auto()
    BEDROCK_BATCH_CONFIG = enum.auto()
    UNCLASSIFIED = enum.auto()


@dataclass(frozen=True, slots=True)
class LiteLLMParam:
    name: str
    group: ParamGroup


def _declare(group: ParamGroup, names: tuple[str, ...]) -> tuple[LiteLLMParam, ...]:
    return tuple(LiteLLMParam(name, group) for name in names)


# Registering a name keeps it out of provider optional params. An unregistered kwarg is sent to the provider
LITELLM_PARAMS: Final[tuple[LiteLLMParam, ...]] = (
    *_declare(
        ParamGroup.AGENTIC_LOOP_STATE,
        (
            "_agentic_loop_depth",
            "_agentic_loop_fingerprints",
            "_agentic_loop_api_surface",
            "max_agentic_loops",
            "_code_interpreter_interception_active",
            "_code_interpreter_interception_sandbox_key",
            "_code_interpreter_interception_session_scoped",
            "_code_interpreter_interception_converted_stream",
            "_websearch_interception_emit_native_blocks",
            "_websearch_interception_converted_stream",
            "_headroom_interception_converted_stream",
        ),
    ),
    *_declare(ParamGroup.PROXY_STAMPED, (TRUSTED_CALLBACK_VARS_FIELD, ADDRESSED_RESPONSE_ID_FIELD)),
    *_declare(
        ParamGroup.BEDROCK_BATCH_CONFIG,
        (
            "aws_batch_role_arn",
            "s3_bucket_name",
            "s3_region_name",
            "s3_endpoint_url",
            "s3_output_bucket_name",
            "s3_bucket_owner",
            "s3_access_key_id",
            "s3_secret_access_key",
            "s3_encryption_key_id",
            "bedrock_tags",
        ),
    ),
    *_declare(
        ParamGroup.UNCLASSIFIED,
        (
            "_context_compaction_state",
            "metadata",
            "litellm_metadata",
            "keepalive_seconds",
            "allow_client_keepalive_override",
            "litellm_trace_id",
            "litellm_request_debug",
            "guardrails",
            "tags",
            "acompletion",
            "aimg_generation",
            "atext_completion",
            "text_completion",
            "caching",
            "mock_response",
            "mock_timeout",
            "disable_add_transform_inline_image_block",
            "api_key",
            "api_version",
            "prompt_id",
            "prompt_variables",
            "litellm_system_prompt",
            "provider_specific_header",
            "prompt_version",
            "prompt_environment",
            "api_base",
            "force_timeout",
            "logger_fn",
            "verbose",
            "custom_llm_provider",
            "model_file_id_mapping",
            "litellm_logging_obj",
            "litellm_call_id",
            "completion_call_id",
            "model_alias_map",
            "custom_prompt_dict",
            "stream_response",
            "cost_per_query",
            "ssl_verify",
            "data_residency",
            "async_call",
            "aembedding",
            "allm_passthrough_route",
            "_litellm_strip_stream_usage",
            "use_client",
            "id",
            "fallbacks",
            "routing_strategy",
            "_router_weights",
            "azure",
            "headers",
            "model_list",
            "num_retries",
            "context_window_fallback_dict",
            "retry_policy",
            "retry_strategy",
            "roles",
            "final_prompt_value",
            "bos_token",
            "eos_token",
            "request_timeout",
            "client_side_timeout",
            "complete_response",
            "self",
            "client",
            "rpm",
            "tpm",
            "default_api_key_rpm_limit",
            "default_api_key_tpm_limit",
            "itpm",
            "otpm",
            "max_parallel_requests",
            "input_cost_per_token",
            "output_cost_per_token",
            "input_cost_per_second",
            "output_cost_per_second",
            "hf_model_name",
            "model_info",
            "proxy_server_request",
            "secret_fields",
            "preset_cache_key",
            "caching_groups",
            "ttl",
            "cache",
            "enable_prompt_caching",
            "no-log",
            "base_model",
            "stream_timeout",
            "stream_chunk_size",
            "supports_system_message",
            "region_name",
            "allowed_model_region",
            "model_config",
            "fastest_response",
            "cooldown_time",
            "cache_key",
            "max_retries",
            "azure_ad_token_provider",
            "tenant_id",
            "client_id",
            "azure_username",
            "azure_password",
            "azure_scope",
            "client_secret",
            "user_continue_message",
            "configurable_clientside_auth_params",
            "weight",
            "ensure_alternating_roles",
            "assistant_continue_message",
            "user_continue_message",
            "fallback_depth",
            "max_fallbacks",
            "attempted_targets",
            "max_budget",
            "budget_duration",
            "use_in_pass_through",
            "merge_reasoning_content_in_choices",
            "litellm_credential_name",
            "allowed_openai_params",
            "litellm_session_id",
            "provider_affinity_header",
            "use_litellm_proxy",
            "use_chat_completions_api",
            "rust",
            "prompt_label",
            "shared_session",
            "search_tool_name",
            "order",
            "enable_tag_filtering",
            "enable_json_schema_validation",
            "use_xai_oauth",
            "auto_router_config_path",
            "auto_router_config",
            "auto_router_default_model",
            "auto_router_embedding_model",
            "auto_router_max_input_chars",
            "auto_router_routing_compression",
            "auto_router_model_compression",
            "complexity_router_config",
            "complexity_router_default_model",
            "adaptive_router_config",
            "adaptive_router_default_model",
            "quality_router_config",
            "quality_router_default_model",
        ),
    ),
)


def names_in(group: ParamGroup) -> tuple[str, ...]:
    return tuple(param.name for param in LITELLM_PARAMS if param.group is group)
