import enum
from dataclasses import dataclass
from typing import Final

TRUSTED_CALLBACK_VARS_FIELD: Final = "litellm_trusted_callback_vars"
ADDRESSED_RESPONSE_ID_FIELD: Final = "_litellm_addressed_response_id"


class ParamGroup(enum.Enum):
    AGENTIC_LOOP_STATE = enum.auto()
    BEDROCK_BATCH_CONFIG = enum.auto()
    PROXY_STAMPED = enum.auto()
    ENTRYPOINT_DISPATCH = enum.auto()
    CREDENTIALS_AND_ENDPOINT = enum.auto()
    TRANSPORT = enum.auto()
    ROUTING_AND_RELIABILITY = enum.auto()
    CACHING = enum.auto()
    COST_AND_BUDGET = enum.auto()
    OBSERVABILITY = enum.auto()
    POLICY = enum.auto()
    PROMPT_AND_RESPONSE_SHAPING = enum.auto()
    MOCKING = enum.auto()


@dataclass(frozen=True, slots=True)
class LiteLLMParam:
    name: str
    group: ParamGroup


LITELLM_PARAMS: Final[tuple[LiteLLMParam, ...]] = (
    LiteLLMParam("_agentic_loop_depth", ParamGroup.AGENTIC_LOOP_STATE),
    LiteLLMParam("_agentic_loop_fingerprints", ParamGroup.AGENTIC_LOOP_STATE),
    LiteLLMParam("_agentic_loop_api_surface", ParamGroup.AGENTIC_LOOP_STATE),
    LiteLLMParam("max_agentic_loops", ParamGroup.AGENTIC_LOOP_STATE),
    LiteLLMParam("_code_interpreter_interception_active", ParamGroup.AGENTIC_LOOP_STATE),
    LiteLLMParam("_code_interpreter_interception_sandbox_key", ParamGroup.AGENTIC_LOOP_STATE),
    LiteLLMParam("_code_interpreter_interception_session_scoped", ParamGroup.AGENTIC_LOOP_STATE),
    LiteLLMParam("_code_interpreter_interception_converted_stream", ParamGroup.AGENTIC_LOOP_STATE),
    LiteLLMParam("_websearch_interception_emit_native_blocks", ParamGroup.AGENTIC_LOOP_STATE),
    LiteLLMParam("_websearch_interception_converted_stream", ParamGroup.AGENTIC_LOOP_STATE),
    LiteLLMParam("_headroom_interception_converted_stream", ParamGroup.AGENTIC_LOOP_STATE),
    LiteLLMParam(TRUSTED_CALLBACK_VARS_FIELD, ParamGroup.PROXY_STAMPED),
    LiteLLMParam(ADDRESSED_RESPONSE_ID_FIELD, ParamGroup.PROXY_STAMPED),
    LiteLLMParam("aws_batch_role_arn", ParamGroup.BEDROCK_BATCH_CONFIG),
    LiteLLMParam("s3_bucket_name", ParamGroup.BEDROCK_BATCH_CONFIG),
    LiteLLMParam("s3_region_name", ParamGroup.BEDROCK_BATCH_CONFIG),
    LiteLLMParam("s3_endpoint_url", ParamGroup.BEDROCK_BATCH_CONFIG),
    LiteLLMParam("s3_output_bucket_name", ParamGroup.BEDROCK_BATCH_CONFIG),
    LiteLLMParam("s3_bucket_owner", ParamGroup.BEDROCK_BATCH_CONFIG),
    LiteLLMParam("s3_access_key_id", ParamGroup.BEDROCK_BATCH_CONFIG),
    LiteLLMParam("s3_secret_access_key", ParamGroup.BEDROCK_BATCH_CONFIG),
    LiteLLMParam("s3_encryption_key_id", ParamGroup.BEDROCK_BATCH_CONFIG),
    LiteLLMParam("bedrock_tags", ParamGroup.BEDROCK_BATCH_CONFIG),
    LiteLLMParam("_context_compaction_state", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("metadata", ParamGroup.OBSERVABILITY),
    LiteLLMParam("litellm_metadata", ParamGroup.OBSERVABILITY),
    LiteLLMParam("keepalive_seconds", ParamGroup.TRANSPORT),
    LiteLLMParam("allow_client_keepalive_override", ParamGroup.TRANSPORT),
    LiteLLMParam("litellm_trace_id", ParamGroup.OBSERVABILITY),
    LiteLLMParam("litellm_request_debug", ParamGroup.OBSERVABILITY),
    LiteLLMParam("guardrails", ParamGroup.POLICY),
    LiteLLMParam("tags", ParamGroup.OBSERVABILITY),
    LiteLLMParam("acompletion", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("aimg_generation", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("atext_completion", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("text_completion", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("caching", ParamGroup.CACHING),
    LiteLLMParam("mock_response", ParamGroup.MOCKING),
    LiteLLMParam("mock_timeout", ParamGroup.MOCKING),
    LiteLLMParam("disable_add_transform_inline_image_block", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("api_key", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("api_version", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("prompt_id", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("prompt_variables", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("litellm_system_prompt", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("provider_specific_header", ParamGroup.TRANSPORT),
    LiteLLMParam("prompt_version", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("prompt_environment", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("api_base", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("force_timeout", ParamGroup.TRANSPORT),
    LiteLLMParam("logger_fn", ParamGroup.OBSERVABILITY),
    LiteLLMParam("verbose", ParamGroup.OBSERVABILITY),
    LiteLLMParam("custom_llm_provider", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("model_file_id_mapping", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("litellm_logging_obj", ParamGroup.OBSERVABILITY),
    LiteLLMParam("litellm_call_id", ParamGroup.OBSERVABILITY),
    LiteLLMParam("completion_call_id", ParamGroup.OBSERVABILITY),
    LiteLLMParam("model_alias_map", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("custom_prompt_dict", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("stream_response", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("cost_per_query", ParamGroup.COST_AND_BUDGET),
    LiteLLMParam("ssl_verify", ParamGroup.TRANSPORT),
    LiteLLMParam("data_residency", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("async_call", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("aembedding", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("allm_passthrough_route", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("_litellm_strip_stream_usage", ParamGroup.PROXY_STAMPED),
    LiteLLMParam("use_client", ParamGroup.TRANSPORT),
    LiteLLMParam("id", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("fallbacks", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("routing_strategy", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("_router_weights", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("azure", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("headers", ParamGroup.TRANSPORT),
    LiteLLMParam("model_list", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("num_retries", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("context_window_fallback_dict", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("retry_policy", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("retry_strategy", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("roles", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("final_prompt_value", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("bos_token", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("eos_token", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("request_timeout", ParamGroup.TRANSPORT),
    LiteLLMParam("client_side_timeout", ParamGroup.TRANSPORT),
    LiteLLMParam("complete_response", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("self", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("client", ParamGroup.TRANSPORT),
    LiteLLMParam("rpm", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("tpm", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("default_api_key_rpm_limit", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("default_api_key_tpm_limit", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("itpm", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("otpm", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("max_parallel_requests", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("input_cost_per_token", ParamGroup.COST_AND_BUDGET),
    LiteLLMParam("output_cost_per_token", ParamGroup.COST_AND_BUDGET),
    LiteLLMParam("input_cost_per_second", ParamGroup.COST_AND_BUDGET),
    LiteLLMParam("output_cost_per_second", ParamGroup.COST_AND_BUDGET),
    LiteLLMParam("hf_model_name", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("model_info", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("proxy_server_request", ParamGroup.PROXY_STAMPED),
    LiteLLMParam("secret_fields", ParamGroup.PROXY_STAMPED),
    LiteLLMParam("preset_cache_key", ParamGroup.CACHING),
    LiteLLMParam("caching_groups", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("ttl", ParamGroup.CACHING),
    LiteLLMParam("cache", ParamGroup.CACHING),
    LiteLLMParam("enable_prompt_caching", ParamGroup.CACHING),
    LiteLLMParam("no-log", ParamGroup.OBSERVABILITY),
    LiteLLMParam("base_model", ParamGroup.COST_AND_BUDGET),
    LiteLLMParam("stream_timeout", ParamGroup.TRANSPORT),
    LiteLLMParam("stream_chunk_size", ParamGroup.TRANSPORT),
    LiteLLMParam("supports_system_message", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("region_name", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("allowed_model_region", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("model_config", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("fastest_response", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("cooldown_time", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("cache_key", ParamGroup.CACHING),
    LiteLLMParam("max_retries", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("azure_ad_token_provider", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("tenant_id", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("client_id", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("azure_username", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("azure_password", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("azure_scope", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("client_secret", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("user_continue_message", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("configurable_clientside_auth_params", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("weight", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("ensure_alternating_roles", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("assistant_continue_message", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("user_continue_message", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("fallback_depth", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("max_fallbacks", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("attempted_targets", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("max_budget", ParamGroup.COST_AND_BUDGET),
    LiteLLMParam("budget_duration", ParamGroup.COST_AND_BUDGET),
    LiteLLMParam("use_in_pass_through", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("merge_reasoning_content_in_choices", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("litellm_credential_name", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("allowed_openai_params", ParamGroup.POLICY),
    LiteLLMParam("litellm_session_id", ParamGroup.OBSERVABILITY),
    LiteLLMParam("provider_affinity_header", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("use_litellm_proxy", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("use_chat_completions_api", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("rust", ParamGroup.ENTRYPOINT_DISPATCH),
    LiteLLMParam("prompt_label", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("shared_session", ParamGroup.TRANSPORT),
    LiteLLMParam("search_tool_name", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("order", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("enable_tag_filtering", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("enable_json_schema_validation", ParamGroup.PROMPT_AND_RESPONSE_SHAPING),
    LiteLLMParam("use_xai_oauth", ParamGroup.CREDENTIALS_AND_ENDPOINT),
    LiteLLMParam("auto_router_config_path", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("auto_router_config", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("auto_router_default_model", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("auto_router_embedding_model", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("auto_router_max_input_chars", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("auto_router_routing_compression", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("auto_router_model_compression", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("complexity_router_config", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("complexity_router_default_model", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("adaptive_router_config", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("adaptive_router_default_model", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("quality_router_config", ParamGroup.ROUTING_AND_RELIABILITY),
    LiteLLMParam("quality_router_default_model", ParamGroup.ROUTING_AND_RELIABILITY),
)


def names_in(group: ParamGroup) -> tuple[str, ...]:
    return tuple(param.name for param in LITELLM_PARAMS if param.group is group)
