"""
Repository classes for database operations.
"""

from litellm.repositories.budget_repository import BudgetRepository
from litellm.repositories.config_repository import ConfigRepository
from litellm.repositories.credentials_repository import CredentialsRepository
from litellm.repositories.model_repository import ModelRepository
from litellm.repositories.object_permission_repository import (
    ObjectPermissionRepository,
)
from litellm.repositories.organization_repository import OrganizationRepository
from litellm.repositories.prisma_protocols import (
    BatchTable,
    PrismaBatch,
    PrismaRecord,
    ReadOnlyTable,
    SpendLinkedTable,
)
from litellm.repositories.project_repository import ProjectRepository
from litellm.repositories.table_repositories import (
    AccessGroupRepository,
    AdaptiveRouterSessionRepository,
    AdaptiveRouterStateRepository,
    AgentsRepository,
    AuditLogRepository,
    CacheConfigRepository,
    ClaudeCodePluginRepository,
    ConfigOverridesRepository,
    DailyGuardrailMetricsRepository,
    DailyGuardrailUsageUnitsRepository,
    DailyPolicyMetricsRepository,
    DailyTagSpendRepository,
    DailyToolSpendRepository,
    DeletedTeamRepository,
    DeletedVerificationTokenRepository,
    DeprecatedVerificationTokenRepository,
    EndUserRepository,
    GuardrailsRepository,
    HealthCheckRepository,
    InvitationLinkRepository,
    JWTKeyMappingRepository,
    ManagedFileRepository,
    ManagedObjectRepository,
    ManagedVectorStoreIndexRepository,
    ManagedVectorStoresRepository,
    MCPServerRepository,
    MCPToolsetRepository,
    MCPUserCredentialsRepository,
    MemoryRepository,
    ModelTableRepository,
    OrganizationMembershipRepository,
    PolicyAttachmentRepository,
    PolicyRepository,
    PrismaTableRepository,
    PromptRepository,
    SearchToolsRepository,
    SkillsRepository,
    SpendLogGuardrailIndexRepository,
    SpendLogsRepository,
    SpendLogToolIndexRepository,
    SSOConfigRepository,
    TagRepository,
    TeamMembershipRepository,
    ToolRepository,
    UISettingsRepository,
    UserNotificationsRepository,
    WorkflowEventRepository,
    WorkflowMessageRepository,
    WorkflowRunRepository,
)
from litellm.repositories.team_repository import TeamRepository
from litellm.repositories.unit_of_work import (
    BudgetCascadeUnitOfWork,
    BudgetWindowWrites,
    KeySpendResetWrites,
    LinkedSpendResetWrites,
    SpendResetUnitOfWork,
    TeamSpendResetWrites,
    UserSpendResetWrites,
    budget_cascade_unit_of_work,
    spend_reset_unit_of_work,
)
from litellm.repositories.user_repository import UserRepository
from litellm.repositories.verification_token_repository import (
    VerificationTokenRepository,
)

__all__ = [
    "AccessGroupRepository",
    "AdaptiveRouterSessionRepository",
    "AdaptiveRouterStateRepository",
    "AgentsRepository",
    "AuditLogRepository",
    "BatchTable",
    "BudgetCascadeUnitOfWork",
    "BudgetRepository",
    "BudgetWindowWrites",
    "CacheConfigRepository",
    "ClaudeCodePluginRepository",
    "ConfigOverridesRepository",
    "ConfigRepository",
    "CredentialsRepository",
    "DailyGuardrailMetricsRepository",
    "DailyGuardrailUsageUnitsRepository",
    "DailyPolicyMetricsRepository",
    "DailyTagSpendRepository",
    "DailyToolSpendRepository",
    "DeletedTeamRepository",
    "DeletedVerificationTokenRepository",
    "DeprecatedVerificationTokenRepository",
    "EndUserRepository",
    "GuardrailsRepository",
    "HealthCheckRepository",
    "InvitationLinkRepository",
    "JWTKeyMappingRepository",
    "KeySpendResetWrites",
    "LinkedSpendResetWrites",
    "MCPServerRepository",
    "MCPToolsetRepository",
    "MCPUserCredentialsRepository",
    "ManagedFileRepository",
    "ManagedObjectRepository",
    "ManagedVectorStoreIndexRepository",
    "ManagedVectorStoresRepository",
    "MemoryRepository",
    "ModelRepository",
    "ModelTableRepository",
    "ObjectPermissionRepository",
    "OrganizationMembershipRepository",
    "OrganizationRepository",
    "PolicyAttachmentRepository",
    "PolicyRepository",
    "PrismaBatch",
    "PrismaRecord",
    "PrismaTableRepository",
    "ProjectRepository",
    "PromptRepository",
    "ReadOnlyTable",
    "SSOConfigRepository",
    "SearchToolsRepository",
    "SkillsRepository",
    "SpendLinkedTable",
    "SpendLogGuardrailIndexRepository",
    "SpendLogToolIndexRepository",
    "SpendLogsRepository",
    "SpendResetUnitOfWork",
    "TagRepository",
    "TeamMembershipRepository",
    "TeamRepository",
    "TeamSpendResetWrites",
    "ToolRepository",
    "UISettingsRepository",
    "UserNotificationsRepository",
    "UserRepository",
    "UserSpendResetWrites",
    "VerificationTokenRepository",
    "WorkflowEventRepository",
    "WorkflowMessageRepository",
    "WorkflowRunRepository",
    "budget_cascade_unit_of_work",
    "spend_reset_unit_of_work",
]
