{{- if and .Values.gateway.config.create (not .Values.gateway.config.existingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "litellm.gateway.fullname" . }}-config
data:
  config.yaml: |
{{ .Values.gateway.config.proxy_config | toYaml | indent 6 }}
{{- end }}
