use sqlx::types::{JsonValue, chrono::NaiveDateTime};

declare_queries! {
    key_auth_combined_view(hashed_token: &str) -> KeyAuthCombinedViewRow => "../../../litellm/proxy/db/queries/keys/key_auth_combined_view.sql";
}

declare_rows! {
    struct KeyAuthCombinedViewRow {
        token: String,
        key_name: Option<String>,
        key_alias: Option<String>,
        soft_budget_cooldown: bool,
        spend: f64,
        total_spend: f64,
        expires: Option<NaiveDateTime>,
        models: Option<Vec<String>>,
        aliases: JsonValue,
        config: JsonValue,
        router_settings: Option<JsonValue>,
        user_id: Option<String>,
        team_id: Option<String>,
        agent_id: Option<String>,
        project_id: Option<String>,
        permissions: JsonValue,
        max_parallel_requests: Option<i32>,
        metadata: JsonValue,
        blocked: Option<bool>,
        tpm_limit: Option<i64>,
        rpm_limit: Option<i64>,
        tpd_limit: Option<i64>,
        max_budget: Option<f64>,
        budget_duration: Option<String>,
        budget_reset_at: Option<NaiveDateTime>,
        allowed_cache_controls: Option<Vec<String>>,
        allowed_routes: Option<Vec<String>>,
        key_type: Option<String>,
        policies: Option<Vec<String>>,
        access_group_ids: Option<Vec<String>>,
        model_spend: JsonValue,
        model_max_budget: JsonValue,
        budget_fallbacks: JsonValue,
        budget_id: Option<String>,
        organization_id: Option<String>,
        object_permission_id: Option<String>,
        created_at: Option<NaiveDateTime>,
        created_by: Option<String>,
        updated_at: Option<NaiveDateTime>,
        updated_by: Option<String>,
        settings_updated_at: Option<NaiveDateTime>,
        last_active: Option<NaiveDateTime>,
        rotation_count: Option<i32>,
        auto_rotate: Option<bool>,
        rotation_interval: Option<String>,
        last_rotation_at: Option<NaiveDateTime>,
        key_rotation_at: Option<NaiveDateTime>,
        budget_limits: Option<JsonValue>,
        team_spend: Option<f64>,
        team_max_budget: Option<f64>,
        team_soft_budget: Option<f64>,
        team_model_max_budget: Option<JsonValue>,
        team_tpm_limit: Option<i64>,
        team_rpm_limit: Option<i64>,
        team_tpd_limit: Option<i64>,
        team_models: Option<Vec<String>>,
        team_blocked: Option<bool>,
        team_alias: Option<String>,
        team_metadata: Option<JsonValue>,
        team_members_with_roles: Option<JsonValue>,
        team_object_permission_id: Option<String>,
        org_id: Option<String>,
        project_alias: Option<String>,
        team_member_spend: Option<f64>,
        team_member_tpm_limit: Option<i64>,
        team_member_rpm_limit: Option<i64>,
        team_model_aliases: Option<JsonValue>,
        litellm_budget_table_max_budget: Option<f64>,
        litellm_budget_table_tpm_limit: Option<i64>,
        litellm_budget_table_rpm_limit: Option<i64>,
        litellm_budget_table_tpd_limit: Option<i64>,
        litellm_budget_table_model_max_budget: Option<JsonValue>,
        litellm_budget_table_soft_budget: Option<f64>,
        organization_metadata: Option<JsonValue>,
        organization_alias: Option<String>,
        organization_max_budget: Option<f64>,
        organization_tpm_limit: Option<i64>,
        organization_rpm_limit: Option<i64>,
    }
}
