name: Read Version from pyproject.toml

on:
  push:
    branches:
      - main # Change this to the default branch of your repository

permissions:
  contents: read

jobs:
  read-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Read version from pyproject.toml
        id: read-version
        run: |
          version=$(grep -m1 '^version' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          printf "LITELLM_VERSION=%s" "$version" >> $GITHUB_ENV

      - name: Display version
        run: echo "Current version is $LITELLM_VERSION"
