name: Read Version from pyproject.toml

on:
  push:
    branches:
      - main # Change this to the default branch of your repository

permissions:
  contents: read

jobs:
  read-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Read version from pyproject.toml
        id: read-version
        run: |
          version=$(grep -m1 '^version' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          printf "LITELLM_VERSION=%s" "$version" >> $GITHUB_ENV

      - name: Display version
        run: echo "Current version is $LITELLM_VERSION"
