name: Validate model_prices_and_context_window.json

on:
  pull_request:
    branches:
      - main
      - litellm_internal_staging
      - litellm_oss_staging
      - "litellm_**"

permissions:
  contents: read

jobs:
  validate-model-prices-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Validate model_prices_and_context_window.json
        run: |
          jq empty model_prices_and_context_window.json
