name: "Unit Tests: Pass-Through Endpoints"

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pass-through:
    uses: ./.github/workflows/_test-unit-base.yml
    with:
      test-path: "tests/pass_through_unit_tests"
      workers: 4
      reruns: 2
